function testResults = runTestTFA(analysisSettings, outputSettings)
% runTestTFA Generate and analyze one synthetic test subject.

    signalData = createTestSignal(analysisSettings.fsTarget);

    subjectInfo.subjectID = "test";
    subjectInfo.group = "Test";
    subjectInfo.session = "simulation";
    subjectInfo.sourceFile = "Generated by createTestSignal";

    testResults = runSubjectTFA( ...
        signalData, subjectInfo, analysisSettings, outputSettings);

end
