function figureHandle = plotStatisticalGroupComparison( ...
    statisticalResults, analysisSettings)
% plotStatisticalGroupComparison Plot NC and MCI subject band values.

    values = statisticalResults.groupComparisonValues;
    comparisons = statisticalResults.groupComparisons;
    groupNames = analysisSettings.statistics.groupsToCompare(:);
    bandNames = analysisSettings.statistics.primaryBandNames(:);
    colors = analysisSettings.plot.colors.groupComparison;
    pathways = ["MAP"; "CO2"];
    metrics = ["Gain"; "Coherence"];

    figureHandle = figure( ...
        "Name", "Statistical_Group_Comparison", ...
        "NumberTitle", "off");
    plotLayout = tiledlayout( ...
        numel(metrics), numel(pathways)*numel(bandNames));

    for metricIndex = 1:numel(metrics)
        metric = metrics(metricIndex);

        for pathwayIndex = 1:numel(pathways)
            pathway = pathways(pathwayIndex);

            for bandIndex = 1:numel(bandNames)
                bandName = bandNames(bandIndex);
                ax = nexttile(plotLayout);
                hold(ax, "on")

                for groupIndex = 1:numel(groupNames)
                    rowMask = values.Group == groupNames(groupIndex) & ...
                        values.Model == "MISO" & ...
                        values.Pathway == pathway & ...
                        values.Metric == metric & ...
                        values.Band == bandName;
                    groupValues = values.Value(rowMask);
                    groupValues = groupValues(isfinite(groupValues));
                    jitter = linspace(-0.08, 0.08, numel(groupValues))';

                    scatter(ax, groupIndex + jitter, groupValues, 24, ...
                        colors(groupIndex,:), "filled", ...
                        "MarkerFaceAlpha", 0.75);

                    if ~isempty(groupValues)
                        groupMean = mean(groupValues);
                        plot(ax, groupIndex + [-0.14 0.14], ...
                            [groupMean groupMean], "k-", ...
                            "LineWidth", 1.5);

                        if numel(groupValues) >= 2
                            confidenceHalfWidth = tinv( ...
                                1 - analysisSettings.statistics.alpha/2, ...
                                numel(groupValues) - 1) * ...
                                std(groupValues)/sqrt(numel(groupValues));
                            errorbar(ax, groupIndex, groupMean, ...
                                confidenceHalfWidth, "k", ...
                                "LineStyle", "none", "CapSize", 7);
                        end
                    end
                end

                summaryMask = comparisons.Model == "MISO" & ...
                    comparisons.Pathway == pathway & ...
                    comparisons.Metric == metric & ...
                    comparisons.Band == bandName;
                if any(summaryMask)
                    summaryRow = comparisons(find(summaryMask, 1), :);
                    text(ax, 0.03, 0.97, sprintf( ...
                        "%s vs %s\ndifference=%.3g, raw P=%.3g, BH P=%.3g\nn=%d/%d", ...
                        summaryRow.FirstGroup, summaryRow.SecondGroup, ...
                        summaryRow.FirstMinusSecond, summaryRow.RawP, ...
                        summaryRow.BHAdjustedP, summaryRow.NFirst, ...
                        summaryRow.NSecond), ...
                        "Units", "normalized", ...
                        "VerticalAlignment", "top", "FontSize", 8);
                end

                xlim(ax, [0.5 numel(groupNames) + 0.5])
                xticks(ax, 1:numel(groupNames))
                xticklabels(ax, groupNames)
                ylabel(ax, "MISO " + lower(metric))
                title(ax, pathway + " - " + bandName)
                grid(ax, "on")
            end
        end
    end

    title(plotLayout, ...
        "Individual MISO values used in the group comparisons")

end
