function statusRow = createBatchStatusRow(subjectInfo, runStatus)
% createBatchStatusRow Convert one subject's run status to a table row.

    statusRow = table( ...
        string(subjectInfo.subjectID), ...
        string(subjectInfo.group), ...
        string(subjectInfo.session), ...
        string(subjectInfo.sourceFile), ...
        string(runStatus.analysisSucceeded), ...
        string(runStatus.runStage), ...
        string(runStatus.statusMessage), ...
        string(runStatus.isTooShortForWelch), ...
        runStatus.numWelchWindows, ...
        runStatus.minimumWelchWindows, ...
        runStatus.signalDurationSeconds, ...
        runStatus.windowLengthSeconds, ...
        runStatus.windowOverlap, ...
        string(runStatus.runMISO), ...
        string(runStatus.runSISO), ...
        runStatus.cbvBaselineCmPerSec, ...
        string(runStatus.cbvUnits), ...
        string(runStatus.misoUsedDefaultCoherenceThreshold), ...
        string(runStatus.sisoUsedDefaultCoherenceThreshold), ...
        runStatus.misoCoherenceThreshold, ...
        runStatus.sisoCoherenceThreshold, ...
        string(runStatus.misoCoherenceThresholdSource), ...
        string(runStatus.sisoCoherenceThresholdSource), ...
        'VariableNames', { ...
            'SubjectID', ...
            'Group', ...
            'Session', ...
            'SourceFile', ...
            'AnalysisSucceeded', ...
            'RunStage', ...
            'StatusMessage', ...
            'IsTooShortForWelch', ...
            'NumWelchWindows', ...
            'MinimumWelchWindows', ...
            'SignalDurationSeconds', ...
            'WindowLengthSeconds', ...
            'WindowOverlap', ...
            'RunMISO', ...
            'RunSISO', ...
            'CBVBaseline_cm_per_s', ...
            'CBVUnits', ...
            'MISO_UsedDefaultCoherenceThreshold', ...
            'SISO_UsedDefaultCoherenceThreshold', ...
            'MISO_CoherenceThreshold', ...
            'SISO_CoherenceThreshold', ...
            'MISO_CoherenceThresholdSource', ...
            'SISO_CoherenceThresholdSource' ...
        });

end
