function addFrequencyBandLines()

    xline(0.024, '--', 'VVLF/VLF', ...
        'LabelVerticalAlignment', 'top', ...
        'LabelHorizontalAlignment', 'center');

    xline(0.07, '--', 'VLF/LF', ...
        'LabelVerticalAlignment', 'top', ...
        'LabelHorizontalAlignment', 'center');

    xline(0.20, '--', 'LF/HF', ...
        'LabelVerticalAlignment', 'top', ...
        'LabelHorizontalAlignment', 'center');

end
