function plotPartitionedMISOwCoherence(f, H, multiple_coherence, partial_coherence, pathway_label, figure_name)

    figure('Name', figure_name, 'NumberTitle', 'off')

    bands = getFrequencyBands(f);

    plotBandMISOwCoherence( ...
        bands.vlf.f, ...
        H(bands.vlf.idx), ...
        multiple_coherence(bands.vlf.idx), ...
        partial_coherence(bands.vlf.idx), ...
        pathway_label, ...
        'VLF', ...
        1);

    plotBandMISOwCoherence( ...
        bands.lf.f, ...
        H(bands.lf.idx), ...
        multiple_coherence(bands.lf.idx), ...
        partial_coherence(bands.lf.idx), ...
        pathway_label, ...
        'LF', ...
        3);

    plotBandMISOwCoherence( ...
        bands.hf.f, ...
        H(bands.hf.idx), ...
        multiple_coherence(bands.hf.idx), ...
        partial_coherence(bands.hf.idx), ...
        pathway_label, ...
        'HF', ...
        5);

    sgtitle(['Partitioned ' pathway_label ' Transfer Function'])

end