function plotMISOResults( ...
    f, ...
    H_mapcbv, ...
    H_co2cbv, ...
    multipleCoherence, ...
    partialCohMapCbvGivenCo2, ...
    partialCohCo2CbvGivenMap, ...
    mapCbvCoherence, ...
    co2CbvCoherence, ...
    inputInputCoherence, ...
    inputInputPhase, ...
    conditionNumber, ...
    coherenceThreshold, ...
    frequencyBandEdgesHz, ...
    frequencyBandNames, ...
    figureMode)

if nargin < 15
    figureMode = "all";
end

%% Original MISO H Plot w/ Multiple and Partial Coherence Overlayed

plotMISOwCoherence( ...
    f, ...
    H_mapcbv, ...
    multipleCoherence, ...
    partialCohMapCbvGivenCo2, ...
    'MAP to CBV', ...
    'MisoMapToCbvTransferFunction');

plotMISOwCoherence( ...
    f, ...
    H_co2cbv, ...
    multipleCoherence, ...
    partialCohCo2CbvGivenMap, ...
    'CO2 to CBV', ...
    'MisoCo2ToCbvTransferFunction');

%% Coherence Plots

figure('Name', 'MisoCoherenceDiagnostics', 'NumberTitle', 'off')

subplot(2,1,1)
plot(f, mapCbvCoherence, 'LineWidth', 1.0)
hold on
plot(f, co2CbvCoherence, 'LineWidth', 1.0)
plot(f, multipleCoherence, 'LineWidth', 1.0)
xlabel('Frequency (Hz)')
ylabel('Coherence')
title('Pairwise and Multiple Coherence')
legend('MAP-CBV coherence', 'CO2-CBV coherence', 'Multiple coherence', ...
    'Location', 'best')
xlim([0.005 0.50])
ylim([0 1])
grid on
addFrequencyBandLines(frequencyBandEdgesHz, frequencyBandNames)

subplot(2,1,2)
plot(f, partialCohMapCbvGivenCo2, 'LineWidth', 1.0)
hold on
plot(f, partialCohCo2CbvGivenMap, 'LineWidth', 1.0)
plot(f, multipleCoherence, 'LineWidth', 1.0)
xlabel('Frequency (Hz)')
ylabel('Coherence')
title('Partial and Multiple Coherence')
legend('MAP-CBV | CO2', 'CO2-CBV | MAP', 'Multiple coherence', ...
    'Location', 'best')
xlim([0.005 0.50])
ylim([0 1])
grid on
addFrequencyBandLines(frequencyBandEdgesHz, frequencyBandNames)

sgtitle('MISO Coherence Diagnostics')

if figureMode == "summary"
    return
end

%% Original MISO H Plot w/ Multiple and Partial Coherence Overlayed & Partitioned into Frequency Bands

plotPartitionedMISOwCoherence( ...
    f, ...
    H_mapcbv, ...
    multipleCoherence, ...
    partialCohMapCbvGivenCo2, ...
    'MAP to CBV', ...
    'PartitionedMisoMapToCbvTransferFunction', ...
    frequencyBandEdgesHz, ...
    frequencyBandNames);

plotPartitionedMISOwCoherence( ...
    f, ...
    H_co2cbv, ...
    multipleCoherence, ...
    partialCohCo2CbvGivenMap, ...
    'CO2 to CBV', ...
    'PartitionedMisoCo2ToCbvTransferFunction', ...
    frequencyBandEdgesHz, ...
    frequencyBandNames);

%% Multiple Coherence Filtered Transfer Functions

H_mapcbvMultCohFiltered = filterByCoherence( ...
    H_mapcbv, multipleCoherence, coherenceThreshold);

H_co2cbvMultCohFiltered = filterByCoherence( ...
    H_co2cbv, multipleCoherence, coherenceThreshold);

plotFilteredMISO( ...
    f, ...
    H_mapcbvMultCohFiltered, ...
    'MAP to CBV', ...
    'Multiple Coherence Filtered', ...
    'MultCohFilteredMisoMapToCbvTransferFunction', ...
    frequencyBandEdgesHz, ...
    frequencyBandNames);

plotFilteredMISO( ...
    f, ...
    H_co2cbvMultCohFiltered, ...
    'CO2 to CBV', ...
    'Multiple Coherence Filtered', ...
    'MultCohFilteredMisoCo2ToCbvTransferFunction', ...
    frequencyBandEdgesHz, ...
    frequencyBandNames);

%% Partial Coherence Filtered Transfer Functions

H_mapcbvPartialCohFiltered = filterByCoherence( ...
    H_mapcbv, partialCohMapCbvGivenCo2, coherenceThreshold);

H_co2cbvPartialCohFiltered = filterByCoherence( ...
    H_co2cbv, partialCohCo2CbvGivenMap, coherenceThreshold);

plotFilteredMISO( ...
    f, ...
    H_mapcbvPartialCohFiltered, ...
    'MAP to CBV', ...
    'Partial Coherence Filtered', ...
    'PartCohFilteredMisoMapToCbvTransferFunction', ...
    frequencyBandEdgesHz, ...
    frequencyBandNames);

plotFilteredMISO( ...
    f, ...
    H_co2cbvPartialCohFiltered, ...
    'CO2 to CBV', ...
    'Partial Coherence Filtered', ...
    'PartCohFilteredMisoCo2ToCbvTransferFunction', ...
    frequencyBandEdgesHz, ...
    frequencyBandNames);

%% Input-Input Coherence & Spectra Phase Plots to Discuss

figure('Name', 'InputInputCoherenceAndPhase', 'NumberTitle', 'off')

subplot(1,2,1)
stem(f, inputInputCoherence, 'filled')
title('MAP-CO2 Input-Input Coherence')
xlabel('Frequency (Hz)')
ylabel('Coherence')
xlim([0.005 0.50])
grid on

subplot(1,2,2)
stem(f, inputInputPhase, 'filled')
title('MAP-CO2 Cross-Spectral Phase')
xlabel('Frequency (Hz)')
ylabel('Phase (rad)')
xlim([0.005 0.50])
grid on

sgtitle('Input-Input Relationship')

%% Condition Number Plot

figure('Name', 'MisoInputMatrixConditionNumber', 'NumberTitle', 'off')

semilogy(f, conditionNumber, 'LineWidth', 1.2)
xlabel('Frequency (Hz)')
ylabel('Condition Number')
title('Condition Number of MISO Input Matrix')
xlim([0.005 0.50])
grid on
hold on
addFrequencyBandLines(frequencyBandEdgesHz, frequencyBandNames)
xlim([0.005 0.50])

end
