function plotPartitionedMISOwCoherence(f, H, phaseData, multipleCoherence, partialCoherence, pathwayLabel, figureName, frequencyBandEdgesHz, frequencyBandNames)

    figure('Name', figureName, 'NumberTitle', 'off')

    bands = getFrequencyBands(f, frequencyBandEdgesHz, frequencyBandNames);

    plotBandMISOwCoherence( ...
        bands.vvlf.f, ...
        H(bands.vvlf.idx), ...
        phaseData.wrapped(bands.vvlf.idx), ...
        phaseData.display(bands.vvlf.idx), ...
        multipleCoherence(bands.vvlf.idx), ...
        partialCoherence(bands.vvlf.idx), ...
        pathwayLabel, ...
        'VVLF', ...
        1);

    plotBandMISOwCoherence( ...
        bands.vlf.f, ...
        H(bands.vlf.idx), ...
        phaseData.wrapped(bands.vlf.idx), ...
        phaseData.display(bands.vlf.idx), ...
        multipleCoherence(bands.vlf.idx), ...
        partialCoherence(bands.vlf.idx), ...
        pathwayLabel, ...
        'VLF', ...
        2);

    plotBandMISOwCoherence( ...
        bands.lf.f, ...
        H(bands.lf.idx), ...
        phaseData.wrapped(bands.lf.idx), ...
        phaseData.display(bands.lf.idx), ...
        multipleCoherence(bands.lf.idx), ...
        partialCoherence(bands.lf.idx), ...
        pathwayLabel, ...
        'LF', ...
        3);

    plotBandMISOwCoherence( ...
        bands.hf.f, ...
        H(bands.hf.idx), ...
        phaseData.wrapped(bands.hf.idx), ...
        phaseData.display(bands.hf.idx), ...
        multipleCoherence(bands.hf.idx), ...
        partialCoherence(bands.hf.idx), ...
        pathwayLabel, ...
        'HF', ...
        4);

    sgtitle(['Partitioned ' pathwayLabel ' Transfer Function'])

end
