classdef approachPaperStudyTest < matlab.unittest.TestCase
    % approachPaperStudyTest Verify the user-facing Paper 1 package.

    methods (TestClassSetup)
        function addProjectFolders(testCase)
            projectRoot = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    projectRoot, IncludingSubfolders=true));
        end
    end

    methods (Test)
        function settingsDescribeNcOnlyStatisticalPlan(testCase)
            settings = approachPaperSettings( ...
                "/example/data", "/example/output", "quick");
            analysis = validateTfaSettings(settings.analysis);

            testCase.verifyEqual( ...
                analysis.statistics.groupsToCompare, "NC");
            testCase.verifyEqual( ...
                analysis.statistics.primaryPathways, "MAP");
            testCase.verifyEqual( ...
                analysis.statistics.secondaryPathways, "CO2");
            testCase.verifyFalse( ...
                analysis.statistics.betweenGroupComparison.enabled);
            testCase.verifyTrue( ...
                analysis.statistics.frequencyWise.modelComparison.phase);
            testCase.verifyTrue(analysis.retainAnalysisInput);
            testCase.verifyFalse( ...
                analysis.misoSolver.regularization.enabled);
            testCase.verifyEqual( ...
                settings.simulation.observations.durationSeconds, ...
                [256 300 320 896]);
            testCase.verifyEqual( ...
                settings.simulation.observations. ...
                    referenceDurationSeconds, 300);
            testCase.verifyEqual( ...
                settings.simulation.observations.outputSnrDb, ...
                [Inf 15 0]);
            testCase.verifyEqual( ...
                settings.export.advantageColorLimit, 2);
            testCase.verifyEqual( ...
                settings.simulation.statistics.alpha, 0.05);
            testCase.verifyEqual( ...
                settings.simulation.statistics.minimumValidN, 3);
        end

        function figureExporterCreatesRequestedFile(testCase)
            outputFolder = tempname();
            mkdir(outputFolder);
            testCase.addTeardown(@() rmdir(outputFolder, "s"));
            figureHandle = plotApproachFigure1Concept();
            testCase.addTeardown(@() close(figureHandle));

            exportSettings.widthInches = 4;
            exportSettings.heightInches = 3;
            exportSettings.pngResolution = 72;
            exportSettings.savePdf = false;
            exportSettings.savePng = true;
            files = exportApproachPaperFigure( ...
                figureHandle, fullfile(outputFolder, "figure_1"), ...
                exportSettings);

            testCase.verifyEqual(numel(files), 1);
            testCase.verifyTrue(isfile(files(1)));
        end

        function plotGroupsHaveStableFolders(testCase)
            groups = approachPlotGroupDefinitions();

            testCase.verifyEqual(height(groups), 24);
            testCase.verifyEqual( ...
                groups.FolderName(3), ...
                "03_Recording_Duration");
            testCase.verifyEqual( ...
                groups.FolderName(23), ...
                "23_NC_Model_Comparison");
        end

        function advantageColormapUsesRequestedSizeAndNeutralCenter(testCase)
            colors = misoAdvantageColormap(257);

            testCase.verifySize(colors, [257 3]);
            testCase.verifyEqual( ...
                colors(129,:), [1 1 1], AbsTol=1e-12);
        end

        function modelErrorColormapsUseModelColors(testCase)
            misoColors = modelErrorColormap("miso", 16);
            sisoColors = modelErrorColormap("siso", 16);

            testCase.verifyEqual(misoColors(1,:), [1 1 1]);
            testCase.verifyEqual(sisoColors(1,:), [1 1 1]);
            testCase.verifyEqual( ...
                misoColors(end,:), [0 0.4470 0.7410], ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                sisoColors(end,:), [0.8500 0.3250 0.0980], ...
                AbsTol=1e-12);
        end

        function emptyRobustnessPanelsRemainExplicit(testCase)
            robustness.surrogateSummary = table();
            robustness.surrogateGroupDistribution = table();
            robustness.delaySummary = table();
            robustness.sensitivitySummary = table();
            robustness.lambdaSummary = table();

            [figureHandle, sourceData] = ...
                plotApproachFigure6Robustness(robustness);
            testCase.addTeardown(@() close(figureHandle));

            testCase.verifyTrue(isgraphics(figureHandle));
            testCase.verifyTrue(istable(sourceData.surrogate));
        end

        function frequencyPhaseFigureShowsBothPathways(testCase)
            frequencyHz = repmat([0.01; 0.02; 0.03], 2, 1);
            pathway = [repmat("MAP", 3, 1); repmat("CO2", 3, 1)];
            metric = repmat("Phase", 6, 1);
            misoMean = linspace(-0.4, 0.4, 6)';
            sisoMean = 0.8*misoMean;
            principalDelay = ...
                -(misoMean - sisoMean)./(2*pi*frequencyHz);
            misoCoherence = 0.5*ones(6, 1);
            sisoCoherence = 0.6*ones(6, 1);
            rawP = linspace(0.01, 0.2, 6)';
            adjustedP = min(1, 1.5*rawP);
            phaseTable = table( ...
                frequencyHz, pathway, metric, misoMean, sisoMean, ...
                principalDelay, misoCoherence, sisoCoherence, ...
                rawP, adjustedP, ...
                'VariableNames', { ...
                    'FrequencyHz', 'Pathway', 'Metric', ...
                    'MISOMean', 'SISOMean', ...
                    'PrincipalDelayDifferenceSeconds', ...
                    'MISOCoherenceMean', 'SISOCoherenceMean', ...
                    'RawP', 'BHAdjustedP'});

            [figureHandle, sourceData] = ...
                plotApproachFrequencyPhaseComparison(phaseTable);
            testCase.addTeardown(@() close(figureHandle));

            testCase.verifyTrue(isgraphics(figureHandle));
            testCase.verifyEqual( ...
                sort(unique(sourceData.Pathway)), ...
                ["CO2"; "MAP"]);
        end

        function frequencySourceWorkbookIncludesReadableGrid(testCase)
            outputFolder = tempname();
            mkdir(outputFolder);
            testCase.addTeardown(@() rmdir(outputFolder, "s"));

            sourceData.map = table( ...
                [0.05; 0.05], ["0-0.1"; "0-0.1"], ...
                [0; 0.1], [0.2; 0.4], [0.1; 0.2], ...
                [4; 3], [4; 4], ...
                'VariableNames', { ...
                    'FactorValue', 'FactorGroup', 'FrequencyHz', ...
                    'Mean', 'SD', 'ValidN', 'GroupN'});
            savedFiles = saveApproachFigureSourceData( ...
                sourceData, outputFolder, "example");
            workbook = savedFiles(endsWith(savedFiles, ".xlsx"));

            testCase.verifyEqual(numel(workbook), 1);
            sheets = string(sheetnames(workbook));
            testCase.verifyTrue(any(contains(sheets, "map_data")));
            testCase.verifyTrue(any(contains(sheets, "map_grid")));
            grid = readcell(workbook, "Sheet", ...
                sheets(contains(sheets, "map_grid")));
            testCase.verifyTrue(any(contains( ...
                string(grid(:)), "±")));
            testCase.verifyTrue(any(contains( ...
                string(grid(:)), "n=3")));
        end

        function surfaceSourceWorkbookIncludesMeanSdAndN(testCase)
            outputFolder = tempname();
            mkdir(outputFolder);
            testCase.addTeardown(@() rmdir(outputFolder, "s"));

            sourceData.surface = table( ...
                [1; 2], ["x1"; "x2"], [3; 3], ["y1"; "y1"], ...
                [0.2; 0.4], [0.1; 0.2], [7; 8], [7; 8], ...
                'VariableNames', { ...
                    'XValue', 'XGroup', 'YValue', 'YGroup', ...
                    'Mean', 'SD', 'ValidN', 'GroupN'});
            savedFiles = saveApproachFigureSourceData( ...
                sourceData, outputFolder, "surface");
            workbook = savedFiles(endsWith(savedFiles, ".xlsx"));
            sheets = string(sheetnames(workbook));
            grid = readcell(workbook, "Sheet", ...
                sheets(contains(sheets, "surface_grid")));

            testCase.verifyTrue(any(contains( ...
                string(grid(:)), "±")));
            testCase.verifyTrue(any(contains( ...
                string(grid(:)), "N=7")));
        end
    end
end
