classdef calculateSubjectBandValuesTest < matlab.unittest.TestCase
    % calculateSubjectBandValuesTest Verify shared subject band values.

    methods (TestClassSetup)
        function addProjectFolders(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(projectRoot, "src"), ...
                    "IncludingSubfolders", true));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(projectRoot, "tests", "helpers")));
        end
    end

    methods (Test)
        function arithmeticBandsUseConfiguredBoundaries(testCase)
            frequencyHz = [0.005; 0.023; 0.024; 0.069; ...
                0.070; 0.199; 0.200; 0.350];
            subjectValues = (1:8)';
            [analysisSettings, ~] = createWorkflowTestSettings( ...
                tempname(), true, true);

            result = calculateSubjectBandValues( ...
                frequencyHz, subjectValues, analysisSettings, ...
                "arithmetic");

            testCase.verifyEqual( ...
                result.values, [1.5; 3.5; 5.5; 7.5], ...
                AbsTol=1e-12);
            testCase.verifyEqual(result.numFrequencyBins, [2; 2; 2; 2]);
        end

        function phaseBandsUseCircularMeans(testCase)
            frequencyHz = [0.010; 0.020; 0.030; 0.040];
            wrappedValues = [pi - 0.1; -pi + 0.1; 0.2; 0.4];
            coherenceValues = ones(size(wrappedValues));
            [analysisSettings, ~] = createWorkflowTestSettings( ...
                tempname(), true, true);

            result = calculateSubjectBandValues( ...
                frequencyHz, wrappedValues, analysisSettings, ...
                "phaseWrapped", wrappedValues, coherenceValues);

            testCase.verifyEqual( ...
                abs(result.values(1)), pi, AbsTol=1e-12);
            testCase.verifyEqual( ...
                result.values(2), 0.3, AbsTol=1e-12);
        end
    end
end
