classdef createSyntheticSignalTest < matlab.unittest.TestCase
    % createSyntheticSignalTest Tests the Sho-style synthetic signal.

    methods (TestClassSetup)
        function addProjectToPath(testCase)
            projectFolder = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                projectFolder, IncludingSubfolders=true));
        end
    end

    methods (Test)
        function storesHorizontalSignalsAndKnownValues(testCase)
            signalData = createSyntheticSignal(4);

            testCase.verifySize(signalData.t, [1 1200]);
            testCase.verifySize(signalData.map, [1 1200]);
            testCase.verifySize(signalData.co2, [1 1200]);
            testCase.verifySize(signalData.cbv, [1 1200]);
            testCase.verifyEqual( ...
                signalData.mapTestFrequenciesHz, [0.03 0.10 0.30]);
            testCase.verifyEqual( ...
                signalData.mapTrueGain, [0.7 1.0 0.5]);
            testCase.verifyEqual( ...
                signalData.mapTruePhaseRad, [-pi/3 -pi/6 -3*pi/4], ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                signalData.co2TestFrequenciesHz, [0.05 0.11 0.40]);
            testCase.verifyEqual( ...
                signalData.co2TrueGain, [1.2 0.6 0.4]);
            testCase.verifyEqual( ...
                signalData.co2TruePhaseRad, [pi/4 pi/2 -pi/8], ...
                AbsTol=1e-12);
            testCase.verifyEqual(signalData.sharedFrequencyHz, 0.08);
            testCase.verifyEqual(signalData.cbvBaselineCmPerSec, 50);
        end

        function containsExpectedInputFrequencyPeaks(testCase)
            signalData = createSyntheticSignal(4);
            numSamples = numel(signalData.t);

            mapSpectrum = abs(fft(signalData.map - mean(signalData.map)));
            co2Spectrum = abs(fft(signalData.co2 - mean(signalData.co2)));

            mapBins = round( ...
                [signalData.mapTestFrequenciesHz, ...
                signalData.sharedFrequencyHz]*numSamples/signalData.fs) + 1;
            co2Bins = round( ...
                [signalData.co2TestFrequenciesHz, ...
                signalData.sharedFrequencyHz]*numSamples/signalData.fs) + 1;

            testCase.verifyGreaterThan( ...
                mapSpectrum(mapBins), 20*median(mapSpectrum));
            testCase.verifyGreaterThan( ...
                co2Spectrum(co2Bins), 20*median(co2Spectrum));
        end

        function normalizedPipelineRecoversKnownResponses(testCase)
            signalData = createSyntheticSignal(4);

            preprocessingSettings.normalizeCbv = true;
            preprocessingSettings.detrendEnabled = false;
            preprocessingSettings.detrendOrder = 1;
            preprocessingSettings.meanRemovalEnabled = true;

            processedSignal = preprocessTfaSignals( ...
                signalData, 4, preprocessingSettings);
            welchSettings = createTestWelchSettings();
            spectra = estimateWelchSpectra( ...
                processedSignal.map, ...
                processedSignal.co2, ...
                processedSignal.cbv, ...
                processedSignal.fs, ...
                welchSettings);
            results = runMISOTFA( ...
                spectra, createTestPhaseSettings("standard"));

            mapBins = arrayfun(@(frequencyHz) find( ...
                abs(results.f - frequencyHz) == ...
                min(abs(results.f - frequencyHz)), 1), ...
                signalData.mapTestFrequenciesHz);
            co2Bins = arrayfun(@(frequencyHz) find( ...
                abs(results.f - frequencyHz) == ...
                min(abs(results.f - frequencyHz)), 1), ...
                signalData.co2TestFrequenciesHz);

            recoveredMapGain = reshape(results.map.gain(mapBins), 1, []);
            recoveredCo2Gain = reshape(results.co2.gain(co2Bins), 1, []);
            recoveredMapPhase = reshape( ...
                results.map.phase.wrapped(mapBins), 1, []);
            recoveredCo2Phase = reshape( ...
                results.co2.phase.wrapped(co2Bins), 1, []);

            mapPhaseError = angle(exp( ...
                1i*(recoveredMapPhase - signalData.mapTruePhaseRad)));
            co2PhaseError = angle(exp( ...
                1i*(recoveredCo2Phase - signalData.co2TruePhaseRad)));

            testCase.verifyEqual( ...
                recoveredMapGain, signalData.mapTrueGain, AbsTol=0.03);
            testCase.verifyEqual( ...
                recoveredCo2Gain, signalData.co2TrueGain, AbsTol=0.03);
            testCase.verifyEqual( ...
                mapPhaseError, zeros(size(mapPhaseError)), AbsTol=0.03);
            testCase.verifyEqual( ...
                co2PhaseError, zeros(size(co2PhaseError)), AbsTol=0.03);
        end
    end
end
