classdef knownTruthSimulationTest < matlab.unittest.TestCase
    % knownTruthSimulationTest Verify the family-based simulation.

    methods (TestClassSetup)
        function addSourceFolder(testCase)
            projectFolder = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    projectFolder, IncludingSubfolders=true));
        end
    end

    methods (Test)
        function familyGeneratorIsReproducible(testCase)
            settings = smallSettings();
            design = createKnownTruthFamilyDesign(settings);

            first = createKnownTruthFamily(design(1,:), settings);
            second = createKnownTruthFamily(design(1,:), settings);

            testCase.verifyEqual( ...
                first.training.map, second.training.map);
            testCase.verifyEqual( ...
                first.training.co2, second.training.co2);
            testCase.verifyEqual( ...
                first.training.cleanCbv, second.training.cleanCbv);
            testCase.verifyEqual( ...
                first.training.truth.co2ImpulseResponse, ...
                second.training.truth.co2ImpulseResponse);
        end

        function shorterObservationIsPrefixOfSameFamily(testCase)
            settings = smallSettings();
            settings.observations.durationSeconds = [256 512];
            design = createKnownTruthFamilyDesign(settings);
            family = createKnownTruthFamily(design(1,:), settings);
            plan = createKnownTruthObservationPlan(settings);
            main = plan(plan.Experiment == "Main" & ...
                isinf(plan.OutputSNRdB), :);
            shortPlan = main(main.DurationSeconds == 256,:);
            longPlan = main(main.DurationSeconds == 512,:);

            short = createKnownTruthObservation( ...
                family.training, shortPlan);
            long = createKnownTruthObservation( ...
                family.training, longPlan);

            testCase.verifyEqual( ...
                short.map, long.map(1:numel(short.map)));
            testCase.verifyEqual( ...
                short.co2, long.co2(1:numel(short.co2)));
        end

        function studyStoresSummaryAndFrequencyResults(testCase)
            settings = smallSettings();
            results = runKnownTruthSimulationGrid(settings);

            testCase.verifyEqual( ...
                height(results.observations), ...
                settings.families.numFamilies);
            testCase.verifyEqual( ...
                height(results.ridge), ...
                settings.families.numFamilies * ...
                numel(settings.estimators.ridgeLambdas));
            expectedEstimatorRows = settings.families.numFamilies * ( ...
                numel(settings.estimatorSensitivity. ...
                    windowLengthSeconds) + ...
                numel(settings.estimatorSensitivity. ...
                    windowOverlap) + ...
                numel(settings.observations.durationSeconds)* ...
                numel(settings.estimatorSensitivity. ...
                    windowLengthSeconds));
            testCase.verifyEqual( ...
                height(results.estimatorSettings), ...
                expectedEstimatorRows);
            testCase.verifyTrue(all(ismember( ...
                ["FamilyID"; "ObservationID"; ...
                 "MAPComplexAdvantage"; "CO2PhaseAdvantage"; ...
                 "FamilyInputCoherence"; ...
                 "FamilyPSDShapeOverlap"; ...
                 "FamilyPETCO2ContributionPowerShare"], ...
                string(results.observations. ...
                Properties.VariableNames))));
            testCase.verifyEqual( ...
                size(results.frequency.map.complexAdvantage, 2), ...
                height(results.observations));
            testCase.verifySize( ...
                results.frequency.map.misoGainError, ...
                size(results.frequency.map.misoComplexError));
            testCase.verifySize( ...
                results.frequency.co2.sisoPhaseErrorRadians, ...
                size(results.frequency.co2.sisoComplexError));
            testCase.verifyTrue(all(isfinite( ...
                results.observations. ...
                MedianNormalizedConditionNumber)));
            testCase.verifyFalse(isempty(results.ridgeFrequency));
            testCase.verifyFalse(isempty(results.estimatorFrequency));

            dataRows = true(height(results.observations), 1);
            [figureHandle, sourceData] = ...
                plotSimulationFactorAbsoluteFrequencyMaps( ...
                    results, dataRows, "DurationSeconds", ...
                    "Duration (s)", "exact", "miso");
            testCase.addTeardown(@() close(figureHandle));
            testCase.verifyTrue(isfield(sourceData, "map_gain"));
            testCase.verifyTrue(isfield(sourceData, "co2_phase"));

            [componentFigure, componentSource] = ...
                plotSimulationFactorComponents( ...
                    results.observations, "DurationSeconds", ...
                    "Duration (s)", "exact");
            testCase.addTeardown(@() close(componentFigure));
            testCase.verifyFalse(ismember( ...
                "PredictionAdvantageMean", ...
                string(componentSource.Properties.VariableNames)));
            testCase.verifyTrue(ismember( ...
                "CO2ComplexAdvantageFractionPositive", ...
                string(componentSource.Properties.VariableNames)));
        end

        function favorableFamiliesUsuallyFavorMiso(testCase)
            settings = smallSettings();
            settings.families.numFamilies = 6;
            settings.families.targetCoherenceValues = [0.05 0.15 0.25];
            settings.families.spectralSimilarityValues = [0.2 0.5 0.8];
            settings.families. ...
                petco2ToMapFluctuationSdRatioValues = [0.8 1.2];
            settings.families. ...
                petco2ToMapBandGainRatioValues = [0.8 1.2];
            settings.families.co2DelaySecondsValues = [0 2];
            settings.observations.durationSeconds = 896;
            settings.observations.outputSnrDb = 30;

            results = runKnownTruthSimulationGrid(settings);

            testCase.verifyGreaterThan( ...
                median(results.observations.MAPComplexAdvantage), 0);
            testCase.verifyGreaterThan( ...
                median(results.observations.CO2ComplexAdvantage), 0);
        end

        function standardDurationAndCharacterizationAreDistinct(testCase)
            settings = smallSettings();
            settings.observations.durationSeconds = [256 896];
            settings.observations.referenceDurationSeconds = 300;
            plan = createKnownTruthObservationPlan(settings);

            testCase.verifyEqual( ...
                nnz(plan.IsReferenceObservation), 1);
            testCase.verifyEqual( ...
                plan.DurationSeconds(plan.IsReferenceObservation), 300);
            testCase.verifyEqual( ...
                nnz(plan.IsFamilyCharacterizationObservation), 1);
            testCase.verifyEqual( ...
                plan.DurationSeconds( ...
                    plan.IsFamilyCharacterizationObservation), 896);
        end

        function summariesReportMeanSdAndValidCounts(testCase)
            data = table( ...
                [1; 1; 2; 2], [1; 3; NaN; 5], ...
                'VariableNames', {'Factor', 'Metric'});
            summary = summarizeSimulationCurve( ...
                data, "Factor", "Metric", "exact", struct());

            testCase.verifyEqual(summary.GroupN, [2; 2]);
            testCase.verifyEqual(summary.MetricValidN, [2; 1]);
            testCase.verifyEqual(summary.MetricMean, [2; 5]);
            testCase.verifyEqual( ...
                summary.MetricSD, [sqrt(2); 0], AbsTol=1e-12);
        end

        function advantageStatisticsUseFamiliesAsPairedUnits(testCase)
            statistics = calculateSimulationAdvantageStatistics( ...
                [0.20; 0.25; 0.30; 0.35; 0.40], 0.05, 3);

            testCase.verifyEqual(statistics.validN, 5);
            testCase.verifyGreaterThan(statistics.ciLower, 0);
            testCase.verifyLessThan(statistics.rawP, 0.05);
        end

        function curveAndFrequencySummariesIncludeBhResults(testCase)
            factor = repelem([1; 2], 5);
            advantage = [ ...
                0.20; 0.25; 0.30; 0.35; 0.40; ...
               -0.20;-0.25;-0.30;-0.35;-0.40];
            data = table(factor, advantage, ...
                'VariableNames', { ...
                    'Factor', 'MAPComplexAdvantage'});
            statisticsSettings.alpha = 0.05;
            statisticsSettings.minimumValidN = 3;

            curve = summarizeSimulationCurve( ...
                data, "Factor", "MAPComplexAdvantage", ...
                "exact", struct(), statisticsSettings);
            testCase.verifyTrue(all( ...
                curve.MAPComplexAdvantageIsSignificant));
            testCase.verifyTrue(all(isfinite( ...
                curve.MAPComplexAdvantageBHAdjustedP)));

            frequencyValues = [advantage'; 2*advantage'];
            surface = summarizeSimulationFrequencyMap( ...
                factor, frequencyValues, "Factor", "exact", ...
                struct(), statisticsSettings);
            testCase.verifySize(surface.bhAdjustedP, [2 2]);
            testCase.verifyTrue(all(surface.isSignificant, "all"));
        end

        function referenceSummarySeparatesPrimaryAndSecondaryTests(testCase)
            numFamilies = 6;
            observations = table( ...
                (1:numFamilies)', true(numFamilies, 1), ...
                300*ones(numFamilies, 1), ...
                15*ones(numFamilies, 1), ...
                repmat((0.20:0.05:0.45)', 1, 1), ...
                repmat((0.18:0.05:0.43)', 1, 1), ...
                repmat((0.16:0.05:0.41)', 1, 1), ...
                repmat((0.14:0.05:0.39)', 1, 1), ...
                repmat((0.12:0.05:0.37)', 1, 1), ...
                repmat((0.10:0.05:0.35)', 1, 1), ...
                'VariableNames', { ...
                    'FamilyID', 'IsReferenceObservation', ...
                    'DurationSeconds', 'OutputSNRdB', ...
                    'MAPComplexAdvantage', 'MAPGainAdvantage', ...
                    'MAPPhaseAdvantage', 'CO2ComplexAdvantage', ...
                    'CO2GainAdvantage', 'CO2PhaseAdvantage'});
            simulation.observations = observations;
            simulation.settings.statistics.alpha = 0.05;
            simulation.settings.statistics.minimumValidN = 3;

            summary = createSimulationReferenceStatistics(simulation);

            testCase.verifyEqual(height(summary), 6);
            testCase.verifyTrue(summary.IsPrimary(1));
            testCase.verifyTrue(isnan(summary.BHAdjustedP(1)));
            testCase.verifyTrue(all(isfinite( ...
                summary.BHAdjustedP(~summary.IsPrimary))));
            testCase.verifyTrue(all(summary.IsSignificant));
        end

        function zeroTruePathwayHasUndefinedPhase(testCase)
            frequencyHz = [0.01; 0.02; 0.03];
            estimate = ones(3, 1);
            truth = zeros(3, 1);
            metrics = calculateKnownTruthMetrics( ...
                frequencyHz, estimate, truth, ...
                [0.01 0.03], 25);

            testCase.verifyTrue(isfinite( ...
                metrics.meanAbsoluteGainError));
            testCase.verifyTrue(isnan( ...
                metrics.meanAbsolutePhaseErrorRadians));
            testCase.verifyTrue(isnan( ...
                metrics.normalizedComplexError));
        end

        function pathwayShapesAndGainRatioMatchDesign(testCase)
            settings = smallSettings();
            settings.families.numFamilies = 1;
            settings.families.petco2ToMapBandGainRatioValues = 2;
            settings.families.co2DelaySecondsValues = 2;
            design = createKnownTruthFamilyDesign(settings);
            family = createKnownTruthFamily(design, settings);
            frequencyHz = [0.005; 0.35];
            mapResponse = freqz( ...
                family.training.truth.mapImpulseResponse, 1, ...
                frequencyHz, family.training.fs);
            co2Response = freqz( ...
                family.training.truth.co2ImpulseResponse, 1, ...
                frequencyHz, family.training.fs);

            testCase.verifyGreaterThan( ...
                abs(mapResponse(2)), abs(mapResponse(1)));
            testCase.verifyLessThan( ...
                abs(co2Response(2)), abs(co2Response(1)));
            testCase.verifyEqual( ...
                family.training.truth. ...
                    achievedPETCO2ToMAPBandGainRatio, ...
                2, RelTol=1e-10);
            testCase.verifyGreaterThan( ...
                find(family.training.truth.co2ImpulseResponse ~= 0, ...
                    1, "first"), ...
                settings.samplingFrequencyHz);
        end

        function balancedLevelsAndContributionShareAreValid(testCase)
            previousState = rng;
            cleanup = onCleanup(@() rng(previousState));
            rng(19);
            levels = createBalancedFamilyLevels([0.1 0.5 1], 11);
            counts = arrayfun(@(value) nnz(levels == value), ...
                [0.1 0.5 1]);
            testCase.verifyLessThanOrEqual( ...
                max(counts) - min(counts), 1);

            share = calculatePetco2ContributionPowerShare( ...
                [1; 2; 3], [3; 2; 1]);
            testCase.verifyGreaterThanOrEqual(share, 0);
            testCase.verifyLessThanOrEqual(share, 1);
            clear cleanup
        end

        function frequencyErrorUsesBandNormalizationAndPhaseMask(testCase)
            truth = [1; 0.001];
            estimate = [0.8; 0.2];
            errors = calculateFrequencyTruthErrors( ...
                estimate, truth, 1e-12, 0.05);

            testCase.verifyTrue(all(isfinite(errors.complex)));
            testCase.verifyTrue(isfinite(errors.phase(1)));
            testCase.verifyTrue(isnan(errors.phase(2)));
        end

        function primaryWelchSettingsYieldExpectedWindowCounts(testCase)
            settings = defaultKnownTruthSimulationSettings("quick");
            [~, info300] = getWelchWindowSettings( ...
                settings.welch, settings.samplingFrequencyHz, ...
                300*settings.samplingFrequencyHz);
            [~, info320] = getWelchWindowSettings( ...
                settings.welch, settings.samplingFrequencyHz, ...
                320*settings.samplingFrequencyHz);

            testCase.verifyEqual(info300.numWindows, 3);
            testCase.verifyEqual(info320.numWindows, 4);
            testCase.verifyTrue(info300.isReadyForTFA);
        end

        function ridgeConditioningImprovesWithLambda(testCase)
            settings = smallSettings();
            settings.families.numFamilies = 1;
            settings.estimators.ridgeLambdas = [0.001 0.1];
            results = runKnownTruthSimulationGrid(settings);
            ridge = sortrows(results.ridge, "Lambda");

            testCase.verifyLessThan( ...
                ridge.MedianRegularizedConditionNumber(end), ...
                ridge.MedianRegularizedConditionNumber(1));
        end
    end
end

function settings = smallSettings()
% smallSettings Return a fast one-observation-per-family test profile.

    settings = defaultKnownTruthSimulationSettings("quick");
    settings.families.numFamilies = 2;
    settings.families.progressEvery = 100;
    settings.observations.durationSeconds = 256;
    settings.observations.referenceDurationSeconds = 256;
    settings.observations.outputSnrDb = Inf;
    settings.observations.referenceOutputSnrDb = Inf;
    settings.observations.runInputNoiseExperiment = false;
    settings.observations.runAlignmentExperiment = false;
    settings.estimators.ridgeLambdas = 0.01;
    settings.estimatorSensitivity.windowLengthSeconds = [64 128];
    settings.estimatorSensitivity.windowOverlap = 0.5;

end
