classdef solveMisoSpectralSystemTest < matlab.unittest.TestCase
    % solveMisoSpectralSystemTest Verify the reusable MISO solver.

    methods (TestClassSetup)
        function addSourceFolder(testCase)
            projectFolder = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(projectFolder, "src"), ...
                    IncludingSubfolders=true));
        end
    end

    methods (Test)
        function normalizedConditioningDoesNotDependOnUnits(testCase)
            spectralMatrix = [4, 1.2 - 0.4i; 1.2 + 0.4i, 9];
            crossSpectrum = [1 + 0.5i; 2 - 0.25i];

            original = solveMisoSpectralSystem( ...
                spectralMatrix, crossSpectrum);

            unitChange = diag([100; 0.01]);
            scaled = solveMisoSpectralSystem( ...
                unitChange*spectralMatrix*unitChange, ...
                unitChange*crossSpectrum);

            testCase.verifyEqual( ...
                scaled.normalizedConditionNumber, ...
                original.normalizedConditionNumber, ...
                RelTol=1e-12);
            testCase.verifyEqual( ...
                scaled.normalizedDeterminant, ...
                original.normalizedDeterminant, ...
                AbsTol=1e-12);
            testCase.verifyNotEqual( ...
                scaled.rawConditionNumber, ...
                original.rawConditionNumber);
        end

        function determinantMatchesInputCoherenceIdentity(testCase)
            inputCoherence = 0.64;
            crossTerm = sqrt(inputCoherence)*exp(1i*pi/5);
            spectralMatrix = [1, conj(crossTerm); crossTerm, 1];
            crossSpectrum = [1; 0.5];

            solution = solveMisoSpectralSystem( ...
                spectralMatrix, crossSpectrum);

            testCase.verifyEqual( ...
                solution.normalizedDeterminant, ...
                1 - inputCoherence, AbsTol=1e-12);
        end

        function zeroLambdaMatchesDirectSolution(testCase)
            spectralMatrix = [2, 0.7; 0.7, 3];
            crossSpectrum = [1 + 0.2i; 0.4 - 0.3i];
            settings = defaultMisoSolverSettings();
            settings.regularization.enabled = true;
            settings.regularization.lambda = 0;

            solution = solveMisoSpectralSystem( ...
                spectralMatrix, crossSpectrum, settings);

            testCase.verifyEqual( ...
                solution.ridgeCoefficients, ...
                solution.unregularizedCoefficients, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                solution.selectedCoefficients, ...
                solution.unregularizedCoefficients, ...
                AbsTol=1e-12);
        end

        function ridgeStabilizesNearCollinearInputs(testCase)
            spectralMatrix = [1, 0.999999; 0.999999, 1];
            crossSpectrum = [1; 0];
            settings = defaultMisoSolverSettings();
            settings.regularization.enabled = true;
            settings.regularization.lambda = 0.05;

            solution = solveMisoSpectralSystem( ...
                spectralMatrix, crossSpectrum, settings);

            testCase.verifyTrue(solution.isPoorlyConditioned);
            testCase.verifyTrue(all(isfinite( ...
                solution.selectedCoefficients)));
            testCase.verifyLessThan( ...
                norm(solution.selectedCoefficients), ...
                norm(solution.unregularizedCoefficients));
        end
    end
end
