classdef statisticalAnalysisTest < matlab.unittest.TestCase
    % statisticalAnalysisTest Verify batch statistics and Excel sheets.

    methods (TestClassSetup)
        function addProjectFolders(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(projectRoot, "src"), ...
                    "IncludingSubfolders", true));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(projectRoot, "tests", "helpers")));
        end
    end

    methods (Test)
        function oneGroupApproachAnalysisUsesNamedFamilies(testCase)
            outputFolder = tempname();
            testCase.addTeardown(@() rmdir(outputFolder, "s"));
            baseSubject = runSelectedWorkflow( ...
                outputFolder, true, true);

            firstNcSubject = baseSubject;
            firstNcSubject.subjectInfo.group = "NC";
            firstNcSubject.subjectInfo.subjectID = "1001";
            secondNcSubject = firstNcSubject;
            secondNcSubject.subjectInfo.subjectID = "1002";
            secondNcSubject.misoResults.map.gain = ...
                1.1*secondNcSubject.misoResults.map.gain;
            allSubjects = {firstNcSubject; secondNcSubject};

            [analysisSettings, ~] = createWorkflowTestSettings( ...
                outputFolder, true, true);
            analysisSettings.statistics.enabled = true;
            analysisSettings.statistics.groupsToCompare = "NC";
            analysisSettings.statistics.primaryBandNames = ...
                analysisSettings.frequencyBandNames;
            analysisSettings.statistics.primaryGroups = "NC";
            analysisSettings.statistics.primaryPathways = "MAP";
            analysisSettings.statistics.secondaryPathways = "CO2";
            analysisSettings.statistics.withinGroupModelComparison.enabled = ...
                true;
            analysisSettings.statistics.betweenGroupComparison.enabled = ...
                false;
            analysisSettings.statistics.frequencyWise.enabled = true;
            analysisSettings = validateTfaSettings(analysisSettings);

            groupResults = createGroupResults( ...
                allSubjects, "NC", true, true, ...
                analysisSettings.phase);
            results = calculateStatisticalResults( ...
                allSubjects, groupResults, analysisSettings);

            primaryRows = results.modelComparisons.Pathway == "MAP" & ...
                results.modelComparisons.Metric == "Gain";
            secondaryRows = results.modelComparisons.Pathway == "CO2" & ...
                results.modelComparisons.Metric == "Gain";

            testCase.verifyEmpty(results.groupComparisons);
            testCase.verifyEmpty(results.frequencyGroupComparisons);
            testCase.verifyTrue(all( ...
                results.modelComparisons.IsPrimary(primaryRows)));
            testCase.verifyEqual( ...
                unique(results.modelComparisons.MultiplicityFamily( ...
                    primaryRows)), ...
                "NC_MAP_GAIN_PRIMARY");
            testCase.verifyEqual( ...
                unique(results.modelComparisons.MultiplicityFamily( ...
                    secondaryRows)), ...
                "NC_CO2_GAIN_SECONDARY");

            frequencyPhase = ...
                results.frequencyModelComparisons( ...
                results.frequencyModelComparisons.Metric == "Phase", :);
            positiveFrequencyRows = frequencyPhase.FrequencyHz > 0;
            expectedDelayDifference = ...
                -frequencyPhase.MISOminusSISO(positiveFrequencyRows) ./ ...
                (2*pi*frequencyPhase.FrequencyHz( ...
                positiveFrequencyRows));
            testCase.verifyEqual( ...
                frequencyPhase.PrincipalDelayDifferenceSeconds( ...
                    positiveFrequencyRows), ...
                expectedDelayDifference, AbsTol=1e-12);
            testCase.verifyTrue(all( ...
                frequencyPhase.DelayModuloSeconds( ...
                    positiveFrequencyRows) > 0));
            testCase.verifyTrue(all( ...
                startsWith( ...
                    frequencyPhase.MultiplicityFamily, ...
                    "FREQUENCY_NC_")));
        end

        function statisticsUseMatchedSubjectBandValues(testCase)
            outputFolder = tempname();
            testCase.addTeardown(@() rmdir(outputFolder, "s"));
            baseSubject = runSelectedWorkflow( ...
                outputFolder, true, true);

            firstNcSubject = baseSubject;
            firstNcSubject.subjectInfo.group = "NC";
            firstNcSubject.subjectInfo.subjectID = "1001";
            secondNcSubject = firstNcSubject;
            secondNcSubject.subjectInfo.subjectID = "1002";
            secondNcSubject.misoResults.map.gain = ...
                1.1*secondNcSubject.misoResults.map.gain;

            firstMciSubject = baseSubject;
            firstMciSubject.subjectInfo.group = "MCI";
            firstMciSubject.subjectInfo.subjectID = "2001";
            firstMciSubject.misoResults.map.gain = ...
                1.2*firstMciSubject.misoResults.map.gain;
            secondMciSubject = firstMciSubject;
            secondMciSubject.subjectInfo.subjectID = "2002";
            secondMciSubject.misoResults.map.gain = ...
                1.1*secondMciSubject.misoResults.map.gain;

            allSubjects = { ...
                firstNcSubject; secondNcSubject; ...
                firstMciSubject; secondMciSubject};
            [analysisSettings, ~] = createWorkflowTestSettings( ...
                outputFolder, true, true);
            analysisSettings.statistics.enabled = true;
            analysisSettings.statistics.frequencyWise.enabled = true;
            analysisSettings.statistics.frequencyWise.groupComparison.coherence = false;
            groupResults = createGroupResults( ...
                allSubjects, ["NC"; "MCI"], true, true, ...
                analysisSettings.phase);

            results = calculateStatisticalResults( ...
                allSubjects, groupResults, analysisSettings);

            modelRowMask = results.modelComparisons.Group == "NC" & ...
                results.modelComparisons.Pathway == "MAP" & ...
                results.modelComparisons.Metric == "Gain" & ...
                results.modelComparisons.Band == "VLF";
            modelRow = results.modelComparisons(modelRowMask, :);
            groupRowMask = results.groupComparisons.Model == "MISO" & ...
                results.groupComparisons.Pathway == "MAP" & ...
                results.groupComparisons.Metric == "Gain" & ...
                results.groupComparisons.Band == "VLF";
            groupRow = results.groupComparisons(groupRowMask, :);

            testCase.verifyEqual(modelRow.N, 2);
            testCase.verifyEqual(groupRow.NFirst, 2);
            testCase.verifyEqual(groupRow.NSecond, 2);
            testCase.verifyTrue(ismember( ...
                "BHAdjustedP", ...
                string(results.modelComparisons.Properties.VariableNames)));
            testCase.verifyEqual( ...
                sort(results.participantValues.SubjectID), ...
                ["1001"; "1002"; "2001"; "2002"]);
            numFrequencies = numel(groupResults.NC.miso.f);
            numPositiveFrequencies = sum( ...
                groupResults.NC.miso.f > 0);
            testCase.verifyEqual( ...
                height(results.frequencyGroupComparisons), ...
                2*(numFrequencies + numPositiveFrequencies));
            testCase.verifyEqual( ...
                height(results.frequencyModelComparisons), ...
                4*(numFrequencies + numPositiveFrequencies));
            testCase.verifyEqual( ...
                sort(unique(results.frequencyGroupComparisons.Metric)), ...
                ["Gain"; "Phase"]);
            testCase.verifySize( ...
                results.frequencyGroupComparisons.BHAdjustedP, ...
                [2*(numFrequencies + numPositiveFrequencies) 1]);
        end

        function workbookAddsStatisticalSheets(testCase)
            outputFolder = tempname();
            mkdir(outputFolder);
            testCase.addTeardown(@() rmdir(outputFolder, "s"));
            baseSubject = runSelectedWorkflow( ...
                outputFolder, true, true);
            ncSubject = baseSubject;
            ncSubject.subjectInfo.group = "NC";
            ncSubject.subjectInfo.subjectID = "1001";
            mciSubject = baseSubject;
            mciSubject.subjectInfo.group = "MCI";
            mciSubject.subjectInfo.subjectID = "2001";
            allSubjects = {ncSubject; mciSubject};

            [analysisSettings, outputSettings] = ...
                createWorkflowTestSettings(outputFolder, true, true);
            analysisSettings.statistics.enabled = true;
            analysisSettings.statistics.frequencyWise.enabled = true;
            analysisSettings.statistics.frequencyWise.groupComparison.coherence = false;
            analysisSettings.statistics.frequencyWise.groupComparison.phase = false;
            analysisSettings.statistics.frequencyWise.modelComparison.phase = false;
            outputSettings.excelStatistics = true;
            outputSettings.excelMetrics.miso.mapGain = true;
            groupResults = createGroupResults( ...
                allSubjects, ["NC"; "MCI"], true, true, ...
                analysisSettings.phase);
            statisticalResults = calculateStatisticalResults( ...
                allSubjects, groupResults, analysisSettings);
            filename = fullfile(outputFolder, "statistics.xlsx");

            saveResultsToExcel( ...
                filename, allSubjects, ["NC"; "MCI"], ...
                analysisSettings, outputSettings, statisticalResults);
            workbookSheets = sheetnames(filename);

            testCase.verifyTrue(any( ...
                workbookSheets == "Participant_Characteristics"));
            testCase.verifyTrue(any( ...
                workbookSheets == "Model_Comparisons"));
            testCase.verifyTrue(any( ...
                workbookSheets == "Group_Comparisons"));
            testCase.verifyTrue(any( ...
                workbookSheets == "Input_Associations"));
            testCase.verifyTrue(any( ...
                workbookSheets == "Frequency_Group_Tests"));
            testCase.verifyTrue(any( ...
                workbookSheets == "Frequency_Model_Tests"));
        end

        function frequencyWiseFiguresAreSaved(testCase)
            outputFolder = tempname();
            mkdir(outputFolder);
            testCase.addTeardown(@() rmdir(outputFolder, "s"));
            baseSubject = runSelectedWorkflow( ...
                outputFolder, true, true);

            firstNcSubject = baseSubject;
            firstNcSubject.subjectInfo.group = "NC";
            firstNcSubject.subjectInfo.subjectID = "1001";
            secondNcSubject = firstNcSubject;
            secondNcSubject.subjectInfo.subjectID = "1002";
            secondNcSubject.misoResults.map.gain = ...
                1.1*secondNcSubject.misoResults.map.gain;

            firstMciSubject = baseSubject;
            firstMciSubject.subjectInfo.group = "MCI";
            firstMciSubject.subjectInfo.subjectID = "2001";
            firstMciSubject.misoResults.map.gain = ...
                1.2*firstMciSubject.misoResults.map.gain;
            secondMciSubject = firstMciSubject;
            secondMciSubject.subjectInfo.subjectID = "2002";
            secondMciSubject.misoResults.map.gain = ...
                1.1*secondMciSubject.misoResults.map.gain;

            allSubjects = { ...
                firstNcSubject; secondNcSubject; ...
                firstMciSubject; secondMciSubject};
            [analysisSettings, ~] = createWorkflowTestSettings( ...
                outputFolder, true, true);
            analysisSettings.statistics.enabled = true;
            analysisSettings.statistics.frequencyWise.enabled = true;
            analysisSettings.statistics.frequencyWise.groupComparison.coherence = false;
            analysisSettings.statistics.frequencyWise.groupComparison.phase = false;
            analysisSettings.statistics.frequencyWise.modelComparison.phase = false;
            analysisSettings.plot.show.statistics.frequencyWiseComparison = true;

            groupResults = createGroupResults( ...
                allSubjects, ["NC"; "MCI"], true, true, ...
                analysisSettings.phase);
            statisticalResults = calculateStatisticalResults( ...
                allSubjects, groupResults, analysisSettings);
            savedFiles = saveStatisticalFigures( ...
                statisticalResults, outputFolder, analysisSettings);

            testCase.verifyEqual(numel(savedFiles), 3);
            testCase.verifyTrue(all(isfile(savedFiles)));
        end
    end
end
