function plotHandle = plotMeanAndSd( ...
    ax, f, meanValues, sdValues, colorValue, plotStyle, plotSettings)
% plotMeanAndSd Plot a group mean with its standard-deviation region.

    f = f(:);
    meanValues = meanValues(:);
    sdValues = sdValues(:);
    sdValues(~isfinite(sdValues)) = 0;

    validValues = isfinite(f) & isfinite(meanValues);
    bandFrequency = f(validValues);
    bandLower = meanValues(validValues) - sdValues(validValues);
    bandUpper = meanValues(validValues) + sdValues(validValues);

    hold(ax, 'on')

    if ~isempty(bandFrequency)
        fill(ax, ...
            [bandFrequency; flipud(bandFrequency)], ...
            [bandLower; flipud(bandUpper)], ...
            colorValue, ...
            'FaceAlpha', 0.15, ...
            'EdgeColor', 'none', ...
            'HandleVisibility', 'off');
    end

    if plotStyle == "stem"
        plotHandle = stem(ax, f, meanValues, 'filled', ...
            'Color', colorValue, ...
            'MarkerSize', plotSettings.markerSize, ...
            'LineWidth', plotSettings.lineWidth.transferFunction);
    else
        plotHandle = plot(ax, f, meanValues, ...
            'Color', colorValue, ...
            'LineWidth', plotSettings.lineWidth.coherence);
    end

end
