function statisticalResults = calculateStatisticalResults( ...
    subjectResults, groupResults, analysisSettings)
% calculateStatisticalResults Run the batch statistical analysis.
%
% Every test uses one band value per subject. Frequency bins are not
% treated as independent observations.

    statisticsSettings = analysisSettings.statistics;
    groupNames = upper(string(statisticsSettings.groupsToCompare(:)));
    bandNames = string(analysisSettings.frequencyBandNames(:));
    primaryBandNames = string( ...
        statisticsSettings.primaryBandNames(:));

    % Keep direct calls backward compatible with settings created before
    % the one-group and multiplicity-family options were added.
    if ~isfield(statisticsSettings, "withinGroupModelComparison")
        statisticsSettings.withinGroupModelComparison.enabled = true;
    end
    if ~isfield(statisticsSettings, "betweenGroupComparison")
        statisticsSettings.betweenGroupComparison.enabled = ...
            numel(groupNames) == 2;
    end
    if ~isfield(statisticsSettings, "primaryGroups")
        statisticsSettings.primaryGroups = groupNames;
    end
    if ~isfield(statisticsSettings, "primaryPathways")
        statisticsSettings.primaryPathways = ["MAP"; "CO2"];
    end
    if ~isfield(statisticsSettings, "secondaryPathways")
        statisticsSettings.secondaryPathways = strings(0, 1);
    end

    previousRandomState = rng;
    restoreRandomState = onCleanup(@() rng(previousRandomState));
    rng(statisticsSettings.randomSeed, "twister");

    bandData = createStatisticalBandData( ...
        groupResults, groupNames, analysisSettings);

    modelComparisons = table();
    modelComparisonValues = table();
    groupComparisons = table();
    groupComparisonValues = table();
    inputAssociations = table();
    inputAssociationValues = table();

    %% Compare SISO and MISO Within Each Subject

    pathways = ["MAP"; "CO2"];
    modelMetrics = ["Gain"; "Coherence"; "Phase"];

    for groupIndex = 1:numel(groupNames)
        if ~statisticsSettings.withinGroupModelComparison.enabled
            continue
        end

        groupName = groupNames(groupIndex);
        groupField = char(groupName);

        if ~isfield(bandData, groupField) || ...
                ~isfield(bandData.(groupField), "miso") || ...
                ~isfield(bandData.(groupField), "siso")
            continue
        end

        miso = bandData.(groupField).miso;
        siso = bandData.(groupField).siso;
        [commonSubjectIds, misoIndices, sisoIndices] = intersect( ...
            miso.subjectIds, siso.subjectIds, "stable");

        for pathwayIndex = 1:numel(pathways)
            pathway = pathways(pathwayIndex);

            if pathway == "MAP"
                misoGain = miso.map.gain(:,misoIndices);
                sisoGain = siso.map.gain(:,sisoIndices);
                misoCoherence = miso.map.coherence(:,misoIndices);
                sisoCoherence = siso.map.coherence(:,sisoIndices);
                misoPhase = miso.map.phase(:,misoIndices);
                sisoPhase = siso.map.phase(:,sisoIndices);
            else
                misoGain = miso.co2.gain(:,misoIndices);
                sisoGain = siso.co2.gain(:,sisoIndices);
                misoCoherence = miso.co2.coherence(:,misoIndices);
                sisoCoherence = siso.co2.coherence(:,sisoIndices);
                misoPhase = miso.co2.phase(:,misoIndices);
                sisoPhase = siso.co2.phase(:,sisoIndices);
            end

            inputCoherence = miso.inputCoherence(:,misoIndices);

            for bandIndex = 1:numel(bandNames)
                bandName = bandNames(bandIndex);

                for metricIndex = 1:numel(modelMetrics)
                    metric = modelMetrics(metricIndex);

                    if metric == "Gain"
                        firstValues = misoGain(bandIndex,:)';
                        secondValues = sisoGain(bandIndex,:)';
                        comparison = comparePairedArithmeticValues( ...
                            firstValues, secondValues, ...
                            statisticsSettings.alpha);
                        testName = "Paired t-test";
                        notes = "MISO minus SISO gain";
                    elseif metric == "Coherence"
                        firstValues = misoCoherence(bandIndex,:)';
                        secondValues = sisoCoherence(bandIndex,:)';
                        comparison = comparePairedArithmeticValues( ...
                            firstValues, secondValues, ...
                            statisticsSettings.alpha);
                        testName = "Paired t-test";
                        notes = "Partial minus ordinary coherence; " + ...
                            "not a model-performance test";
                    else
                        firstValues = misoPhase(bandIndex,:)';
                        secondValues = sisoPhase(bandIndex,:)';
                        circularComparison = compareCircularValues( ...
                            firstValues, secondValues, "paired", ...
                            statisticsSettings.numPhasePermutations);
                        comparison.n = circularComparison.nFirst;
                        comparison.meanFirst = ...
                            circularComparison.meanFirst;
                        comparison.meanSecond = ...
                            circularComparison.meanSecond;
                        comparison.difference = ...
                            circularComparison.difference;
                        comparison.ciLower = NaN;
                        comparison.ciUpper = NaN;
                        comparison.effectSize = NaN;
                        comparison.medianRatio = NaN;
                        comparison.ratioQ1 = NaN;
                        comparison.ratioQ3 = NaN;
                        comparison.pValue = ...
                            circularComparison.pValue;
                        testName = "Paired circular permutation";
                        notes = "Circular MISO minus SISO phase";
                    end

                    [multiplicityFamily, isPrimary] = ...
                        getModelComparisonFamily( ...
                            groupName, pathway, metric, bandName, ...
                            statisticsSettings);

                    newSummaryRow = table( ...
                        groupName, pathway, metric, bandName, ...
                        comparison.n, comparison.meanFirst, ...
                        comparison.meanSecond, comparison.difference, ...
                        comparison.ciLower, comparison.ciUpper, ...
                        comparison.effectSize, comparison.medianRatio, ...
                        comparison.ratioQ1, comparison.ratioQ3, ...
                        testName, multiplicityFamily, ...
                        comparison.pValue, NaN, isPrimary, notes, ...
                        'VariableNames', { ...
                            'Group', 'Pathway', 'Metric', 'Band', 'N', ...
                            'MISOEstimate', 'SISOEstimate', ...
                            'MISOminusSISO', 'CILower', 'CIUpper', ...
                            'EffectSize', 'MedianRatio', 'RatioQ1', ...
                            'RatioQ3', 'Test', 'MultiplicityFamily', ...
                            'RawP', 'BHAdjustedP', 'IsPrimary', 'Notes'});
                    modelComparisons = [modelComparisons; newSummaryRow];

                    if metric == "Phase"
                        differences = angle(exp( ...
                            1i*(firstValues - secondValues)));
                    else
                        differences = firstValues - secondValues;
                    end

                    numValues = numel(commonSubjectIds);
                    newValueRows = table( ...
                        commonSubjectIds, ...
                        repmat(groupName, numValues, 1), ...
                        repmat(pathway, numValues, 1), ...
                        repmat(metric, numValues, 1), ...
                        repmat(bandName, numValues, 1), ...
                        firstValues, secondValues, differences, ...
                        'VariableNames', { ...
                            'SubjectID', 'Group', 'Pathway', 'Metric', ...
                            'Band', 'MISOValue', 'SISOValue', ...
                            'MISOminusSISO'});
                    modelComparisonValues = [ ...
                        modelComparisonValues; newValueRows];
                end

                absoluteGainChange = abs( ...
                    misoGain(bandIndex,:)' - sisoGain(bandIndex,:)');
                numValues = numel(commonSubjectIds);
                newAssociationRows = table( ...
                    commonSubjectIds, ...
                    repmat(groupName, numValues, 1), ...
                    repmat(pathway, numValues, 1), ...
                    repmat(bandName, numValues, 1), ...
                    inputCoherence(bandIndex,:)', absoluteGainChange, ...
                    'VariableNames', { ...
                        'SubjectID', 'Group', 'Pathway', 'Band', ...
                        'InputCoherence', 'AbsoluteGainChange'});
                inputAssociationValues = [ ...
                    inputAssociationValues; newAssociationRows];
            end
        end
    end

    %% Compare NC and MCI Subject Values

    bothGroupsAvailable = false;
    if statisticsSettings.betweenGroupComparison.enabled && ...
            numel(groupNames) == 2
        firstGroupName = groupNames(1);
        secondGroupName = groupNames(2);
        firstGroupField = char(firstGroupName);
        secondGroupField = char(secondGroupName);
        bothGroupsAvailable = isfield(bandData, firstGroupField) && ...
            isfield(bandData, secondGroupField);
    end

    if bothGroupsAvailable
        models = ["MISO"; "SISO"];

        for modelIndex = 1:numel(models)
            modelName = models(modelIndex);
            modelField = lower(char(modelName));

            if ~isfield(bandData.(firstGroupField), modelField) || ...
                    ~isfield(bandData.(secondGroupField), modelField)
                continue
            end

            firstModel = bandData.(firstGroupField).(modelField);
            secondModel = bandData.(secondGroupField).(modelField);

            for pathwayIndex = 1:numel(pathways)
                pathway = pathways(pathwayIndex);

                if pathway == "MAP"
                    firstGain = firstModel.map.gain;
                    secondGain = secondModel.map.gain;
                    firstCoherence = firstModel.map.coherence;
                    secondCoherence = secondModel.map.coherence;
                    firstPhase = firstModel.map.phase;
                    secondPhase = secondModel.map.phase;
                else
                    firstGain = firstModel.co2.gain;
                    secondGain = secondModel.co2.gain;
                    firstCoherence = firstModel.co2.coherence;
                    secondCoherence = secondModel.co2.coherence;
                    firstPhase = firstModel.co2.phase;
                    secondPhase = secondModel.co2.phase;
                end

                for bandIndex = 1:numel(bandNames)
                    bandName = bandNames(bandIndex);

                    for metricIndex = 1:numel(modelMetrics)
                        metric = modelMetrics(metricIndex);

                        if metric == "Gain"
                            firstValues = firstGain(bandIndex,:)';
                            secondValues = secondGain(bandIndex,:)';
                            comparison = ...
                                compareIndependentArithmeticValues( ...
                                    firstValues, secondValues, ...
                                    statisticsSettings.alpha);
                            testName = "Welch two-sample t-test";
                        elseif metric == "Coherence"
                            firstValues = firstCoherence(bandIndex,:)';
                            secondValues = secondCoherence(bandIndex,:)';
                            comparison = ...
                                compareIndependentArithmeticValues( ...
                                    firstValues, secondValues, ...
                                    statisticsSettings.alpha);
                            testName = "Welch two-sample t-test";
                        else
                            firstValues = firstPhase(bandIndex,:)';
                            secondValues = secondPhase(bandIndex,:)';
                            circularComparison = compareCircularValues( ...
                                firstValues, secondValues, "independent", ...
                                statisticsSettings.numPhasePermutations);
                            comparison.nFirst = ...
                                circularComparison.nFirst;
                            comparison.nSecond = ...
                                circularComparison.nSecond;
                            comparison.meanFirst = ...
                                circularComparison.meanFirst;
                            comparison.meanSecond = ...
                                circularComparison.meanSecond;
                            comparison.difference = ...
                                circularComparison.difference;
                            comparison.ciLower = NaN;
                            comparison.ciUpper = NaN;
                            comparison.effectSize = NaN;
                            comparison.pValue = ...
                                circularComparison.pValue;
                            testName = "Independent circular permutation";
                        end

                        isPrimary = modelName == "MISO" && ...
                            metric ~= "Phase" && ...
                            ismember(bandName, primaryBandNames);

                        if modelName == "MISO" && metric == "Coherence"
                            notes = "MISO partial coherence";
                        elseif modelName == "SISO" && ...
                                metric == "Coherence"
                            notes = "SISO ordinary coherence";
                        else
                            notes = "";
                        end

                        if isPrimary
                            familyPurpose = "PRIMARY";
                        else
                            familyPurpose = "EXPLORATORY";
                        end
                        multiplicityFamily = ...
                            "BETWEEN_" + modelName + "_" + pathway + ...
                            "_" + metric + "_" + familyPurpose;

                        newSummaryRow = table( ...
                            modelName, pathway, metric, bandName, ...
                            firstGroupName, secondGroupName, ...
                            comparison.nFirst, comparison.nSecond, ...
                            comparison.meanFirst, ...
                            comparison.meanSecond, ...
                            comparison.difference, ...
                            comparison.ciLower, comparison.ciUpper, ...
                            comparison.effectSize, testName, ...
                            multiplicityFamily, comparison.pValue, NaN, ...
                            isPrimary, notes, ...
                            'VariableNames', { ...
                                'Model', 'Pathway', 'Metric', 'Band', ...
                                'FirstGroup', 'SecondGroup', ...
                                'NFirst', 'NSecond', 'FirstEstimate', ...
                                'SecondEstimate', 'FirstMinusSecond', ...
                                'CILower', 'CIUpper', 'HedgesG', ...
                                'Test', 'MultiplicityFamily', 'RawP', ...
                                'BHAdjustedP', ...
                                'IsPrimary', 'Notes'});
                        groupComparisons = [ ...
                            groupComparisons; newSummaryRow];

                        firstValueRows = table( ...
                            firstModel.subjectIds, ...
                            repmat(firstGroupName, ...
                                numel(firstModel.subjectIds), 1), ...
                            repmat(modelName, ...
                                numel(firstModel.subjectIds), 1), ...
                            repmat(pathway, ...
                                numel(firstModel.subjectIds), 1), ...
                            repmat(metric, ...
                                numel(firstModel.subjectIds), 1), ...
                            repmat(bandName, ...
                                numel(firstModel.subjectIds), 1), ...
                            firstValues, ...
                            'VariableNames', { ...
                                'SubjectID', 'Group', 'Model', 'Pathway', ...
                                'Metric', 'Band', 'Value'});
                        secondValueRows = table( ...
                            secondModel.subjectIds, ...
                            repmat(secondGroupName, ...
                                numel(secondModel.subjectIds), 1), ...
                            repmat(modelName, ...
                                numel(secondModel.subjectIds), 1), ...
                            repmat(pathway, ...
                                numel(secondModel.subjectIds), 1), ...
                            repmat(metric, ...
                                numel(secondModel.subjectIds), 1), ...
                            repmat(bandName, ...
                                numel(secondModel.subjectIds), 1), ...
                            secondValues, ...
                            'VariableNames', { ...
                                'SubjectID', 'Group', 'Model', 'Pathway', ...
                                'Metric', 'Band', 'Value'});
                        groupComparisonValues = [ ...
                            groupComparisonValues; ...
                            firstValueRows; secondValueRows];
                    end
                end
            end
        end

        %% Compare the MISO MAP-versus-CO2 Partial-Coherence Balance

        if isfield(bandData.(firstGroupField), "miso") && ...
                isfield(bandData.(secondGroupField), "miso")
            firstMiso = bandData.(firstGroupField).miso;
            secondMiso = bandData.(secondGroupField).miso;

            for bandIndex = 1:numel(bandNames)
                bandName = bandNames(bandIndex);
                firstBalance = firstMiso.map.coherence(bandIndex,:)' - ...
                    firstMiso.co2.coherence(bandIndex,:)';
                secondBalance = secondMiso.map.coherence(bandIndex,:)' - ...
                    secondMiso.co2.coherence(bandIndex,:)';
                comparison = compareIndependentArithmeticValues( ...
                    firstBalance, secondBalance, ...
                    statisticsSettings.alpha);

                multiplicityFamily = ...
                    "BETWEEN_MISO_PATHWAY_BALANCE_EXPLORATORY";
                newSummaryRow = table( ...
                    "MISO", "MAP minus CO2", "Pathway balance", ...
                    bandName, firstGroupName, secondGroupName, ...
                    comparison.nFirst, comparison.nSecond, ...
                    comparison.meanFirst, comparison.meanSecond, ...
                    comparison.difference, comparison.ciLower, ...
                    comparison.ciUpper, comparison.effectSize, ...
                    "Welch two-sample t-test", multiplicityFamily, ...
                    comparison.pValue, NaN, false, ...
                    "MAP partial coherence minus CO2 partial coherence", ...
                    'VariableNames', { ...
                        'Model', 'Pathway', 'Metric', 'Band', ...
                        'FirstGroup', 'SecondGroup', 'NFirst', ...
                        'NSecond', 'FirstEstimate', 'SecondEstimate', ...
                        'FirstMinusSecond', 'CILower', 'CIUpper', ...
                        'HedgesG', 'Test', 'MultiplicityFamily', ...
                        'RawP', 'BHAdjustedP', ...
                        'IsPrimary', 'Notes'});
                groupComparisons = [groupComparisons; newSummaryRow];
            end
        end
    end

    %% Relate Input Coherence to the Absolute SISO-to-MISO Gain Change

    if ~isempty(inputAssociationValues)
        associationGroups = [groupNames; "All"];

        for groupIndex = 1:numel(associationGroups)
            groupName = associationGroups(groupIndex);

            for pathwayIndex = 1:numel(pathways)
                pathway = pathways(pathwayIndex);

                for bandIndex = 1:numel(bandNames)
                    bandName = bandNames(bandIndex);
                    rowMask = ...
                        inputAssociationValues.Pathway == pathway & ...
                        inputAssociationValues.Band == bandName;

                    if groupName ~= "All"
                        rowMask = rowMask & ...
                            inputAssociationValues.Group == groupName;
                    end

                    xValues = inputAssociationValues.InputCoherence(rowMask);
                    yValues = ...
                        inputAssociationValues.AbsoluteGainChange(rowMask);
                    completeMask = isfinite(xValues) & isfinite(yValues);
                    xValues = xValues(completeMask);
                    yValues = yValues(completeMask);

                    rho = NaN;
                    pValue = NaN;
                    if numel(xValues) >= 3
                        [rho, pValue] = corr( ...
                            xValues, yValues, "Type", "Spearman");
                    end

                    multiplicityFamily = upper(groupName) + "_" + ...
                        pathway + "_INPUT_ASSOCIATION_EXPLORATORY";
                    newAssociationRow = table( ...
                        groupName, pathway, bandName, numel(xValues), ...
                        rho, "Spearman correlation", ...
                        multiplicityFamily, pValue, NaN, ...
                        false, ...
                        "Input coherence vs absolute gain change", ...
                        'VariableNames', { ...
                            'Group', 'Pathway', 'Band', 'N', 'Rho', ...
                            'Test', 'MultiplicityFamily', 'RawP', ...
                            'BHAdjustedP', ...
                            'IsPrimary', 'Notes'});
                    inputAssociations = [ ...
                        inputAssociations; newAssociationRow];
                end
            end
        end
    end

    %% Apply BH Adjustment Within Prespecified Analysis Families

    if ~isempty(modelComparisons)
        modelComparisons = adjustPValuesByFamily( ...
            modelComparisons, statisticsSettings.alpha);
    end

    if ~isempty(groupComparisons)
        groupComparisons = adjustPValuesByFamily( ...
            groupComparisons, statisticsSettings.alpha);
    end

    if ~isempty(inputAssociations)
        inputAssociations = adjustPValuesByFamily( ...
            inputAssociations, statisticsSettings.alpha);
    end

    %% Exploratory Frequency-Wise Comparisons

    frequencyGroupComparisons = table();
    frequencyModelComparisons = table();

    if statisticsSettings.frequencyWise.enabled
        frequencyResults = calculateFrequencyWiseStatistics( ...
            groupResults, analysisSettings);
        frequencyGroupComparisons = ...
            frequencyResults.groupComparisons;
        frequencyModelComparisons = ...
            frequencyResults.modelComparisons;
    end

    %% Participant Characteristics and Final Result

    participantResults = summarizeParticipantCharacteristics( ...
        subjectResults, statisticsSettings);

    statisticalResults.participantCharacteristics = ...
        participantResults.summary;
    statisticalResults.participantValues = ...
        participantResults.subjectValues;
    statisticalResults.modelComparisons = modelComparisons;
    statisticalResults.groupComparisons = groupComparisons;
    statisticalResults.inputAssociations = inputAssociations;
    statisticalResults.modelComparisonValues = modelComparisonValues;
    statisticalResults.groupComparisonValues = groupComparisonValues;
    statisticalResults.inputAssociationValues = inputAssociationValues;
    statisticalResults.frequencyGroupComparisons = ...
        frequencyGroupComparisons;
    statisticalResults.frequencyModelComparisons = ...
        frequencyModelComparisons;
    statisticalResults.bandData = bandData;
    statisticalResults.randomSeed = statisticsSettings.randomSeed;

    clear restoreRandomState

end
