function bandData = createStatisticalBandData( ...
    groupResults, groupNames, analysisSettings)
% createStatisticalBandData Collect subject-level values for each band.

    bandData = struct();
    groupNames = upper(string(groupNames(:)));

    for groupIndex = 1:numel(groupNames)
        groupName = groupNames(groupIndex);
        groupField = char(groupName);

        if ~isfield(groupResults, groupField)
            continue
        end

        currentGroup = groupResults.(groupField);

        %% MISO Band Values

        if isfield(currentGroup, "miso")
            results = currentGroup.miso;
            statistics = "arithmetic";

            bandData.(groupField).miso.subjectIds = results.subjectIds;
            bandData.(groupField).miso.f = results.f;

            bandData.(groupField).miso.map.gain = ...
                calculateSubjectBandValues( ...
                    results.f, results.map.gain.values, ...
                    analysisSettings, statistics).values;
            bandData.(groupField).miso.co2.gain = ...
                calculateSubjectBandValues( ...
                    results.f, results.co2.gain.values, ...
                    analysisSettings, statistics).values;

            bandData.(groupField).miso.map.coherence = ...
                calculateSubjectBandValues( ...
                    results.f, ...
                    results.map.coherence.partial.values, ...
                    analysisSettings, statistics).values;
            bandData.(groupField).miso.co2.coherence = ...
                calculateSubjectBandValues( ...
                    results.f, ...
                    results.co2.coherence.partial.values, ...
                    analysisSettings, statistics).values;

            bandData.(groupField).miso.map.phase = ...
                calculateSubjectBandValues( ...
                    results.f, results.map.phase.unwrapped.values, ...
                    analysisSettings, "phaseWrapped", ...
                    results.map.phase.wrapped.values, ...
                    results.map.coherence.partial.values).wrappedValues;
            bandData.(groupField).miso.co2.phase = ...
                calculateSubjectBandValues( ...
                    results.f, results.co2.phase.unwrapped.values, ...
                    analysisSettings, "phaseWrapped", ...
                    results.co2.phase.wrapped.values, ...
                    results.co2.coherence.partial.values).wrappedValues;

            bandData.(groupField).miso.multipleCoherence = ...
                calculateSubjectBandValues( ...
                    results.f, ...
                    results.system.multipleCoherence.values, ...
                    analysisSettings, statistics).values;
            bandData.(groupField).miso.inputCoherence = ...
                calculateSubjectBandValues( ...
                    results.f, ...
                    results.inputRelationship.coherence.values, ...
                    analysisSettings, statistics).values;
        end

        %% SISO Band Values

        if isfield(currentGroup, "siso")
            results = currentGroup.siso;
            statistics = "arithmetic";

            bandData.(groupField).siso.subjectIds = results.subjectIds;
            bandData.(groupField).siso.f = results.f;

            bandData.(groupField).siso.map.gain = ...
                calculateSubjectBandValues( ...
                    results.f, results.map.gain.values, ...
                    analysisSettings, statistics).values;
            bandData.(groupField).siso.co2.gain = ...
                calculateSubjectBandValues( ...
                    results.f, results.co2.gain.values, ...
                    analysisSettings, statistics).values;

            bandData.(groupField).siso.map.coherence = ...
                calculateSubjectBandValues( ...
                    results.f, ...
                    results.map.coherence.pairwise.values, ...
                    analysisSettings, statistics).values;
            bandData.(groupField).siso.co2.coherence = ...
                calculateSubjectBandValues( ...
                    results.f, ...
                    results.co2.coherence.pairwise.values, ...
                    analysisSettings, statistics).values;

            bandData.(groupField).siso.map.phase = ...
                calculateSubjectBandValues( ...
                    results.f, results.map.phase.unwrapped.values, ...
                    analysisSettings, "phaseWrapped", ...
                    results.map.phase.wrapped.values, ...
                    results.map.coherence.pairwise.values).wrappedValues;
            bandData.(groupField).siso.co2.phase = ...
                calculateSubjectBandValues( ...
                    results.f, results.co2.phase.unwrapped.values, ...
                    analysisSettings, "phaseWrapped", ...
                    results.co2.phase.wrapped.values, ...
                    results.co2.coherence.pairwise.values).wrappedValues;

            bandData.(groupField).siso.inputCoherence = ...
                calculateSubjectBandValues( ...
                    results.f, ...
                    results.inputRelationship.coherence.values, ...
                    analysisSettings, statistics).values;
        end
    end

end
