function [familyName, isPrimary] = getModelComparisonFamily( ...
    groupName, pathway, metric, bandName, statisticsSettings)
% getModelComparisonFamily Name one within-group test family.

    selectedBand = ismember( ...
        string(bandName), string(statisticsSettings.primaryBandNames));
    selectedGroup = ismember( ...
        upper(string(groupName)), ...
        upper(string(statisticsSettings.primaryGroups)));
    selectedPrimaryPathway = ismember( ...
        upper(string(pathway)), ...
        upper(string(statisticsSettings.primaryPathways)));
    selectedSecondaryPathway = ismember( ...
        upper(string(pathway)), ...
        upper(string(statisticsSettings.secondaryPathways)));

    isPrimary = string(metric) == "Gain" && selectedBand && ...
        selectedGroup && selectedPrimaryPathway;

    if isPrimary
        familyPurpose = "PRIMARY";
    elseif string(metric) == "Gain" && selectedBand && ...
            selectedSecondaryPathway
        familyPurpose = "SECONDARY";
    else
        familyPurpose = "EXPLORATORY";
    end

    familyName = upper(string(groupName)) + "_" + ...
        upper(string(pathway)) + "_" + upper(string(metric)) + "_" + ...
        familyPurpose;

end
