function analysis = analyzeKnownTruthObservation( ...
    training, validation, settings, runRidge)
% analyzeKnownTruthObservation Fit SISO and MISO to one paired observation.

    trainingSpectra = estimateWelchSpectra( ...
        training.map, training.co2, training.cbv, training.fs, ...
        settings.welch);
    validationSpectra = estimateWelchSpectra( ...
        validation.map, validation.co2, validation.cbv, validation.fs, ...
        settings.welch);

    frequencyHz = trainingSpectra.f;
    frequencyMask = ...
        frequencyHz >= settings.frequencyRangeHz(1) & ...
        frequencyHz <= settings.frequencyRangeHz(2);

    trueMap = freqz( ...
        training.truth.mapImpulseResponse, 1, ...
        frequencyHz, training.fs);
    trueCo2 = freqz( ...
        training.truth.co2ImpulseResponse, 1, ...
        frequencyHz, training.fs);

    siso = runSISOTFA(trainingSpectra, settings.phase);
    miso = runMISOTFA(trainingSpectra, settings.phase);

    analysis.frequencyHz = frequencyHz(frequencyMask);
    analysis.truth.map = trueMap(frequencyMask);
    analysis.truth.co2 = trueCo2(frequencyMask);
    analysis.estimate.map.siso = ...
        siso.map.transferFunction(frequencyMask);
    analysis.estimate.map.miso = ...
        miso.map.transferFunction(frequencyMask);
    analysis.estimate.co2.siso = ...
        siso.co2.transferFunction(frequencyMask);
    analysis.estimate.co2.miso = ...
        miso.co2.transferFunction(frequencyMask);

    errorFloor = settings.metrics.errorFloor;
    phaseMinimumGainFraction = ...
        settings.metrics.phaseMinimumTruthGainFraction;
    analysis.frequencyError.map.siso = ...
        calculateFrequencyTruthErrors( ...
            analysis.estimate.map.siso, analysis.truth.map, errorFloor, ...
            phaseMinimumGainFraction);
    analysis.frequencyError.map.miso = ...
        calculateFrequencyTruthErrors( ...
            analysis.estimate.map.miso, analysis.truth.map, errorFloor, ...
            phaseMinimumGainFraction);
    analysis.frequencyError.co2.siso = ...
        calculateFrequencyTruthErrors( ...
            analysis.estimate.co2.siso, analysis.truth.co2, errorFloor, ...
            phaseMinimumGainFraction);
    analysis.frequencyError.co2.miso = ...
        calculateFrequencyTruthErrors( ...
            analysis.estimate.co2.miso, analysis.truth.co2, errorFloor, ...
            phaseMinimumGainFraction);

    analysis.frequencyAdvantage.map = calculatePathwayAdvantages( ...
        analysis.frequencyError.map, errorFloor);
    analysis.frequencyAdvantage.co2 = calculatePathwayAdvantages( ...
        analysis.frequencyError.co2, errorFloor);

    analysis.summary.map.siso = calculateKnownTruthMetrics( ...
        frequencyHz, siso.map.transferFunction, trueMap, ...
        settings.frequencyRangeHz, ...
        settings.metrics.extremeCoefficientThreshold, ...
        phaseMinimumGainFraction);
    analysis.summary.map.miso = calculateKnownTruthMetrics( ...
        frequencyHz, miso.map.transferFunction, trueMap, ...
        settings.frequencyRangeHz, ...
        settings.metrics.extremeCoefficientThreshold, ...
        phaseMinimumGainFraction);
    analysis.summary.co2.siso = calculateKnownTruthMetrics( ...
        frequencyHz, siso.co2.transferFunction, trueCo2, ...
        settings.frequencyRangeHz, ...
        settings.metrics.extremeCoefficientThreshold, ...
        phaseMinimumGainFraction);
    analysis.summary.co2.miso = calculateKnownTruthMetrics( ...
        frequencyHz, miso.co2.transferFunction, trueCo2, ...
        settings.frequencyRangeHz, ...
        settings.metrics.extremeCoefficientThreshold, ...
        phaseMinimumGainFraction);

    analysis.summaryAdvantage.map = calculateSummaryAdvantages( ...
        analysis.summary.map.siso, analysis.summary.map.miso, ...
        errorFloor);
    analysis.summaryAdvantage.co2 = calculateSummaryAdvantages( ...
        analysis.summary.co2.siso, analysis.summary.co2.miso, ...
        errorFloor);

    analysis.prediction.sisoMap = ...
        calculateValidationPredictionError( ...
            validationSpectra, siso.map.transferFunction, ...
            zeros(size(siso.co2.transferFunction)), ...
            settings.frequencyRangeHz);
    analysis.prediction.sisoCo2 = ...
        calculateValidationPredictionError( ...
            validationSpectra, ...
            zeros(size(siso.map.transferFunction)), ...
            siso.co2.transferFunction, settings.frequencyRangeHz);
    analysis.prediction.miso = ...
        calculateValidationPredictionError( ...
            validationSpectra, ...
            miso.map.transferFunction, ...
            miso.co2.transferFunction, ...
            settings.frequencyRangeHz);
    analysis.prediction.advantage = calculateErrorAdvantage( ...
        analysis.prediction.sisoMap, ...
        analysis.prediction.miso, errorFloor);

    mapPower = real(trainingSpectra.map.power(frequencyMask));
    co2Power = real(trainingSpectra.co2.power(frequencyMask));
    inputCoherence = abs( ...
        trainingSpectra.cross.mapCo2(frequencyMask)).^2 ./ ...
        max(mapPower.*co2Power, errorFloor);
    inputCoherence = min(1, max(0, real(inputCoherence)));

    analysis.diagnostics.inputCoherence = inputCoherence;
    analysis.diagnostics.realizedPSDShapeOverlap = ...
        calculatePSDShapeOverlap(mapPower, co2Power);
    analysis.diagnostics.realizedPETCO2ToMAPFluctuationSDRatio = ...
        std(training.co2, "omitnan")/std(training.map, "omitnan");
    analysis.diagnostics.realizedPETCO2ContributionPowerShare = ...
        calculatePetco2ContributionPowerShare( ...
            training.mapContribution, training.co2Contribution);
    analysis.diagnostics.achievedPETCO2ToMAPBandGainRatio = ...
        training.truth.achievedPETCO2ToMAPBandGainRatio;
    analysis.diagnostics.rawConditionNumber = ...
        miso.diagnostics.conditionNumber(frequencyMask);
    analysis.diagnostics.normalizedConditionNumber = ...
        miso.diagnostics.normalizedConditionNumber(frequencyMask);
    analysis.diagnostics.normalizedDeterminant = ...
        miso.diagnostics.normalizedDeterminant(frequencyMask);
    analysis.diagnostics.numWelchWindows = ...
        trainingSpectra.welchInfo.numWindows;
    analysis.diagnostics.numAnalyzedSamples = numel(training.map);
    analysis.diagnostics.analyzedDurationSeconds = ...
        numel(training.map)/training.fs;

    analysis.ridge = table();
    analysis.ridgeFrequency = table();
    if runRidge
        [analysis.ridge, analysis.ridgeFrequency] = analyzeRidgePath( ...
            trainingSpectra, validationSpectra, ...
            frequencyHz, trueMap, trueCo2, ...
            siso, settings);
    end

end

function advantages = calculatePathwayAdvantages(errors, errorFloor)
% calculatePathwayAdvantages Compare frequency-wise SISO and MISO errors.

    advantages.gain = calculateErrorAdvantage( ...
        errors.siso.gain, errors.miso.gain, errorFloor);
    advantages.phase = calculateErrorAdvantage( ...
        errors.siso.phase, errors.miso.phase, errorFloor);
    advantages.complex = calculateErrorAdvantage( ...
        errors.siso.complex, errors.miso.complex, errorFloor);

end

function advantages = calculateSummaryAdvantages( ...
    siso, miso, errorFloor)
% calculateSummaryAdvantages Compare whole-range pathway errors.

    advantages.gain = calculateErrorAdvantage( ...
        siso.meanAbsoluteGainError, ...
        miso.meanAbsoluteGainError, errorFloor);
    advantages.phase = calculateErrorAdvantage( ...
        siso.meanAbsolutePhaseErrorRadians, ...
        miso.meanAbsolutePhaseErrorRadians, errorFloor);
    advantages.complex = calculateErrorAdvantage( ...
        siso.normalizedComplexError, ...
        miso.normalizedComplexError, errorFloor);

end

function [ridgeTable, frequencyTable] = analyzeRidgePath( ...
    trainingSpectra, validationSpectra, frequencyHz, ...
    trueMap, trueCo2, siso, settings)
% analyzeRidgePath Evaluate selected ridge values on the same observation.

    lambdas = settings.estimators.ridgeLambdas(:);
    numLambdas = numel(lambdas);
    rows = repmat(emptyRidgeRow(), numLambdas, 1);
    frequencyParts = cell(numLambdas, 1);
    errorFloor = settings.metrics.errorFloor;
    frequencyMask = frequencyHz >= settings.frequencyRangeHz(1) & ...
        frequencyHz <= settings.frequencyRangeHz(2);
    retainedFrequencyHz = frequencyHz(frequencyMask);
    retainedTrueMap = trueMap(frequencyMask);
    retainedTrueCo2 = trueCo2(frequencyMask);

    sisoMapMetrics = calculateKnownTruthMetrics( ...
        frequencyHz, siso.map.transferFunction, trueMap, ...
        settings.frequencyRangeHz, ...
        settings.metrics.extremeCoefficientThreshold, ...
        settings.metrics.phaseMinimumTruthGainFraction);
    sisoCo2Metrics = calculateKnownTruthMetrics( ...
        frequencyHz, siso.co2.transferFunction, trueCo2, ...
        settings.frequencyRangeHz, ...
        settings.metrics.extremeCoefficientThreshold, ...
        settings.metrics.phaseMinimumTruthGainFraction);

    for lambdaIndex = 1:numLambdas
        solverSettings = defaultMisoSolverSettings();
        solverSettings.regularization.enabled = true;
        solverSettings.regularization.lambda = lambdas(lambdaIndex);
        ridge = runMISOTFA( ...
            trainingSpectra, settings.phase, solverSettings);

        mapMetrics = calculateKnownTruthMetrics( ...
            frequencyHz, ridge.map.transferFunction, trueMap, ...
            settings.frequencyRangeHz, ...
            settings.metrics.extremeCoefficientThreshold, ...
            settings.metrics.phaseMinimumTruthGainFraction);
        co2Metrics = calculateKnownTruthMetrics( ...
            frequencyHz, ridge.co2.transferFunction, trueCo2, ...
            settings.frequencyRangeHz, ...
            settings.metrics.extremeCoefficientThreshold, ...
            settings.metrics.phaseMinimumTruthGainFraction);
        predictionError = calculateValidationPredictionError( ...
            validationSpectra, ridge.map.transferFunction, ...
            ridge.co2.transferFunction, settings.frequencyRangeHz);

        rows(lambdaIndex).Lambda = lambdas(lambdaIndex);
        rows(lambdaIndex).MAPComplexError = ...
            mapMetrics.normalizedComplexError;
        rows(lambdaIndex).CO2ComplexError = ...
            co2Metrics.normalizedComplexError;
        rows(lambdaIndex).MAPComplexAdvantage = ...
            calculateErrorAdvantage( ...
                sisoMapMetrics.normalizedComplexError, ...
                mapMetrics.normalizedComplexError, errorFloor);
        rows(lambdaIndex).CO2ComplexAdvantage = ...
            calculateErrorAdvantage( ...
                sisoCo2Metrics.normalizedComplexError, ...
                co2Metrics.normalizedComplexError, errorFloor);
        rows(lambdaIndex).PredictionError = predictionError;
        regularizedConditionNumber = ...
            calculateRegularizedConditionNumber( ...
                trainingSpectra, lambdas(lambdaIndex));
        rows(lambdaIndex).MedianRegularizedConditionNumber = median( ...
            regularizedConditionNumber(frequencyMask), "omitnan");
        rows(lambdaIndex).MAPMISOHasLowerComplexError = ...
            rows(lambdaIndex).MAPComplexAdvantage > 0;
        rows(lambdaIndex).CO2MISOHasLowerComplexError = ...
            rows(lambdaIndex).CO2ComplexAdvantage > 0;

        mapSisoError = calculateFrequencyTruthErrors( ...
            siso.map.transferFunction(frequencyMask), ...
            retainedTrueMap, errorFloor, ...
            settings.metrics.phaseMinimumTruthGainFraction);
        mapMisoError = calculateFrequencyTruthErrors( ...
            ridge.map.transferFunction(frequencyMask), ...
            retainedTrueMap, errorFloor, ...
            settings.metrics.phaseMinimumTruthGainFraction);
        co2SisoError = calculateFrequencyTruthErrors( ...
            siso.co2.transferFunction(frequencyMask), ...
            retainedTrueCo2, errorFloor, ...
            settings.metrics.phaseMinimumTruthGainFraction);
        co2MisoError = calculateFrequencyTruthErrors( ...
            ridge.co2.transferFunction(frequencyMask), ...
            retainedTrueCo2, errorFloor, ...
            settings.metrics.phaseMinimumTruthGainFraction);
        frequencyParts{lambdaIndex} = createRidgeFrequencyTable( ...
            lambdas(lambdaIndex), retainedFrequencyHz, ...
            mapSisoError, mapMisoError, ...
            co2SisoError, co2MisoError, ...
            regularizedConditionNumber(frequencyMask), errorFloor);
    end

    ridgeTable = struct2table(rows);
    frequencyTable = vertcat(frequencyParts{:});

end

function row = emptyRidgeRow()
% emptyRidgeRow Return the scalar fields saved for one ridge setting.

    row = struct( ...
        'Lambda', NaN, ...
        'MAPComplexError', NaN, ...
        'CO2ComplexError', NaN, ...
        'MAPComplexAdvantage', NaN, ...
        'CO2ComplexAdvantage', NaN, ...
        'PredictionError', NaN, ...
        'MedianRegularizedConditionNumber', NaN, ...
        'MAPMISOHasLowerComplexError', false, ...
        'CO2MISOHasLowerComplexError', false);

end

function frequencyTable = createRidgeFrequencyTable( ...
    lambda, frequencyHz, mapSiso, mapMiso, ...
    co2Siso, co2Miso, regularizedConditionNumber, errorFloor)
% createRidgeFrequencyTable Store frequency-resolved ridge results.

    numRows = numel(frequencyHz);
    frequencyTable = table( ...
        repmat(lambda, numRows, 1), frequencyHz(:), ...
        mapMiso.complex, ...
        calculateErrorAdvantage( ...
            mapSiso.complex, mapMiso.complex, errorFloor), ...
        mapMiso.gain, ...
        calculateErrorAdvantage( ...
            mapSiso.gain, mapMiso.gain, errorFloor), ...
        mapMiso.phase, ...
        calculateErrorAdvantage( ...
            mapSiso.phase, mapMiso.phase, errorFloor), ...
        co2Miso.complex, ...
        calculateErrorAdvantage( ...
            co2Siso.complex, co2Miso.complex, errorFloor), ...
        co2Miso.gain, ...
        calculateErrorAdvantage( ...
            co2Siso.gain, co2Miso.gain, errorFloor), ...
        co2Miso.phase, ...
        calculateErrorAdvantage( ...
            co2Siso.phase, co2Miso.phase, errorFloor), ...
        regularizedConditionNumber(:), ...
        'VariableNames', { ...
            'Lambda', 'FrequencyHz', ...
            'MAPMISOComplexError', ...
            'MAPComplexAdvantage', ...
            'MAPMISOGainError', ...
            'MAPGainAdvantage', ...
            'MAPMISOPhaseErrorRadians', 'MAPPhaseAdvantage', ...
            'CO2MISOComplexError', ...
            'CO2ComplexAdvantage', ...
            'CO2MISOGainError', ...
            'CO2GainAdvantage', ...
            'CO2MISOPhaseErrorRadians', 'CO2PhaseAdvantage', ...
            'RegularizedConditionNumber'});

end

function conditionNumber = calculateRegularizedConditionNumber( ...
    spectra, lambda)
% calculateRegularizedConditionNumber Condition the normalized ridge matrix.

    numFrequencies = numel(spectra.f);
    conditionNumber = NaN(numFrequencies, 1);
    for frequencyIndex = 1:numFrequencies
        spectralMatrix = [ ...
            spectra.map.power(frequencyIndex), ...
            spectra.cross.mapCo2(frequencyIndex); ...
            spectra.cross.co2Map(frequencyIndex), ...
            spectra.co2.power(frequencyIndex)];
        inputPowers = real(diag(spectralMatrix));
        if any(inputPowers <= 0) || any(~isfinite(spectralMatrix), "all")
            continue
        end
        scaleMatrix = diag(sqrt(inputPowers));
        normalizedMatrix = ...
            scaleMatrix \ spectralMatrix / scaleMatrix;
        conditionNumber(frequencyIndex) = ...
            cond(normalizedMatrix + lambda*eye(2));
    end

end
