function bandGain = calculateBandAveragedGain( ...
    impulseResponse, samplingFrequencyHz, frequencyRangeHz)
% calculateBandAveragedGain Return RMS transfer-function gain in one band.

    validateattributes( ...
        frequencyRangeHz, {'numeric'}, ...
        {'numel', 2, 'increasing', 'nonnegative', 'finite'});

    frequencyHz = linspace( ...
        frequencyRangeHz(1), frequencyRangeHz(2), 2048)';
    response = freqz( ...
        impulseResponse, 1, frequencyHz, samplingFrequencyHz);
    bandGain = sqrt(mean(abs(response).^2, "omitnan"));

end
