function kernel = createPetco2VasoreactivityKernel( ...
    pathwayGain, timeConstantSeconds, delaySeconds, ...
    samplingFrequencyHz, durationTimeConstants)
% createPetco2VasoreactivityKernel Create a delayed low-pass PETCO2 pathway.

    kernel = createExponentialPathwayKernel( ...
        pathwayGain, timeConstantSeconds, delaySeconds, ...
        samplingFrequencyHz, durationTimeConstants);

end
