function row = createKnownTruthObservationResultRow( ...
    observationId, familyRow, planRow, analysis, ~)
% createKnownTruthObservationResultRow Flatten one result for plotting.

    row = emptyRow();

    row.ObservationID = observationId;
    row.FamilyID = familyRow.FamilyID;
    row.ScenarioID = familyRow.ScenarioID;
    row.PlanID = planRow.PlanID;
    row.Experiment = planRow.Experiment;
    row.DurationSeconds = planRow.DurationSeconds;
    row.AnalyzedDurationSeconds = ...
        analysis.diagnostics.analyzedDurationSeconds;
    row.OutputSNRdB = planRow.OutputSNRdB;
    row.MAPInputSNRdB = planRow.MAPInputSNRdB;
    row.CO2InputSNRdB = planRow.CO2InputSNRdB;
    row.AlignmentErrorSeconds = planRow.AlignmentErrorSeconds;

    row.TargetInputCoherence = familyRow.TargetInputCoherence;
    row.SpectralSimilarityControl = ...
        familyRow.SpectralSimilarityControl;
    row.DesignedPSDShapeOverlap = ...
        familyRow.DesignedPSDShapeOverlap;
    row.AssignedPETCO2ToMAPFluctuationSDRatio = ...
        familyRow.PETCO2ToMAPFluctuationSDRatio;
    row.AssignedPETCO2ToMAPBandGainRatio = ...
        familyRow.PETCO2ToMAPBandGainRatio;
    row.CO2DelaySeconds = familyRow.CO2DelaySeconds;
    row.MAPPathwayTimeConstantSeconds = ...
        familyRow.MAPPathwayTimeConstantSeconds;
    row.CO2PathwayTimeConstantSeconds = ...
        familyRow.CO2PathwayTimeConstantSeconds;

    row.RealizedInputCoherence = mean( ...
        analysis.diagnostics.inputCoherence, "omitnan");
    row.RealizedPSDShapeOverlap = ...
        analysis.diagnostics.realizedPSDShapeOverlap;
    row.RealizedPETCO2ToMAPFluctuationSDRatio = ...
        analysis.diagnostics.realizedPETCO2ToMAPFluctuationSDRatio;
    row.AchievedPETCO2ToMAPBandGainRatio = ...
        analysis.diagnostics.achievedPETCO2ToMAPBandGainRatio;
    row.RealizedPETCO2ContributionPowerShare = ...
        analysis.diagnostics.realizedPETCO2ContributionPowerShare;
    row.MedianRawConditionNumber = median( ...
        analysis.diagnostics.rawConditionNumber, "omitnan");
    row.MedianNormalizedConditionNumber = median( ...
        analysis.diagnostics.normalizedConditionNumber, "omitnan");
    row.MedianNormalizedDeterminant = median( ...
        analysis.diagnostics.normalizedDeterminant, "omitnan");
    row.NumWelchWindows = analysis.diagnostics.numWelchWindows;
    row.NumAnalyzedSamples = ...
        analysis.diagnostics.numAnalyzedSamples;

    row.MAPSISOComplexError = ...
        analysis.summary.map.siso.normalizedComplexError;
    row.MAPMISOComplexError = ...
        analysis.summary.map.miso.normalizedComplexError;
    row.MAPComplexAdvantage = ...
        analysis.summaryAdvantage.map.complex;
    row.MAPSISOGainError = ...
        analysis.summary.map.siso.meanAbsoluteGainError;
    row.MAPMISOGainError = ...
        analysis.summary.map.miso.meanAbsoluteGainError;
    row.MAPGainAdvantage = ...
        analysis.summaryAdvantage.map.gain;
    row.MAPSISOPhaseErrorRadians = ...
        analysis.summary.map.siso.meanAbsolutePhaseErrorRadians;
    row.MAPMISOPhaseErrorRadians = ...
        analysis.summary.map.miso.meanAbsolutePhaseErrorRadians;
    row.MAPPhaseAdvantage = ...
        analysis.summaryAdvantage.map.phase;

    row.CO2SISOComplexError = ...
        analysis.summary.co2.siso.normalizedComplexError;
    row.CO2MISOComplexError = ...
        analysis.summary.co2.miso.normalizedComplexError;
    row.CO2ComplexAdvantage = ...
        analysis.summaryAdvantage.co2.complex;
    row.CO2SISOGainError = ...
        analysis.summary.co2.siso.meanAbsoluteGainError;
    row.CO2MISOGainError = ...
        analysis.summary.co2.miso.meanAbsoluteGainError;
    row.CO2GainAdvantage = ...
        analysis.summaryAdvantage.co2.gain;
    row.CO2SISOPhaseErrorRadians = ...
        analysis.summary.co2.siso.meanAbsolutePhaseErrorRadians;
    row.CO2MISOPhaseErrorRadians = ...
        analysis.summary.co2.miso.meanAbsolutePhaseErrorRadians;
    row.CO2PhaseAdvantage = ...
        analysis.summaryAdvantage.co2.phase;

    row.MapSISOPredictionError = ...
        analysis.prediction.sisoMap;
    row.CO2SISOPredictionError = ...
        analysis.prediction.sisoCo2;
    row.MISOPredictionError = analysis.prediction.miso;
    row.PredictionAdvantage = ...
        analysis.prediction.advantage;

    row.MAPMISOFailureRate = ...
        analysis.summary.map.miso.failureRate;
    row.CO2MISOFailureRate = ...
        analysis.summary.co2.miso.failureRate;
    row.MAPMISOExtremeCoefficientRate = ...
        analysis.summary.map.miso.extremeCoefficientRate;
    row.CO2MISOExtremeCoefficientRate = ...
        analysis.summary.co2.miso.extremeCoefficientRate;

    row.IsMainExperiment = planRow.Experiment == "Main";
    row.IsReferenceObservation = ...
        planRow.IsReferenceObservation;
    row.IsFamilyCharacterizationObservation = ...
        planRow.IsFamilyCharacterizationObservation;

end

function row = emptyRow()
% emptyRow Define the stable scalar schema for one observation.

    row = struct( ...
        'ObservationID', NaN, ...
        'FamilyID', NaN, ...
        'ScenarioID', NaN, ...
        'PlanID', NaN, ...
        'Experiment', "", ...
        'DurationSeconds', NaN, ...
        'AnalyzedDurationSeconds', NaN, ...
        'OutputSNRdB', NaN, ...
        'MAPInputSNRdB', NaN, ...
        'CO2InputSNRdB', NaN, ...
        'AlignmentErrorSeconds', NaN, ...
        'TargetInputCoherence', NaN, ...
        'SpectralSimilarityControl', NaN, ...
        'DesignedPSDShapeOverlap', NaN, ...
        'AssignedPETCO2ToMAPFluctuationSDRatio', NaN, ...
        'AssignedPETCO2ToMAPBandGainRatio', NaN, ...
        'CO2DelaySeconds', NaN, ...
        'MAPPathwayTimeConstantSeconds', NaN, ...
        'CO2PathwayTimeConstantSeconds', NaN, ...
        'RealizedInputCoherence', NaN, ...
        'RealizedPSDShapeOverlap', NaN, ...
        'RealizedPETCO2ToMAPFluctuationSDRatio', NaN, ...
        'AchievedPETCO2ToMAPBandGainRatio', NaN, ...
        'RealizedPETCO2ContributionPowerShare', NaN, ...
        'FamilyInputCoherence', NaN, ...
        'FamilyPSDShapeOverlap', NaN, ...
        'FamilyPETCO2ToMAPFluctuationSDRatio', NaN, ...
        'FamilyPETCO2ContributionPowerShare', NaN, ...
        'MedianRawConditionNumber', NaN, ...
        'MedianNormalizedConditionNumber', NaN, ...
        'MedianNormalizedDeterminant', NaN, ...
        'NumWelchWindows', NaN, ...
        'NumAnalyzedSamples', NaN, ...
        'MAPSISOComplexError', NaN, ...
        'MAPMISOComplexError', NaN, ...
        'MAPComplexAdvantage', NaN, ...
        'MAPSISOGainError', NaN, ...
        'MAPMISOGainError', NaN, ...
        'MAPGainAdvantage', NaN, ...
        'MAPSISOPhaseErrorRadians', NaN, ...
        'MAPMISOPhaseErrorRadians', NaN, ...
        'MAPPhaseAdvantage', NaN, ...
        'CO2SISOComplexError', NaN, ...
        'CO2MISOComplexError', NaN, ...
        'CO2ComplexAdvantage', NaN, ...
        'CO2SISOGainError', NaN, ...
        'CO2MISOGainError', NaN, ...
        'CO2GainAdvantage', NaN, ...
        'CO2SISOPhaseErrorRadians', NaN, ...
        'CO2MISOPhaseErrorRadians', NaN, ...
        'CO2PhaseAdvantage', NaN, ...
        'MapSISOPredictionError', NaN, ...
        'CO2SISOPredictionError', NaN, ...
        'MISOPredictionError', NaN, ...
        'PredictionAdvantage', NaN, ...
        'MAPMISOFailureRate', NaN, ...
        'CO2MISOFailureRate', NaN, ...
        'MAPMISOExtremeCoefficientRate', NaN, ...
        'CO2MISOExtremeCoefficientRate', NaN, ...
        'IsMainExperiment', false, ...
        'IsReferenceObservation', false, ...
        'IsFamilyCharacterizationObservation', false);

end
