function observationPlan = createKnownTruthObservationPlan(settings)
% createKnownTruthObservationPlan List all paired observation variants.
%
% The main experiment crosses duration with CBFV output SNR. Secondary
% experiments vary input measurement noise and CO2 alignment at one
% user-selected standard duration and output SNR.

    durations = settings.observations.durationSeconds(:);
    outputSnrValues = settings.observations.outputSnrDb(:);
    referenceDuration = ...
        settings.observations.referenceDurationSeconds;
    validateattributes(referenceDuration, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});
    characterizationDuration = max([durations; referenceDuration]);
    referenceOutputSnr = ...
        settings.observations.referenceOutputSnrDb;

    if ~ismember(referenceOutputSnr, outputSnrValues)
        % Keep the workflow easy to edit. If the user changes the SNR
        % sweep but forgets to change the reference, use the closest
        % available finite value.
        finiteIndices = find(isfinite(outputSnrValues));
        if isempty(finiteIndices)
            referenceOutputSnr = outputSnrValues(1);
        else
            [~, nearestIndex] = min(abs( ...
                outputSnrValues(finiteIndices) - referenceOutputSnr));
            referenceOutputSnr = ...
                outputSnrValues(finiteIndices(nearestIndex));
        end
    end

    rows = cell(0, 1);

    for durationIndex = 1:numel(durations)
        for snrIndex = 1:numel(outputSnrValues)
            rows{end + 1,1} = makePlanRow( ...
                "Main", durations(durationIndex), ...
                outputSnrValues(snrIndex), Inf, Inf, 0, false); %#ok<AGROW>
        end
    end

    % Add the standard duration if the user did not also place it in the
    % duration sweep. This keeps the main settings easy to edit.
    hasReferenceDuration = any(durations == referenceDuration);
    if ~hasReferenceDuration
        for snrIndex = 1:numel(outputSnrValues)
            rows{end + 1,1} = makePlanRow( ...
                "Main", referenceDuration, ...
                outputSnrValues(snrIndex), Inf, Inf, 0, false); %#ok<AGROW>
        end
    end

    % A long, noise-free observation defines the intrinsic realized
    % properties of each family. Add it if it is absent from the main grid.
    hasCleanCharacterization = ...
        any([durations; referenceDuration] == ...
            characterizationDuration) && ...
        any(isinf(outputSnrValues));
    if ~hasCleanCharacterization
        rows{end + 1,1} = makePlanRow( ...
            "Family characterization", characterizationDuration, ...
            Inf, Inf, Inf, 0, false);
    end

    if settings.observations.runInputNoiseExperiment
        inputSnrValues = ...
            settings.observations.inputNoiseSnrDb(:);
        for snrIndex = 1:numel(inputSnrValues)
            rows{end + 1,1} = makePlanRow( ...
                "MAP input noise", referenceDuration, ...
                referenceOutputSnr, inputSnrValues(snrIndex), ...
                Inf, 0, false); %#ok<AGROW>
            rows{end + 1,1} = makePlanRow( ...
                "CO2 input noise", referenceDuration, ...
                referenceOutputSnr, Inf, ...
                inputSnrValues(snrIndex), 0, false); %#ok<AGROW>
        end
    end

    if settings.observations.runAlignmentExperiment
        alignmentErrors = ...
            settings.observations.alignmentErrorSeconds(:);
        for alignmentIndex = 1:numel(alignmentErrors)
            rows{end + 1,1} = makePlanRow( ...
                "Alignment", referenceDuration, ...
                referenceOutputSnr, Inf, Inf, ...
                alignmentErrors(alignmentIndex), false); %#ok<AGROW>
        end
    end

    observationPlan = vertcat(rows{:});
    observationPlan.PlanID = (1:height(observationPlan))';

    observationPlan.IsReferenceObservation = ...
        observationPlan.Experiment == "Main" & ...
        observationPlan.DurationSeconds == referenceDuration & ...
        observationPlan.OutputSNRdB == referenceOutputSnr;
    observationPlan.IsFamilyCharacterizationObservation = ...
        ismember(observationPlan.Experiment, ...
            ["Main", "Family characterization"]) & ...
        observationPlan.DurationSeconds == characterizationDuration & ...
        isinf(observationPlan.OutputSNRdB) & ...
        isinf(observationPlan.MAPInputSNRdB) & ...
        isinf(observationPlan.CO2InputSNRdB) & ...
        observationPlan.AlignmentErrorSeconds == 0;

    % Ridge and estimator sensitivity are evaluated once per family at
    % the same standard observation used for non-duration comparisons.
    observationPlan.RunRidge( ...
        observationPlan.IsReferenceObservation) = true;

    observationPlan = movevars( ...
        observationPlan, "PlanID", "Before", 1);

end

function row = makePlanRow( ...
    experiment, durationSeconds, outputSnrDb, mapInputSnrDb, ...
    co2InputSnrDb, alignmentErrorSeconds, runRidge)
% makePlanRow Create one-row table for a single observation variant.

    row = table( ...
        string(experiment), durationSeconds, outputSnrDb, ...
        mapInputSnrDb, co2InputSnrDb, alignmentErrorSeconds, ...
        logical(runRidge), ...
        'VariableNames', { ...
            'Experiment', 'DurationSeconds', 'OutputSNRdB', ...
            'MAPInputSNRdB', 'CO2InputSNRdB', ...
            'AlignmentErrorSeconds', 'RunRidge'});

end
