function familyDesign = createKnownTruthFamilyDesign(settings)
% createKnownTruthFamilyDesign Create balanced family-level physiology.
%
% Named physiological factors use fixed levels with nearly equal counts.
% Time constants remain continuous nuisance variables.

    numFamilies = settings.families.numFamilies;
    validateattributes( ...
        numFamilies, {'numeric'}, ...
        {'scalar', 'integer', 'positive', 'finite'});
    validateFamilyFactorValues(settings.families);

    previousRandomState = rng;
    restoreRandomState = onCleanup(@() rng(previousRandomState));
    rng(settings.randomSeed, "twister");

    targetCoherence = createBalancedFamilyLevels( ...
        settings.families.targetCoherenceValues, numFamilies);
    spectralSimilarity = createBalancedFamilyLevels( ...
        settings.families.spectralSimilarityValues, numFamilies);
    petco2ToMapFluctuationSdRatio = createBalancedFamilyLevels( ...
        settings.families.petco2ToMapFluctuationSdRatioValues, ...
        numFamilies);
    petco2ToMapBandGainRatio = createBalancedFamilyLevels( ...
        settings.families.petco2ToMapBandGainRatioValues, ...
        numFamilies);
    co2DelaySeconds = createBalancedFamilyLevels( ...
        settings.families.co2DelaySecondsValues, numFamilies);
    mapTimeConstantSeconds = sampleLinearRange( ...
        numFamilies, ...
        settings.families.mapPathwayTimeConstantRange);
    co2TimeConstantSeconds = sampleLinearRange( ...
        numFamilies, ...
        settings.families.co2PathwayTimeConstantRange);

    fs = settings.samplingFrequencyHz;
    co2DelaySeconds = round(co2DelaySeconds*fs)/fs;

    familyId = (1:numFamilies)';
    scenarioId = familyId;
    familySeed = settings.randomSeed + 1000*familyId;

    designedSpectralOverlap = NaN(numFamilies, 1);
    for familyIndex = 1:numFamilies
        scenario = makeScenario( ...
            targetCoherence(familyIndex), ...
            spectralSimilarity(familyIndex), ...
            petco2ToMapFluctuationSdRatio(familyIndex), ...
            petco2ToMapBandGainRatio(familyIndex), ...
            co2DelaySeconds(familyIndex), ...
            mapTimeConstantSeconds(familyIndex), ...
            co2TimeConstantSeconds(familyIndex));
        frequencyHz = linspace( ...
            settings.frequencyRangeHz(1), ...
            settings.frequencyRangeHz(2), 1024)';
        shapes = createKnownTruthInputSpectra( ...
            frequencyHz, scenario, settings);
        designedSpectralOverlap(familyIndex) = ...
            calculatePSDShapeOverlap( ...
                shapes.mapPower, shapes.co2Power);
    end

    familyDesign = table( ...
        familyId, scenarioId, familySeed, targetCoherence, ...
        spectralSimilarity, designedSpectralOverlap, ...
        petco2ToMapFluctuationSdRatio, petco2ToMapBandGainRatio, ...
        co2DelaySeconds, ...
        mapTimeConstantSeconds, co2TimeConstantSeconds, ...
        'VariableNames', { ...
            'FamilyID', 'ScenarioID', 'FamilySeed', ...
            'TargetInputCoherence', 'SpectralSimilarityControl', ...
            'DesignedPSDShapeOverlap', ...
            'PETCO2ToMAPFluctuationSDRatio', ...
            'PETCO2ToMAPBandGainRatio', 'CO2DelaySeconds', ...
            'MAPPathwayTimeConstantSeconds', ...
            'CO2PathwayTimeConstantSeconds'});

    clear restoreRandomState

end

function validateFamilyFactorValues(families)
% validateFamilyFactorValues Give clear errors for editable main settings.

    validateattributes( ...
        families.targetCoherenceValues, {'numeric'}, ...
        {'nonempty', 'finite', '>=', 0, '<=', 1});
    validateattributes( ...
        families.spectralSimilarityValues, {'numeric'}, ...
        {'nonempty', 'finite', '>=', 0, '<=', 1});
    validateattributes( ...
        families.petco2ToMapFluctuationSdRatioValues, {'numeric'}, ...
        {'nonempty', 'finite', 'positive'});
    validateattributes( ...
        families.petco2ToMapBandGainRatioValues, {'numeric'}, ...
        {'nonempty', 'finite', 'positive'});
    validateattributes( ...
        families.co2DelaySecondsValues, {'numeric'}, ...
        {'nonempty', 'finite', 'nonnegative'});

end

function values = sampleLinearRange(numValues, range)
% sampleLinearRange Draw one randomized point from each equal interval.

    unitValues = stratifiedUnitValues(numValues);
    values = range(1) + unitValues*(range(2) - range(1));

end

function values = stratifiedUnitValues(numValues)
% stratifiedUnitValues Return shuffled values between zero and one.

    values = ((0:(numValues - 1))' + rand(numValues, 1))/numValues;
    values = values(randperm(numValues));

end

function scenario = makeScenario( ...
    targetCoherence, spectralSimilarity, ...
    petco2ToMapFluctuationSdRatio, ...
    petco2ToMapBandGainRatio, co2DelaySeconds, mapTimeConstantSeconds, ...
    co2TimeConstantSeconds)
% makeScenario Make the small struct used by the spectrum helper.

    scenario.targetInputCoherence = targetCoherence;
    scenario.spectralSimilarityControl = spectralSimilarity;
    scenario.petco2ToMapFluctuationSdRatio = ...
        petco2ToMapFluctuationSdRatio;
    scenario.petco2ToMapBandGainRatio = ...
        petco2ToMapBandGainRatio;
    scenario.co2DelaySeconds = co2DelaySeconds;
    scenario.mapPathwayTimeConstantSeconds = ...
        mapTimeConstantSeconds;
    scenario.co2PathwayTimeConstantSeconds = ...
        co2TimeConstantSeconds;

end
