function kernel = createExponentialPathwayKernel( ...
    pathwayGain, timeConstantSeconds, delaySeconds, ...
    samplingFrequencyHz, durationTimeConstants)
% createExponentialPathwayKernel Create a causal pathway with known truth.

    validateattributes( ...
        timeConstantSeconds, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});
    validateattributes( ...
        delaySeconds, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'});

    numKernelSamples = max(2, round( ...
        durationTimeConstants*timeConstantSeconds*samplingFrequencyHz));
    timeSeconds = ...
        (0:(numKernelSamples - 1))'/samplingFrequencyHz;
    kernel = exp(-timeSeconds/timeConstantSeconds);
    kernel = pathwayGain*kernel/sum(kernel);

    numDelaySamples = round(delaySeconds*samplingFrequencyHz);
    kernel = [zeros(numDelaySamples, 1); kernel];

end
