function kernel = createMapAutoregulationKernel( ...
    highFrequencyGain, lowFrequencyGainFraction, ...
    timeConstantSeconds, samplingFrequencyHz, durationTimeConstants)
% createMapAutoregulationKernel Create a simple autoregulatory MAP pathway.
%
% The pathway retains only a fraction of slow MAP changes but approaches
% highFrequencyGain for faster changes. This produces the rising gain that
% is expected from a basic high-pass-like autoregulatory response.

    validateattributes( ...
        highFrequencyGain, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});
    validateattributes( ...
        lowFrequencyGainFraction, {'numeric'}, ...
        {'scalar', '>=', 0, '<=', 1, 'finite'});
    validateattributes( ...
        timeConstantSeconds, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});

    lowPass = createExponentialPathwayKernel( ...
        1, timeConstantSeconds, 0, samplingFrequencyHz, ...
        durationTimeConstants);
    impulse = zeros(size(lowPass));
    impulse(1) = 1;

    residualLowFrequencyPart = ...
        lowFrequencyGainFraction*impulse;
    highPassPart = ...
        (1 - lowFrequencyGainFraction)*(impulse - lowPass);
    kernel = highFrequencyGain*( ...
        residualLowFrequencyPart + highPassPart);

end
