function [resultTable, frequencyTable] = ...
    runKnownTruthEstimatorSettingExperiment( ...
    family, familyRow, referencePlan, settings)
% runKnownTruthEstimatorSettingExperiment Check editable Welch choices.
%
% Window length and overlap are varied one at a time. All other settings
% remain at their primary values.

    if ~settings.estimatorSensitivity.enabled
        resultTable = table();
        frequencyTable = table();
        return
    end

    windowValues = ...
        settings.estimatorSensitivity.windowLengthSeconds(:);
    overlapValues = ...
        settings.estimatorSensitivity.windowOverlap(:);
    durationValues = ...
        settings.observations.durationSeconds(:);
    numRows = numel(windowValues) + numel(overlapValues) + ...
        numel(durationValues)*numel(windowValues);
    resultParts = cell(numRows, 1);
    frequencyParts = cell(numRows, 1);
    rowIndex = 0;

    for windowIndex = 1:numel(windowValues)
        variantSettings = settings;
        variantSettings.welch.windowLengthSeconds = ...
            windowValues(windowIndex);
        variantSettings.welch.smoothingEnabled = ...
            settings.welch.smoothingEnabled;

        rowIndex = rowIndex + 1;
        [resultParts{rowIndex}, frequencyParts{rowIndex}] = ...
            analyzeVariant( ...
            family, familyRow, referencePlan, variantSettings, ...
            "Window length");
    end

    for overlapIndex = 1:numel(overlapValues)
        variantSettings = settings;
        variantSettings.welch.windowLengthSeconds = ...
            settings.welch.windowLengthSeconds;
        variantSettings.welch.windowOverlap = ...
            overlapValues(overlapIndex);

        rowIndex = rowIndex + 1;
        [resultParts{rowIndex}, frequencyParts{rowIndex}] = ...
            analyzeVariant( ...
            family, familyRow, referencePlan, variantSettings, ...
            "Window overlap");
    end

    % This paired grid separates the effect of a longer recording from the
    % effect of using a longer Welch window.
    for durationIndex = 1:numel(durationValues)
        durationPlan = referencePlan;
        durationPlan.DurationSeconds = durationValues(durationIndex);
        for windowIndex = 1:numel(windowValues)
            variantSettings = settings;
            variantSettings.welch.windowLengthSeconds = ...
                windowValues(windowIndex);

            rowIndex = rowIndex + 1;
            [resultParts{rowIndex}, frequencyParts{rowIndex}] = ...
                analyzeVariant( ...
                    family, familyRow, durationPlan, ...
                    variantSettings, "Duration by window");
        end
    end

    resultTable = vertcat(resultParts{:});
    frequencyTable = vertcat(frequencyParts{:});

end

function [result, frequencyResult] = analyzeVariant( ...
    family, familyRow, referencePlan, variantSettings, sweepName)
% analyzeVariant Analyze one estimator setting on the reference signals.

    training = createKnownTruthObservation( ...
        family.training, referencePlan);
    validation = createKnownTruthObservation( ...
        family.validation, referencePlan);
    analysis = analyzeKnownTruthObservation( ...
        training, validation, variantSettings, false);

    resultRow = createKnownTruthObservationResultRow( ...
        NaN, familyRow, referencePlan, analysis, variantSettings);
    result = struct2table(resultRow);
    result.Sweep = string(sweepName);
    result.WelchWindowLengthSeconds = ...
        variantSettings.welch.windowLengthSeconds;
    result.WelchWindowOverlap = ...
        variantSettings.welch.windowOverlap;
    result.MeetsMinimumWelchWindows = ...
        result.NumWelchWindows >= variantSettings.welch.minimumWindows;

    frequencyResult = createEstimatorFrequencyTable( ...
        analysis, result, familyRow.FamilyID, sweepName);

end

function frequencyTable = createEstimatorFrequencyTable( ...
    analysis, result, familyId, sweepName)
% createEstimatorFrequencyTable Store one native Welch frequency grid.

    numRows = numel(analysis.frequencyHz);
    frequencyTable = table( ...
        repmat(familyId, numRows, 1), ...
        repmat(string(sweepName), numRows, 1), ...
        repmat(result.WelchWindowLengthSeconds, numRows, 1), ...
        repmat(result.WelchWindowOverlap, numRows, 1), ...
        repmat(result.NumWelchWindows, numRows, 1), ...
        repmat(result.MeetsMinimumWelchWindows, numRows, 1), ...
        analysis.frequencyHz(:), ...
        analysis.frequencyError.map.siso.complex, ...
        analysis.frequencyError.map.miso.complex, ...
        analysis.frequencyAdvantage.map.complex, ...
        analysis.frequencyError.map.siso.gain, ...
        analysis.frequencyError.map.miso.gain, ...
        analysis.frequencyAdvantage.map.gain, ...
        analysis.frequencyError.map.siso.phase, ...
        analysis.frequencyError.map.miso.phase, ...
        analysis.frequencyAdvantage.map.phase, ...
        analysis.frequencyError.co2.siso.complex, ...
        analysis.frequencyError.co2.miso.complex, ...
        analysis.frequencyAdvantage.co2.complex, ...
        analysis.frequencyError.co2.siso.gain, ...
        analysis.frequencyError.co2.miso.gain, ...
        analysis.frequencyAdvantage.co2.gain, ...
        analysis.frequencyError.co2.siso.phase, ...
        analysis.frequencyError.co2.miso.phase, ...
        analysis.frequencyAdvantage.co2.phase, ...
        'VariableNames', { ...
            'FamilyID', 'Sweep', ...
            'WelchWindowLengthSeconds', 'WelchWindowOverlap', ...
            'NumWelchWindows', 'MeetsMinimumWelchWindows', ...
            'FrequencyHz', ...
            'MAPSISOComplexError', 'MAPMISOComplexError', ...
            'MAPComplexAdvantage', ...
            'MAPSISOGainError', 'MAPMISOGainError', ...
            'MAPGainAdvantage', ...
            'MAPSISOPhaseErrorRadians', ...
            'MAPMISOPhaseErrorRadians', 'MAPPhaseAdvantage', ...
            'CO2SISOComplexError', 'CO2MISOComplexError', ...
            'CO2ComplexAdvantage', ...
            'CO2SISOGainError', 'CO2MISOGainError', ...
            'CO2GainAdvantage', ...
            'CO2SISOPhaseErrorRadians', ...
            'CO2MISOPhaseErrorRadians', 'CO2PhaseAdvantage'});

end
