function simulationResults = runKnownTruthSimulationGrid(settings)
% runKnownTruthSimulationGrid Run a reproducible known-truth study.
%
% Results are returned in a tidy table. Each row represents one pathway
% from one estimator in one simulated condition.

    if nargin < 1
        settings = defaultKnownTruthSimulationSettings("quick");
    end

    conditionCount = numel(settings.inputCorrelations) * ...
        numel(settings.co2InputSds) * ...
        numel(settings.co2PathwayScales) * ...
        numel(settings.outputSnrDb) * ...
        numel(settings.durationSeconds) * ...
        numel(settings.co2DelaysSeconds) * ...
        numel(settings.misspecificationStrengths) * ...
        settings.numReplicates;
    estimatorCount = 2 + numel(settings.ridgeLambdas);
    rowCount = conditionCount*estimatorCount*2;

    rows = initializeResultColumns(rowCount);
    rowIndex = 0;
    conditionIndex = 0;

    for correlation = settings.inputCorrelations
        for co2InputSd = settings.co2InputSds
            for co2PathwayScale = settings.co2PathwayScales
                for outputSnrDb = settings.outputSnrDb
                    for durationSeconds = settings.durationSeconds
                        for co2DelaySeconds = ...
                                settings.co2DelaysSeconds
                            for misspecificationStrength = ...
                                    settings.misspecificationStrengths
                                for replicate = 1:settings.numReplicates
                                    conditionIndex = conditionIndex + 1;
                                    seed = settings.randomSeed + ...
                                        2*conditionIndex;

                                    if isfield(settings, "progressEvery") && ...
                                            settings.progressEvery > 0 && ...
                                            (conditionIndex == 1 || ...
                                             mod(conditionIndex, ...
                                             settings.progressEvery) == 0)
                                        fprintf( ...
                                            ['Known-truth condition %d of ' ...
                                             '%d\n'], ...
                                            conditionIndex, ...
                                            conditionCount);
                                    end

                                    condition = createCondition( ...
                                        correlation, co2InputSd, ...
                                        co2PathwayScale, outputSnrDb, ...
                                        durationSeconds, co2DelaySeconds, ...
                                        misspecificationStrength);
                                    training = createKnownTruthMisoSignal( ...
                                        settings, condition, seed);
                                    validation = createKnownTruthMisoSignal( ...
                                        settings, condition, seed + 1);

                                    trainingSpectra = estimateWelchSpectra( ...
                                        training.map, training.co2, ...
                                        training.cbv, training.fs, ...
                                        settings.welch);
                                    validationSpectra = ...
                                        estimateWelchSpectra( ...
                                            validation.map, validation.co2, ...
                                            validation.cbv, validation.fs, ...
                                            settings.welch);

                                    frequencyHz = trainingSpectra.f;
                                    trueMap = freqz( ...
                                        training.truth.mapImpulseResponse, ...
                                        1, frequencyHz, training.fs);
                                    trueCo2 = freqz( ...
                                        training.truth.co2ImpulseResponse, ...
                                        1, frequencyHz, training.fs);

                                    siso = runSISOTFA( ...
                                        trainingSpectra, settings.phase);
                                    direct = runMISOTFA( ...
                                        trainingSpectra, settings.phase);

                                    [rows, rowIndex] = addEstimatorRows( ...
                                        rows, rowIndex, condition, ...
                                        replicate, seed, "SISO", NaN, ...
                                        siso.map.transferFunction, ...
                                        siso.co2.transferFunction, ...
                                        trueMap, trueCo2, trainingSpectra, ...
                                        validationSpectra, settings);
                                    [rows, rowIndex] = addEstimatorRows( ...
                                        rows, rowIndex, condition, ...
                                        replicate, seed, ...
                                        "MISO unregularized", 0, ...
                                        direct.map.transferFunction, ...
                                        direct.co2.transferFunction, ...
                                        trueMap, trueCo2, trainingSpectra, ...
                                        validationSpectra, settings, ...
                                        direct.diagnostics);

                                    for lambda = settings.ridgeLambdas
                                        solverSettings = ...
                                            defaultMisoSolverSettings();
                                        solverSettings.regularization.enabled = ...
                                            true;
                                        solverSettings.regularization.lambda = ...
                                            lambda;
                                        ridge = runMISOTFA( ...
                                            trainingSpectra, ...
                                            settings.phase, solverSettings);
                                        [rows, rowIndex] = addEstimatorRows( ...
                                            rows, rowIndex, condition, ...
                                            replicate, seed, ...
                                            "MISO ridge", lambda, ...
                                            ridge.map.transferFunction, ...
                                            ridge.co2.transferFunction, ...
                                            trueMap, trueCo2, ...
                                            trainingSpectra, ...
                                            validationSpectra, settings, ...
                                            ridge.diagnostics);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end

    simulationResults.trials = columnsToTable(rows, rowIndex);
    simulationResults.settings = settings;
    simulationResults.numConditions = conditionCount;
    simulationResults.numRows = rowIndex;

end

function condition = createCondition( ...
    correlation, co2InputSd, co2PathwayScale, outputSnrDb, ...
    durationSeconds, co2DelaySeconds, misspecificationStrength)
% createCondition Store one combination of simulation factors.

    condition.inputCorrelation = correlation;
    condition.co2InputSd = co2InputSd;
    condition.co2PathwayScale = co2PathwayScale;
    condition.outputSnrDb = outputSnrDb;
    condition.durationSeconds = durationSeconds;
    condition.co2DelaySeconds = co2DelaySeconds;
    condition.misspecificationStrength = misspecificationStrength;

end

function rows = initializeResultColumns(numRows)
% initializeResultColumns Preallocate the tidy output columns.

    rows.Replicate = NaN(numRows, 1);
    rows.Seed = NaN(numRows, 1);
    rows.InputCorrelation = NaN(numRows, 1);
    rows.RealizedInputCoherence = NaN(numRows, 1);
    rows.CO2InputSD = NaN(numRows, 1);
    rows.CO2PathwayScale = NaN(numRows, 1);
    rows.OutputSNRdB = NaN(numRows, 1);
    rows.DurationSeconds = NaN(numRows, 1);
    rows.CO2DelaySeconds = NaN(numRows, 1);
    rows.MisspecificationStrength = NaN(numRows, 1);
    rows.Estimator = strings(numRows, 1);
    rows.Lambda = NaN(numRows, 1);
    rows.Pathway = strings(numRows, 1);
    rows.GainBias = NaN(numRows, 1);
    rows.MeanAbsoluteGainError = NaN(numRows, 1);
    rows.MeanAbsolutePhaseErrorRadians = NaN(numRows, 1);
    rows.IntegratedComplexError = NaN(numRows, 1);
    rows.NormalizedComplexError = NaN(numRows, 1);
    rows.OutOfSampleNormalizedError = NaN(numRows, 1);
    rows.MedianRawConditionNumber = NaN(numRows, 1);
    rows.MedianNormalizedConditionNumber = NaN(numRows, 1);
    rows.MedianNormalizedDeterminant = NaN(numRows, 1);
    rows.FailureRate = NaN(numRows, 1);
    rows.ExtremeCoefficientRate = NaN(numRows, 1);

end

function [rows, rowIndex] = addEstimatorRows( ...
    rows, rowIndex, condition, replicate, seed, estimator, lambda, ...
    mapEstimate, co2Estimate, trueMap, trueCo2, trainingSpectra, ...
    validationSpectra, settings, diagnostics)
% addEstimatorRows Add the MAP and CO2 rows for one fitted estimator.

    if nargin < 15
        diagnostics = struct();
    end

    frequencyHz = trainingSpectra.f;
    realizedInputCoherence = mean( ...
        abs(trainingSpectra.cross.mapCo2).^2 ./ ...
        real(trainingSpectra.map.power .* ...
        trainingSpectra.co2.power), "omitnan");

    pathwayNames = ["MAP"; "CO2"];
    estimates = {mapEstimate; co2Estimate};
    truths = {trueMap; trueCo2};

    for pathwayIndex = 1:2
        rowIndex = rowIndex + 1;

        if estimator == "SISO" && pathwayIndex == 1
            outOfSampleError = calculateValidationPredictionError( ...
                validationSpectra, mapEstimate, ...
                zeros(size(co2Estimate)), ...
                settings.frequencyRangeHz);
        elseif estimator == "SISO"
            outOfSampleError = calculateValidationPredictionError( ...
                validationSpectra, zeros(size(mapEstimate)), ...
                co2Estimate, settings.frequencyRangeHz);
        else
            outOfSampleError = calculateValidationPredictionError( ...
                validationSpectra, mapEstimate, co2Estimate, ...
                settings.frequencyRangeHz);
        end

        metrics = calculateKnownTruthMetrics( ...
            frequencyHz, estimates{pathwayIndex}, ...
            truths{pathwayIndex}, settings.frequencyRangeHz, ...
            settings.extremeCoefficientThreshold);

        rows.Replicate(rowIndex) = replicate;
        rows.Seed(rowIndex) = seed;
        rows.InputCorrelation(rowIndex) = ...
            condition.inputCorrelation;
        rows.RealizedInputCoherence(rowIndex) = ...
            realizedInputCoherence;
        rows.CO2InputSD(rowIndex) = condition.co2InputSd;
        rows.CO2PathwayScale(rowIndex) = ...
            condition.co2PathwayScale;
        rows.OutputSNRdB(rowIndex) = condition.outputSnrDb;
        rows.DurationSeconds(rowIndex) = ...
            condition.durationSeconds;
        rows.CO2DelaySeconds(rowIndex) = ...
            condition.co2DelaySeconds;
        rows.MisspecificationStrength(rowIndex) = ...
            condition.misspecificationStrength;
        rows.Estimator(rowIndex) = estimator;
        rows.Lambda(rowIndex) = lambda;
        rows.Pathway(rowIndex) = pathwayNames(pathwayIndex);
        rows.GainBias(rowIndex) = metrics.gainBias;
        rows.MeanAbsoluteGainError(rowIndex) = ...
            metrics.meanAbsoluteGainError;
        rows.MeanAbsolutePhaseErrorRadians(rowIndex) = ...
            metrics.meanAbsolutePhaseErrorRadians;
        rows.IntegratedComplexError(rowIndex) = ...
            metrics.integratedComplexError;
        rows.NormalizedComplexError(rowIndex) = ...
            metrics.normalizedComplexError;
        rows.OutOfSampleNormalizedError(rowIndex) = ...
            outOfSampleError;
        rows.FailureRate(rowIndex) = metrics.failureRate;
        rows.ExtremeCoefficientRate(rowIndex) = ...
            metrics.extremeCoefficientRate;

        if ~isempty(fieldnames(diagnostics))
            rows.MedianRawConditionNumber(rowIndex) = median( ...
                diagnostics.conditionNumber, "omitnan");
            rows.MedianNormalizedConditionNumber(rowIndex) = median( ...
                diagnostics.normalizedConditionNumber, "omitnan");
            rows.MedianNormalizedDeterminant(rowIndex) = median( ...
                diagnostics.normalizedDeterminant, "omitnan");
        end
    end

end

function resultsTable = columnsToTable(rows, numRows)
% columnsToTable Trim preallocated arrays and create the final table.

    fieldNames = fieldnames(rows);
    for fieldIndex = 1:numel(fieldNames)
        fieldName = fieldNames{fieldIndex};
        rows.(fieldName) = rows.(fieldName)(1:numRows,:);
    end
    resultsTable = struct2table(rows);

end
