function [scaledKernel, achievedRatio] = ...
    scalePathwayToBandGainRatio( ...
        pathwayKernel, referenceKernel, targetRatio, ...
        samplingFrequencyHz, frequencyRangeHz)
% scalePathwayToBandGainRatio Match an RMS gain ratio over the study band.

    validateattributes( ...
        targetRatio, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});

    referenceGain = calculateBandAveragedGain( ...
        referenceKernel, samplingFrequencyHz, frequencyRangeHz);
    pathwayGain = calculateBandAveragedGain( ...
        pathwayKernel, samplingFrequencyHz, frequencyRangeHz);

    if pathwayGain <= 0 || ~isfinite(pathwayGain)
        error( ...
            "TFA:InvalidPathwayGain", ...
            "The unscaled pathway has zero or invalid band gain.");
    end

    scaledKernel = pathwayKernel*(targetRatio*referenceGain/pathwayGain);
    achievedRatio = calculateBandAveragedGain( ...
        scaledKernel, samplingFrequencyHz, frequencyRangeHz)/ ...
        referenceGain;

end
