function results = storeKnownTruthFrequencyResult( ...
    results, observationColumn, observationId, analysis)
% storeKnownTruthFrequencyResult Save one observation into preallocated arrays.

    results.observationId(observationColumn) = observationId;
    results.inputCoherence(:,observationColumn) = ...
        analysis.diagnostics.inputCoherence;
    results.normalizedConditionNumber(:,observationColumn) = ...
        analysis.diagnostics.normalizedConditionNumber;
    results.normalizedDeterminant(:,observationColumn) = ...
        analysis.diagnostics.normalizedDeterminant;

    results.map.truth(:,observationColumn) = analysis.truth.map;
    results.map.sisoEstimate(:,observationColumn) = ...
        analysis.estimate.map.siso;
    results.map.misoEstimate(:,observationColumn) = ...
        analysis.estimate.map.miso;
    results.map.sisoComplexError(:,observationColumn) = ...
        analysis.frequencyError.map.siso.complex;
    results.map.misoComplexError(:,observationColumn) = ...
        analysis.frequencyError.map.miso.complex;
    results.map.sisoGainError(:,observationColumn) = ...
        analysis.frequencyError.map.siso.gain;
    results.map.misoGainError(:,observationColumn) = ...
        analysis.frequencyError.map.miso.gain;
    results.map.sisoPhaseErrorRadians(:,observationColumn) = ...
        analysis.frequencyError.map.siso.phase;
    results.map.misoPhaseErrorRadians(:,observationColumn) = ...
        analysis.frequencyError.map.miso.phase;
    results.map.complexAdvantage(:,observationColumn) = ...
        analysis.frequencyAdvantage.map.complex;
    results.map.gainAdvantage(:,observationColumn) = ...
        analysis.frequencyAdvantage.map.gain;
    results.map.phaseAdvantage(:,observationColumn) = ...
        analysis.frequencyAdvantage.map.phase;

    results.co2.truth(:,observationColumn) = analysis.truth.co2;
    results.co2.sisoEstimate(:,observationColumn) = ...
        analysis.estimate.co2.siso;
    results.co2.misoEstimate(:,observationColumn) = ...
        analysis.estimate.co2.miso;
    results.co2.sisoComplexError(:,observationColumn) = ...
        analysis.frequencyError.co2.siso.complex;
    results.co2.misoComplexError(:,observationColumn) = ...
        analysis.frequencyError.co2.miso.complex;
    results.co2.sisoGainError(:,observationColumn) = ...
        analysis.frequencyError.co2.siso.gain;
    results.co2.misoGainError(:,observationColumn) = ...
        analysis.frequencyError.co2.miso.gain;
    results.co2.sisoPhaseErrorRadians(:,observationColumn) = ...
        analysis.frequencyError.co2.siso.phase;
    results.co2.misoPhaseErrorRadians(:,observationColumn) = ...
        analysis.frequencyError.co2.miso.phase;
    results.co2.complexAdvantage(:,observationColumn) = ...
        analysis.frequencyAdvantage.co2.complex;
    results.co2.gainAdvantage(:,observationColumn) = ...
        analysis.frequencyAdvantage.co2.gain;
    results.co2.phaseAdvantage(:,observationColumn) = ...
        analysis.frequencyAdvantage.co2.phase;

end
