function bandAverages = computeMISOBandAverages( ...
    f, ...
    H_mapcbv, ...
    H_co2cbv, ...
    multiple_coherence, ...
    partial_coh_map_cbv_given_co2, ...
    partial_coh_co2_cbv_given_map, ...
    input_input_coherence, ...
    input_input_phase, ...
    condition_number, ...
    coherence_threshold)
% computeMISOBandAverages
%
% Computes unfiltered band averages for MISO TFA results.
%
% Bands:
%   VLF = 0.02 - 0.07 Hz
%   LF  = 0.07 - 0.20 Hz
%   HF  = 0.20 - 0.50 Hz
%
% Phase values are averaged using a circular mean.

    f = f(:);

    % Frequency band masks
    vlf_mask = f >= 0.02 & f < 0.07;
    lf_mask  = f >= 0.07 & f < 0.20;
    hf_mask  = f >= 0.20 & f <= 0.50;

    band_names = ["VLF"; "LF"; "HF"];
    band_masks = {vlf_mask; lf_mask; hf_mask};

    % Preallocate
    map_gain_mean = NaN(3,1);
    map_phase_mean = NaN(3,1);

    co2_gain_mean = NaN(3,1);
    co2_phase_mean = NaN(3,1);

    multiple_coh_mean = NaN(3,1);
    partial_coh_map_mean = NaN(3,1);
    partial_coh_co2_mean = NaN(3,1);

    input_input_coh_mean = NaN(3,1);
    input_input_phase_mean = NaN(3,1);

    condition_number_mean = NaN(3,1);
    condition_number_median = NaN(3,1);

    percent_passed_multiple_coh = NaN(3,1);
    percent_passed_partial_map_coh = NaN(3,1);
    percent_passed_partial_co2_coh = NaN(3,1);

    for b = 1:3

        mask = band_masks{b};

        % MAP -> CBV transfer function summaries
        map_gain_mean(b) = mean(abs(H_mapcbv(mask)), 'omitnan');
        map_phase_mean(b) = circularMeanPhase(angle(H_mapcbv(mask)));

        % CO2 -> CBV transfer function summaries
        co2_gain_mean(b) = mean(abs(H_co2cbv(mask)), 'omitnan');
        co2_phase_mean(b) = circularMeanPhase(angle(H_co2cbv(mask)));

        % Coherence summaries
        multiple_coh_mean(b) = mean(multiple_coherence(mask), 'omitnan');
        partial_coh_map_mean(b) = mean(partial_coh_map_cbv_given_co2(mask), 'omitnan');
        partial_coh_co2_mean(b) = mean(partial_coh_co2_cbv_given_map(mask), 'omitnan');

        % Input-input summaries
        input_input_coh_mean(b) = mean(input_input_coherence(mask), 'omitnan');
        input_input_phase_mean(b) = circularMeanPhase(input_input_phase(mask));

        % Condition number summaries
        condition_number_mean(b) = mean(condition_number(mask),'omitnan');
        condition_number_median(b) = median(condition_number(mask), 'omitnan');

        % Percent passed coherence threshold
        percent_passed_multiple_coh(b) = ...
            100 * mean(multiple_coherence(mask) >= coherence_threshold, 'omitnan');

        percent_passed_partial_map_coh(b) = ...
            100 * mean(partial_coh_map_cbv_given_co2(mask) >= coherence_threshold, 'omitnan');

        percent_passed_partial_co2_coh(b) = ...
            100 * mean(partial_coh_co2_cbv_given_map(mask) >= coherence_threshold, 'omitnan');

    end

    bandAverages = table( ...
    band_names, ...
    map_gain_mean, ...
    map_phase_mean, ...
    co2_gain_mean, ...
    co2_phase_mean, ...
    multiple_coh_mean, ...
    partial_coh_map_mean, ...
    partial_coh_co2_mean, ...
    input_input_coh_mean, ...
    input_input_phase_mean, ...
    condition_number_mean, ...
    condition_number_median, ...
    percent_passed_multiple_coh, ...
    percent_passed_partial_map_coh, ...
    percent_passed_partial_co2_coh, ...
    'VariableNames', { ...
        'Band', ...
        'MAP_Gain_Mean', ...
        'MAP_Phase_CircularMean_rad', ...
        'CO2_Gain_Mean', ...
        'CO2_Phase_CircularMean_rad', ...
        'Multiple_Coh_Mean', ...
        'Partial_Coh_MAP_Mean', ...
        'Partial_Coh_CO2_Mean', ...
        'Input_Input_Coh_Mean', ...
        'Input_Input_Phase_CircularMean_rad', ...
        'Condition_Number_Mean', ...
        'Condition_Number_Median', ...
        'Percent_Passed_Multiple_Coh', ...
        'Percent_Passed_Partial_MAP_Coh', ...
        'Percent_Passed_Partial_CO2_Coh' ...
    });

end


function mean_phase = circularMeanPhase(phase_values)
% circularMeanPhase
%
% Computes circular mean of phase values in radians.
% Prevents incorrect averaging across the -pi / pi boundary.

    phase_values = phase_values(:);
    phase_values = phase_values(~isnan(phase_values));

    if isempty(phase_values)
        mean_phase = NaN;
    else
        mean_phase = angle(mean(exp(1i * phase_values)));
    end

end