function bandAverages = addSubjectMetadataToBandAverages(bandAverages, welchInfo, subjectInfo)

    numBands = height(bandAverages);
    bandColumn = bandAverages(:, "Band");
    metricColumns = removevars(bandAverages, "Band");

    subjectColumns = table( ...
        repmat(string(subjectInfo.subjectID), numBands, 1), ...
        repmat(string(subjectInfo.group), numBands, 1), ...
        repmat(string(subjectInfo.session), numBands, 1), ...
        repmat(string(subjectInfo.sourceFile), numBands, 1), ...
        repmat(welchInfo.numWindows, numBands, 1), ...
        repmat(welchInfo.signalDurationSeconds, numBands, 1), ...
        repmat(welchInfo.isTooShort, numBands, 1), ...
        repmat(welchInfo.usesDefaultCoherenceThreshold, numBands, 1), ...
        repmat(welchInfo.coherenceThreshold, numBands, 1), ...
        'VariableNames', { ...
            'SubjectID', ...
            'Group', ...
            'Session', ...
            'SourceFile', ...
            'NumWelchWindows', ...
            'SignalDurationSeconds', ...
            'IsTooShortForWelch', ...
            'UsesDefaultCoherenceThreshold', ...
            'CoherenceThreshold' ...
        });

    bandAverages = [bandColumn, subjectColumns, metricColumns];

end
