function bandAverages = addSubjectMetadataToBandAverages(bandAverages, welchInfo, subjectInfo)

    numBands = height(bandAverages);
    bandColumn = bandAverages(:, "Band");
    metricColumns = removevars(bandAverages, "Band");

    cbvBaselineCmPerSec = valueFromWelchInfo( ...
        welchInfo, 'cbvBaselineCmPerSec', NaN);
    cbvUnits = valueFromWelchInfo(welchInfo, 'cbvUnits', "");
    phaseUnwrapMethod = valueFromWelchInfo(welchInfo, 'phaseUnwrapMethod', "");

    subjectColumns = table( ...
        repmat(string(subjectInfo.subjectID), numBands, 1), ...
        repmat(string(subjectInfo.group), numBands, 1), ...
        repmat(string(subjectInfo.session), numBands, 1), ...
        repmat(string(subjectInfo.sourceFile), numBands, 1), ...
        repmat(welchInfo.numWindows, numBands, 1), ...
        repmat(welchInfo.signalDurationSeconds, numBands, 1), ...
        repmat(welchInfo.isTooShort, numBands, 1), ...
        repmat(welchInfo.usesDefaultCoherenceThreshold, numBands, 1), ...
        repmat(welchInfo.coherenceThreshold, numBands, 1), ...
        repmat(cbvBaselineCmPerSec, numBands, 1), ...
        repmat(string(cbvUnits), numBands, 1), ...
        repmat(string(phaseUnwrapMethod), numBands, 1), ...
        'VariableNames', { ...
            'SubjectID', ...
            'Group', ...
            'Session', ...
            'SourceFile', ...
            'NumWelchWindows', ...
            'SignalDurationSeconds', ...
            'IsTooShortForWelch', ...
            'UsesDefaultCoherenceThreshold', ...
            'CoherenceThreshold', ...
            'CBVBaseline_cm_per_s', ...
            'CBVUnits', ...
            'PhaseUnwrapMethod' ...
        });

    bandAverages = [bandColumn, subjectColumns, metricColumns];
    bandAverages = renameGainColumnsForDisplay(bandAverages);
    bandAverages = renamePhaseColumnsForDisplay(bandAverages);

end


function value = valueFromWelchInfo(welchInfo, fieldName, defaultValue)

    if isfield(welchInfo, fieldName)
        value = welchInfo.(fieldName);
    else
        value = defaultValue;
    end

end


function bandAverages = renamePhaseColumnsForDisplay(bandAverages)

    if ismember('MAP_Phase_CircularMean_rad', bandAverages.Properties.VariableNames)
        bandAverages = renamevars( ...
            bandAverages, ...
            'MAP_Phase_CircularMean_rad', ...
            'MAP_Phase_Wrapped_CircularMean_rad');
    end

    if ismember('CO2_Phase_CircularMean_rad', bandAverages.Properties.VariableNames)
        bandAverages = renamevars( ...
            bandAverages, ...
            'CO2_Phase_CircularMean_rad', ...
            'CO2_Phase_Wrapped_CircularMean_rad');
    end

end


function bandAverages = renameGainColumnsForDisplay(bandAverages)

    if ismember('MAP_Gain_Mean', bandAverages.Properties.VariableNames)
        bandAverages = renamevars( ...
            bandAverages, ...
            'MAP_Gain_Mean', ...
            'MAP_Gain_Mean_pctCBV_per_mmHg');
    end

    if ismember('CO2_Gain_Mean', bandAverages.Properties.VariableNames)
        bandAverages = renamevars( ...
            bandAverages, ...
            'CO2_Gain_Mean', ...
            'CO2_Gain_Mean_pctCBV_per_mmHgCO2');
    end

end
