function metrics = batchMetricDefinitions(modelName, resolution)
% batchMetricDefinitions Define the metrics written to batch workbooks.

    if resolution == "full"
        if modelName == "miso"
            metrics = struct( ...
                'name', { ...
                    "MAP_Power", "CO2_Power", "CBV_Power", ...
                    "MAP_Gain", "MAP_PhW", "MAP_PhU", ...
                    "CO2_Gain", "CO2_PhW", "CO2_PhU", ...
                    "MultCoh", "MAP_PartCoh", "CO2_PartCoh", ...
                    "Unexplained", "Residual", "CondNum", ...
                    "InputCoh", "Input_PhW"}, ...
                'field', { ...
                    "map.power", "co2.power", "cbv.power", ...
                    "map.gain", "map.phase.wrapped", ...
                    "map.phase.unwrapped", "co2.gain", ...
                    "co2.phase.wrapped", "co2.phase.unwrapped", ...
                    "system.multipleCoherence", ...
                    "map.coherence.partial", "co2.coherence.partial", ...
                    "system.unexplainedFraction", ...
                    "system.residualPower", ...
                    "diagnostics.conditionNumber", ...
                    "inputRelationship.coherence", ...
                    "inputRelationship.phase.wrapped"}, ...
                'valuesField', { ...
                    "valuesDb", "valuesDb", "valuesDb", ...
                    "values", "values", "values", ...
                    "values", "values", "values", ...
                    "values", "values", "values", ...
                    "values", "values", "values", ...
                    "values", "values"}, ...
                'meanField', { ...
                    "meanDb", "meanDb", "meanDb", ...
                    "mean", "mean", "mean", ...
                    "mean", "mean", "mean", ...
                    "mean", "mean", "mean", ...
                    "mean", "mean", "mean", ...
                    "mean", "mean"}, ...
                'sdField', { ...
                    "sdDb", "sdDb", "sdDb", ...
                    "sd", "sd", "sd", ...
                    "sd", "sd", "sd", ...
                    "sd", "sd", "sd", ...
                    "sd", "sd", "sd", ...
                    "sd", "sd"});
        else
            metrics = struct( ...
                'name', { ...
                    "MAP_Power", "CO2_Power", "CBV_Power", ...
                    "MAP_Gain", "MAP_PhW", "MAP_PhU", ...
                    "CO2_Gain", "CO2_PhW", "CO2_PhU", ...
                    "MAP_Coh", "CO2_Coh", ...
                    "MAP_Unexplained", "MAP_Residual", ...
                    "CO2_Unexplained", "CO2_Residual", ...
                    "InputCoh", "Input_PhW"}, ...
                'field', { ...
                    "map.power", "co2.power", "cbv.power", ...
                    "map.gain", "map.phase.wrapped", ...
                    "map.phase.unwrapped", "co2.gain", ...
                    "co2.phase.wrapped", "co2.phase.unwrapped", ...
                    "map.coherence.pairwise", "co2.coherence.pairwise", ...
                    "map.unexplainedFraction", "map.residualPower", ...
                    "co2.unexplainedFraction", "co2.residualPower", ...
                    "inputRelationship.coherence", ...
                    "inputRelationship.phase.wrapped"}, ...
                'valuesField', { ...
                    "valuesDb", "valuesDb", "valuesDb", ...
                    "values", "values", "values", ...
                    "values", "values", "values", ...
                    "values", "values", "values", "values", ...
                    "values", "values", "values", "values"}, ...
                'meanField', { ...
                    "meanDb", "meanDb", "meanDb", ...
                    "mean", "mean", "mean", ...
                    "mean", "mean", "mean", ...
                    "mean", "mean", "mean", "mean", ...
                    "mean", "mean", "mean", "mean"}, ...
                'sdField', { ...
                    "sdDb", "sdDb", "sdDb", ...
                    "sd", "sd", "sd", ...
                    "sd", "sd", "sd", ...
                    "sd", "sd", "sd", "sd", ...
                    "sd", "sd", "sd", "sd"});
        end
        return
    end

    if modelName == "miso"
        metrics = struct( ...
            'name', { ...
                "MAP_Gain", "MAP_PhW", "MAP_PhU", ...
                "CO2_Gain", "CO2_PhW", "CO2_PhU", ...
                "MultCoh", "MAP_PartCoh", "CO2_PartCoh", ...
                "Pct_MultCoh", "Pct_MAPPartCoh", "Pct_CO2PartCoh"}, ...
            'field', { ...
                "MAP_Gain_Mean", "MAP_Phase_CircularMean_rad", ...
                "MAP_Phase_Unwrapped_Mean_rad", ...
                "CO2_Gain_Mean", "CO2_Phase_CircularMean_rad", ...
                "CO2_Phase_Unwrapped_Mean_rad", ...
                "Multiple_Coh_Mean", "Partial_Coh_MAP_Mean", ...
                "Partial_Coh_CO2_Mean", ...
                "Percent_Passed_Multiple_Coh", ...
                "Percent_Passed_Partial_MAP_Coh", ...
                "Percent_Passed_Partial_CO2_Coh"}, ...
            'wrappedField', { ...
                "", "MAP_Phase_CircularMean_rad", ...
                "MAP_Phase_CircularMean_rad", ...
                "", "CO2_Phase_CircularMean_rad", ...
                "CO2_Phase_CircularMean_rad", ...
                "", "", "", "", "", ""}, ...
            'coherenceField', { ...
                "", "Partial_Coh_MAP_Mean", "Partial_Coh_MAP_Mean", ...
                "", "Partial_Coh_CO2_Mean", "Partial_Coh_CO2_Mean", ...
                "", "", "", "", "", ""}, ...
            'isPhase', { ...
                false, true, true, false, true, true, ...
                false, false, false, false, false, false}, ...
            'unwrapMean', { ...
                false, false, true, false, false, true, ...
                false, false, false, false, false, false});
    else
        metrics = struct( ...
            'name', { ...
                "MAP_Gain", "MAP_PhW", "MAP_PhU", ...
                "CO2_Gain", "CO2_PhW", "CO2_PhU", ...
                "MAP_Coh", "CO2_Coh", ...
                "Pct_MAPCoh", "Pct_CO2Coh"}, ...
            'field', { ...
                "MAP_Gain_Mean", "MAP_Phase_CircularMean_rad", ...
                "MAP_Phase_Unwrapped_Mean_rad", ...
                "CO2_Gain_Mean", "CO2_Phase_CircularMean_rad", ...
                "CO2_Phase_Unwrapped_Mean_rad", ...
                "MAP_CBV_Coh_Mean", "CO2_CBV_Coh_Mean", ...
                "Percent_Passed_MAP_CBV_Coh", ...
                "Percent_Passed_CO2_CBV_Coh"}, ...
            'wrappedField', { ...
                "", "MAP_Phase_CircularMean_rad", ...
                "MAP_Phase_CircularMean_rad", ...
                "", "CO2_Phase_CircularMean_rad", ...
                "CO2_Phase_CircularMean_rad", "", "", "", ""}, ...
            'coherenceField', { ...
                "", "MAP_CBV_Coh_Mean", "MAP_CBV_Coh_Mean", ...
                "", "CO2_CBV_Coh_Mean", "CO2_CBV_Coh_Mean", ...
                "", "", "", ""}, ...
            'isPhase', { ...
                false, true, true, false, true, true, ...
                false, false, false, false}, ...
            'unwrapMean', { ...
                false, false, true, false, false, true, ...
                false, false, false, false});
    end

end
