function comparisonTable = createModelComparisonTable(misoResults, sisoResults)
% createModelComparisonTable Compare subject-level MISO and SISO band results.

    variableNames = { ...
        'Band', 'Model', ...
        'MAP_Gain', 'MAP_Phase_Wrapped_rad', ...
        'MAP_Phase_Unwrapped_rad', ...
        'CO2_Gain', 'CO2_Phase_Wrapped_rad', ...
        'CO2_Phase_Unwrapped_rad', ...
        'Multiple_Coherence', ...
        'MAP_Coherence', 'CO2_Coherence', ...
        'Percent_Passed_Multiple_Coherence', ...
        'Percent_Passed_MAP_Coherence', ...
        'Percent_Passed_CO2_Coherence' ...
    };

    comparisonTable = table();

    if ~isempty(misoResults)
        misoBands = misoResults.bandAverages;
        numMisoBands = height(misoBands);
        comparisonTable = table( ...
            string(misoBands.Band), ...
            repmat("MISO", numMisoBands, 1), ...
            misoBands.MAP_Gain_Mean, ...
            misoBands.MAP_Phase_CircularMean_rad, ...
            misoBands.MAP_Phase_Unwrapped_Mean_rad, ...
            misoBands.CO2_Gain_Mean, ...
            misoBands.CO2_Phase_CircularMean_rad, ...
            misoBands.CO2_Phase_Unwrapped_Mean_rad, ...
            misoBands.Multiple_Coh_Mean, ...
            misoBands.Partial_Coh_MAP_Mean, ...
            misoBands.Partial_Coh_CO2_Mean, ...
            misoBands.Percent_Passed_Multiple_Coh, ...
            misoBands.Percent_Passed_Partial_MAP_Coh, ...
            misoBands.Percent_Passed_Partial_CO2_Coh, ...
            'VariableNames', variableNames);
    end

    if ~isempty(sisoResults)
        sisoBands = sisoResults.bandAverages;
        numSisoBands = height(sisoBands);
        sisoRows = table( ...
            string(sisoBands.Band), ...
            repmat("SISO", numSisoBands, 1), ...
            sisoBands.MAP_Gain_Mean, ...
            sisoBands.MAP_Phase_CircularMean_rad, ...
            sisoBands.MAP_Phase_Unwrapped_Mean_rad, ...
            sisoBands.CO2_Gain_Mean, ...
            sisoBands.CO2_Phase_CircularMean_rad, ...
            sisoBands.CO2_Phase_Unwrapped_Mean_rad, ...
            NaN(numSisoBands, 1), ...
            sisoBands.MAP_CBV_Coh_Mean, ...
            sisoBands.CO2_CBV_Coh_Mean, ...
            NaN(numSisoBands, 1), ...
            sisoBands.Percent_Passed_MAP_CBV_Coh, ...
            sisoBands.Percent_Passed_CO2_CBV_Coh, ...
            'VariableNames', variableNames);

        if isempty(comparisonTable)
            comparisonTable = sisoRows;
        else
            comparisonTable = [comparisonTable; sisoRows];
        end
    end

end
