function fullFrequencyTable = createMisoFullFrequencyTable( ...
    misoResults, frequencyBandEdgesHz, frequencyBandNames)
% createMisoFullFrequencyTable Organize one subject's MISO frequency results.

    f = misoResults.f(:);
    band = getFrequencyBandLabels( ...
        f, frequencyBandEdgesHz, frequencyBandNames);

    fullFrequencyTable = table( ...
        band, ...
        f, ...
        powerToDb(misoResults.map.power(:)), ...
        powerToDb(misoResults.co2.power(:)), ...
        powerToDb(misoResults.cbv.power(:)), ...
        misoResults.map.gain(:), ...
        misoResults.map.phase.wrapped(:), ...
        misoResults.map.phase.unwrapped(:), ...
        misoResults.co2.gain(:), ...
        misoResults.co2.phase.wrapped(:), ...
        misoResults.co2.phase.unwrapped(:), ...
        misoResults.map.coherence.partial(:), ...
        misoResults.co2.coherence.partial(:), ...
        misoResults.system.multipleCoherence(:), ...
        misoResults.inputRelationship.coherence(:), ...
        misoResults.inputRelationship.phase.wrapped(:), ...
        misoResults.diagnostics.conditionNumber(:), ...
        misoResults.system.unexplainedFraction(:), ...
        powerToDb(misoResults.system.residualPower(:)), ...
        'VariableNames', { ...
            'Band', ...
            'Frequency_Hz', ...
            'MAP_Power_dB', ...
            'CO2_Power_dB', ...
            'CBV_Power_dB', ...
            'MAP_Gain', ...
            'MAP_Phase_Wrapped_rad', ...
            'MAP_Phase_Unwrapped_rad', ...
            'CO2_Gain', ...
            'CO2_Phase_Wrapped_rad', ...
            'CO2_Phase_Unwrapped_rad', ...
            'MAP_Partial_Coherence', ...
            'CO2_Partial_Coherence', ...
            'Multiple_Coherence', ...
            'Input_Coherence', ...
            'Input_Phase_Wrapped_rad', ...
            'Condition_Number', ...
            'Unexplained_Fraction', ...
            'Residual_Power_dB' ...
        });

end
