function fullFrequencyTable = createSisoFullFrequencyTable( ...
    sisoResults, frequencyBandEdgesHz, frequencyBandNames)
% createSisoFullFrequencyTable Organize one subject's SISO frequency results.

    f = sisoResults.f(:);
    band = getFrequencyBandLabels( ...
        f, frequencyBandEdgesHz, frequencyBandNames);

    fullFrequencyTable = table( ...
        band, ...
        f, ...
        powerToDb(sisoResults.map.power(:)), ...
        powerToDb(sisoResults.co2.power(:)), ...
        powerToDb(sisoResults.cbv.power(:)), ...
        sisoResults.map.gain(:), ...
        sisoResults.map.phase.wrapped(:), ...
        sisoResults.map.phase.unwrapped(:), ...
        sisoResults.co2.gain(:), ...
        sisoResults.co2.phase.wrapped(:), ...
        sisoResults.co2.phase.unwrapped(:), ...
        sisoResults.map.coherence.pairwise(:), ...
        sisoResults.co2.coherence.pairwise(:), ...
        sisoResults.inputRelationship.coherence(:), ...
        sisoResults.inputRelationship.phase.wrapped(:), ...
        sisoResults.map.unexplainedFraction(:), ...
        powerToDb(sisoResults.map.residualPower(:)), ...
        sisoResults.co2.unexplainedFraction(:), ...
        powerToDb(sisoResults.co2.residualPower(:)), ...
        'VariableNames', { ...
            'Band', ...
            'Frequency_Hz', ...
            'MAP_Power_dB', ...
            'CO2_Power_dB', ...
            'CBV_Power_dB', ...
            'MAP_Gain', ...
            'MAP_Phase_Wrapped_rad', ...
            'MAP_Phase_Unwrapped_rad', ...
            'CO2_Gain', ...
            'CO2_Phase_Wrapped_rad', ...
            'CO2_Phase_Unwrapped_rad', ...
            'MAP_CBV_Coherence', ...
            'CO2_CBV_Coherence', ...
            'Input_Coherence', ...
            'Input_Phase_Wrapped_rad', ...
            'MAP_Unexplained_Fraction', ...
            'MAP_Residual_Power_dB', ...
            'CO2_Unexplained_Fraction', ...
            'CO2_Residual_Power_dB' ...
        });

end
