function saveDatatoExcel(filename, sheetName, tfaResults, frequencyBandEdgesHz, frequencyBandNames, subjectInfo)

headers = {
    "Band", ...
    "Frequency (Hz)", ...
    "MAP Power", ...
    "MAP Power Smoothed", ...
    "CO2 Power", ...
    "CO2 Power Smoothed", ...
    "CBV Percent Power", ...
    "CBV Percent Power Smoothed", ...
    "MAP to CBV Gain (%CBV/mmHg)", ...
    "MAP to CBV Wrapped Phase (rad)", ...
    "MAP to CBV Unwrapped Phase (rad)", ...
    "MAP to CBV Anchored Phase (rad)", ...
    "CO2 to CBV Gain (%CBV/mmHg CO2)", ...
    "CO2 to CBV Wrapped Phase (rad)", ...
    "CO2 to CBV Unwrapped Phase (rad)", ...
    "CO2 to CBV Anchored Phase (rad)", ...
    "Multiple Coherence", ...
    "Partial Coherence: MAP-CBV | CO2", ...
    "Partial Coherence: CO2-CBV | MAP", ...
    "Input-Input Coherence", ...
    "Input-Input Wrapped Phase (rad)", ...
    "Input-Input Unwrapped Phase (rad)", ...
    "Input-Input Anchored Phase (rad)", ...
    "Condition Number"
};

writecell(headers, filename, ...
    "Sheet", sheetName, ...
    "Range", "A1");

f = tfaResults.f(:);

bands = getFrequencyBands(f, frequencyBandEdgesHz, frequencyBandNames);

band = strings(size(f));

for k = 1:numel(frequencyBandNames)
    bandName = frequencyBandNames(k);
    bandField = lower(char(bandName));
    band(bands.(bandField).idx) = bandName;
end

writecell(cellstr(band), filename, ...
    "Sheet", sheetName, ...
    "Range", "A2");

data = [
    f, ...
    tfaResults.mapPower(:), ...
    tfaResults.mapPowerSmooth(:), ...
    tfaResults.co2Power(:), ...
    tfaResults.co2PowerSmooth(:), ...
    tfaResults.cbvPower(:), ...
    tfaResults.cbvPowerSmooth(:), ...
    tfaResults.mapCbvGain(:), ...
    tfaResults.mapCbvPhaseWrapped(:), ...
    tfaResults.mapCbvPhaseUnwrapped(:), ...
    tfaResults.mapCbvPhaseAnchored(:), ...
    tfaResults.co2CbvGain(:), ...
    tfaResults.co2CbvPhaseWrapped(:), ...
    tfaResults.co2CbvPhaseUnwrapped(:), ...
    tfaResults.co2CbvPhaseAnchored(:), ...
    tfaResults.multipleCoh(:), ...
    tfaResults.partialCohMap(:), ...
    tfaResults.partialCohCo2(:), ...
    tfaResults.inputInputCoh(:), ...
    tfaResults.inputInputPhaseWrapped(:), ...
    tfaResults.inputInputPhaseUnwrapped(:), ...
    tfaResults.inputInputPhaseAnchored(:), ...
    tfaResults.conditionNumber(:)
];

writematrix(data, filename, ...
    "Sheet", sheetName, ...
    "Range", "B2");


bandAverageStartRow = length(f) + 3;
bandAverages = addSubjectMetadataToBandAverages( ...
    tfaResults.bandAverages, tfaResults.welchInfo, subjectInfo);

writetable(bandAverages, filename, ...
    "Sheet", sheetName, ...
    "Range", "A" + bandAverageStartRow);

metadata = {
    "SubjectID", string(subjectInfo.subjectID);
    "Group", string(subjectInfo.group);
    "Session", string(subjectInfo.session);
    "SourceFile", string(subjectInfo.sourceFile);
    "WindowLengthSeconds", tfaResults.welchInfo.windowLengthSeconds;
    "WindowOverlap", tfaResults.welchInfo.windowOverlap;
    "NumWelchWindows", tfaResults.welchInfo.numWindows;
    "SignalDurationSeconds", tfaResults.welchInfo.signalDurationSeconds;
    "CBVBaseline_cm_per_s", valueFromWelchInfo(tfaResults.welchInfo, 'cbvBaselineCmPerSec', NaN);
    "CBVUnits", string(valueFromWelchInfo(tfaResults.welchInfo, 'cbvUnits', ""));
    "PhaseUnwrapMethod", string(valueFromResults(tfaResults, 'phaseUnwrapMethod', ""));
    "PhaseAnchorEnabled", valueFromPhaseSettings(tfaResults, {'anchor', 'enabled'}, false);
    "MAPAnchorBandHz", formatNumericVector(valueFromPhaseSettings(tfaResults, {'anchor', 'map', 'bandHz'}, [NaN NaN]));
    "MAPAnchorTargetRangeRad", formatNumericVector(valueFromPhaseSettings(tfaResults, {'anchor', 'map', 'targetRangeRad'}, [NaN NaN]));
    "CO2AnchorBandHz", formatNumericVector(valueFromPhaseSettings(tfaResults, {'anchor', 'co2', 'bandHz'}, [NaN NaN]));
    "CO2AnchorTargetRangeRad", formatNumericVector(valueFromPhaseSettings(tfaResults, {'anchor', 'co2', 'targetRangeRad'}, [NaN NaN]));
    "IsTooShortForWelch", tfaResults.welchInfo.isTooShort;
    "UsesDefaultCoherenceThreshold", tfaResults.welchInfo.usesDefaultCoherenceThreshold;
    "CoherenceThreshold", tfaResults.welchInfo.coherenceThreshold
};

writecell(metadata, filename, ...
    "Sheet", "Subject Metadata", ...
    "Range", "A1");

end


function value = valueFromResults(results, fieldName, defaultValue)

if isfield(results, fieldName)
    value = results.(fieldName);
else
    value = defaultValue;
end

end


function value = valueFromPhaseSettings(results, fieldPath, defaultValue)

if ~isfield(results, 'phaseSettings')
    value = defaultValue;
    return
end

value = results.phaseSettings;

for k = 1:numel(fieldPath)
    fieldName = fieldPath{k};

    if isstruct(value) && isfield(value, fieldName)
        value = value.(fieldName);
    else
        value = defaultValue;
        return
    end
end

end


function valueText = formatNumericVector(values)

values = values(:)';
valueText = strjoin(string(values), ",");

end


function value = valueFromWelchInfo(welchInfo, fieldName, defaultValue)

if isfield(welchInfo, fieldName)
    value = welchInfo.(fieldName);
else
    value = defaultValue;
end

end
