function saveSubjectOutputs( ...
    filename, ...
    subjectInfo, ...
    runStatus, ...
    tfaResults, ...
    sisoResults, ...
    outputSettings)

if exist(filename, "file")
    delete(filename);
end

statusSheetName = "Subject_" + subjectInfo.subjectID + "_Status";

saveSubjectRunStatusToExcel( ...
    filename, statusSheetName, subjectInfo, runStatus);

if ~runStatus.analysisSucceeded
    return
end

misoBandSheetName = "Subject_" + subjectInfo.subjectID + "_MISO_Bands";

saveMISOBandAveragesToExcel( ...
    filename, misoBandSheetName, tfaResults, subjectInfo);

if outputSettings.runSISO
    sisoBandSheetName = "Subject_" + subjectInfo.subjectID + "_SISO_Bands";
    comparisonSheetName = "Subject_" + subjectInfo.subjectID + "_Compare";

    saveSISOBandAveragesToExcel( ...
        filename, sisoBandSheetName, sisoResults, subjectInfo);

    saveModelComparisonToExcel( ...
        filename, comparisonSheetName, ...
        tfaResults, sisoResults, subjectInfo);
end

if outputSettings.saveFullFrequencyData
    misoFullSheetName = "Subject_" + subjectInfo.subjectID + "_MISO_Full";

    saveDatatoExcel( ...
        filename, misoFullSheetName, tfaResults, ...
        outputSettings.frequencyBandEdgesHz, ...
        outputSettings.frequencyBandNames, ...
        subjectInfo);

    if outputSettings.runSISO
        sisoFullSheetName = "Subject_" + subjectInfo.subjectID + "_SISO_Full";

        saveSISODataToExcel( ...
            filename, sisoFullSheetName, sisoResults, ...
            outputSettings.frequencyBandEdgesHz, ...
            outputSettings.frequencyBandNames, ...
            subjectInfo);
    end
end

end
