function saveDatatoExcel(filename, sheetName, tfaResults, frequencyBandEdgesHz, frequencyBandNames, subjectInfo)

headers = {
    "Band", ...
    "Frequency (Hz)", ...
    "MAP Power", ...
    "MAP Power Smoothed", ...
    "CO2 Power", ...
    "CO2 Power Smoothed", ...
    "CBV Power", ...
    "CBV Power Smoothed", ...
    "MAP to CBV Gain", ...
    "MAP to CBV Phase (rad)", ...
    "CO2 to CBV Gain", ...
    "CO2 to CBV Phase (rad)", ...
    "Multiple Coherence", ...
    "Partial Coherence: MAP-CBV | CO2", ...
    "Partial Coherence: CO2-CBV | MAP", ...
    "Input-Input Coherence", ...
    "Input-Input Phase (rad)", ...
    "Condition Number"
};

writecell(headers, filename, ...
    "Sheet", sheetName, ...
    "Range", "A1");

f = tfaResults.f(:);

bands = getFrequencyBands(f, frequencyBandEdgesHz, frequencyBandNames);

band = strings(size(f));

for k = 1:numel(frequencyBandNames)
    bandName = frequencyBandNames(k);
    bandField = lower(char(bandName));
    band(bands.(bandField).idx) = bandName;
end

writecell(cellstr(band), filename, ...
    "Sheet", sheetName, ...
    "Range", "A2");

data = [
    f, ...
    tfaResults.mapPower(:), ...
    tfaResults.mapPowerSmooth(:), ...
    tfaResults.co2Power(:), ...
    tfaResults.co2PowerSmooth(:), ...
    tfaResults.cbvPower(:), ...
    tfaResults.cbvPowerSmooth(:), ...
    tfaResults.mapCbvGain(:), ...
    tfaResults.mapCbvPhase(:), ...
    tfaResults.co2CbvGain(:), ...
    tfaResults.co2CbvPhase(:), ...
    tfaResults.multipleCoh(:), ...
    tfaResults.partialCohMap(:), ...
    tfaResults.partialCohCo2(:), ...
    tfaResults.inputInputCoh(:), ...
    tfaResults.inputInputPhase(:), ...
    tfaResults.conditionNumber(:)
];

writematrix(data, filename, ...
    "Sheet", sheetName, ...
    "Range", "B2");


bandAverageStartRow = length(f) + 3;
bandAverages = addSubjectMetadataToBandAverages( ...
    tfaResults.bandAverages, tfaResults.welchInfo, subjectInfo);

writetable(bandAverages, filename, ...
    "Sheet", sheetName, ...
    "Range", "A" + bandAverageStartRow);

metadata = {
    "SubjectID", string(subjectInfo.subjectID);
    "Group", string(subjectInfo.group);
    "Session", string(subjectInfo.session);
    "SourceFile", string(subjectInfo.sourceFile);
    "WindowLengthSeconds", tfaResults.welchInfo.windowLengthSeconds;
    "WindowOverlap", tfaResults.welchInfo.windowOverlap;
    "NumWelchWindows", tfaResults.welchInfo.numWindows;
    "SignalDurationSeconds", tfaResults.welchInfo.signalDurationSeconds;
    "IsTooShortForWelch", tfaResults.welchInfo.isTooShort;
    "UsesDefaultCoherenceThreshold", tfaResults.welchInfo.usesDefaultCoherenceThreshold;
    "CoherenceThreshold", tfaResults.welchInfo.coherenceThreshold
};

writecell(metadata, filename, ...
    "Sheet", "Subject Metadata", ...
    "Range", "A1");

end
