function saveSISODataToExcel(filename, sheetName, sisoResults, frequencyBandEdgesHz, frequencyBandNames, subjectInfo)

headers = {
    "Band", ...
    "Frequency (Hz)", ...
    "MAP Power", ...
    "MAP Power Smoothed", ...
    "CO2 Power", ...
    "CO2 Power Smoothed", ...
    "CBV Power", ...
    "CBV Power Smoothed", ...
    "MAP to CBV Gain", ...
    "MAP to CBV Phase (rad)", ...
    "CO2 to CBV Gain", ...
    "CO2 to CBV Phase (rad)", ...
    "MAP-CBV Coherence", ...
    "CO2-CBV Coherence"
};

writecell(headers, filename, ...
    "Sheet", sheetName, ...
    "Range", "A1");

f = sisoResults.f(:);

bands = getFrequencyBands(f, frequencyBandEdgesHz, frequencyBandNames);

band = strings(size(f));

for k = 1:numel(frequencyBandNames)
    bandName = frequencyBandNames(k);
    bandField = lower(char(bandName));
    band(bands.(bandField).idx) = bandName;
end

writecell(cellstr(band), filename, ...
    "Sheet", sheetName, ...
    "Range", "A2");

data = [
    f, ...
    sisoResults.mapPower(:), ...
    sisoResults.mapPowerSmooth(:), ...
    sisoResults.co2Power(:), ...
    sisoResults.co2PowerSmooth(:), ...
    sisoResults.cbvPower(:), ...
    sisoResults.cbvPowerSmooth(:), ...
    sisoResults.mapCbvGain(:), ...
    sisoResults.mapCbvPhase(:), ...
    sisoResults.co2CbvGain(:), ...
    sisoResults.co2CbvPhase(:), ...
    sisoResults.mapCbvCoh(:), ...
    sisoResults.co2CbvCoh(:)
];

writematrix(data, filename, ...
    "Sheet", sheetName, ...
    "Range", "B2");

bandAverageStartRow = length(f) + 3;
bandAverages = addSubjectMetadataToBandAverages( ...
    sisoResults.bandAverages, sisoResults.welchInfo, subjectInfo);

writetable(bandAverages, filename, ...
    "Sheet", sheetName, ...
    "Range", "A" + bandAverageStartRow);

end
