function bandAverages = computeSISOBandAverages( ...
    f, ...
    H_mapcbv, ...
    H_co2cbv, ...
    mapCbvCoherence, ...
    co2CbvCoherence, ...
    coherenceThreshold, ...
    frequencyBandEdgesHz, ...
    frequencyBandNames, ...
    phaseSettings)
% computeSISOBandAverages
%
% Computes unfiltered band averages for SISO TFA results.
%
% Frequency bands are passed in from the analysis settings.
%
% Phase values are averaged using a circular mean.

    if nargin < 9
        phaseSettings = defaultPhaseSettings();
    end

    phaseSettings = normalizePhaseSettings(phaseSettings);

    f = f(:);

    bands = getFrequencyBands(f, frequencyBandEdgesHz, frequencyBandNames);

    bandNames = frequencyBandNames(:);
    numBands = numel(bandNames);

    bandMasks = cell(numBands,1);
    for b = 1:numBands
        bandName = lower(char(bandNames(b)));
        bandMasks{b} = bands.(bandName).idx;
    end

    % Preallocate
    mapGainMean = NaN(numBands,1);
    mapPhaseMean = NaN(numBands,1);
    mapPhaseUnwrappedMean = NaN(numBands,1);
    mapPhaseAnchoredMean = NaN(numBands,1);

    co2GainMean = NaN(numBands,1);
    co2PhaseMean = NaN(numBands,1);
    co2PhaseUnwrappedMean = NaN(numBands,1);
    co2PhaseAnchoredMean = NaN(numBands,1);

    mapCbvCohMean = NaN(numBands,1);
    co2CbvCohMean = NaN(numBands,1);

    percentPassedMapCbvCoh = NaN(numBands,1);
    percentPassedCo2CbvCoh = NaN(numBands,1);
    mapPhaseData = computePhaseRepresentations( ...
        H_mapcbv, f, mapCbvCoherence, coherenceThreshold, phaseSettings, "map");
    co2PhaseData = computePhaseRepresentations( ...
        H_co2cbv, f, co2CbvCoherence, coherenceThreshold, phaseSettings, "co2");

    for b = 1:numBands

        mask = bandMasks{b};

        % MAP -> CBV transfer function summaries
        mapGainMean(b) = mean(abs(H_mapcbv(mask)), 'omitnan');
        mapPhaseMean(b) = circularMeanPhase(mapPhaseData.wrapped(mask));
        mapPhaseUnwrappedMean(b) = mean(mapPhaseData.unwrapped(mask), 'omitnan');
        mapPhaseAnchoredMean(b) = mean(mapPhaseData.anchored(mask), 'omitnan');

        % CO2 -> CBV transfer function summaries
        co2GainMean(b) = mean(abs(H_co2cbv(mask)), 'omitnan');
        co2PhaseMean(b) = circularMeanPhase(co2PhaseData.wrapped(mask));
        co2PhaseUnwrappedMean(b) = mean(co2PhaseData.unwrapped(mask), 'omitnan');
        co2PhaseAnchoredMean(b) = mean(co2PhaseData.anchored(mask), 'omitnan');

        % Coherence summaries
        mapCbvCohMean(b) = mean(mapCbvCoherence(mask), 'omitnan');
        co2CbvCohMean(b) = mean(co2CbvCoherence(mask), 'omitnan');

        % Percent passed coherence threshold
        percentPassedMapCbvCoh(b) = ...
            100 * mean(mapCbvCoherence(mask) >= coherenceThreshold, 'omitnan');

        percentPassedCo2CbvCoh(b) = ...
            100 * mean(co2CbvCoherence(mask) >= coherenceThreshold, 'omitnan');

    end

    bandAverages = table( ...
    bandNames, ...
    mapGainMean, ...
    mapPhaseMean, ...
    co2GainMean, ...
    co2PhaseMean, ...
    mapPhaseUnwrappedMean, ...
    mapPhaseAnchoredMean, ...
    co2PhaseUnwrappedMean, ...
    co2PhaseAnchoredMean, ...
    mapCbvCohMean, ...
    co2CbvCohMean, ...
    percentPassedMapCbvCoh, ...
    percentPassedCo2CbvCoh, ...
    'VariableNames', { ...
        'Band', ...
        'MAP_Gain_Mean', ...
        'MAP_Phase_CircularMean_rad', ...
        'CO2_Gain_Mean', ...
        'CO2_Phase_CircularMean_rad', ...
        'MAP_Phase_Unwrapped_Mean_rad', ...
        'MAP_Phase_Anchored_Mean_rad', ...
        'CO2_Phase_Unwrapped_Mean_rad', ...
        'CO2_Phase_Anchored_Mean_rad', ...
        'MAP_CBV_Coh_Mean', ...
        'CO2_CBV_Coh_Mean', ...
        'Percent_Passed_MAP_CBV_Coh', ...
        'Percent_Passed_CO2_CBV_Coh' ...
    });

end
