function bandAverages = computeMISOBandAverages( ...
    f, ...
    H_mapcbv, ...
    H_co2cbv, ...
    multipleCoherence, ...
    partialCohMapCbvGivenCo2, ...
    partialCohCo2CbvGivenMap, ...
    coherenceThreshold, ...
    frequencyBandEdgesHz, ...
    frequencyBandNames, ...
    phaseSettings)
% computeMISOBandAverages
%
% Computes unfiltered band averages for MISO TFA results.
%
% Frequency bands are passed in from the analysis settings.
%
% Phase values are averaged using a circular mean.

    if nargin < 11
        phaseSettings = defaultPhaseSettings();
    end

    phaseSettings = normalizePhaseSettings(phaseSettings);

    f = f(:);

    bands = getFrequencyBands(f, frequencyBandEdgesHz, frequencyBandNames);

    bandNames = frequencyBandNames(:);
    numBands = numel(bandNames);

    bandMasks = cell(numBands,1);
    for b = 1:numBands
        bandName = lower(char(bandNames(b)));
        bandMasks{b} = bands.(bandName).idx;
    end

    % Preallocate
    mapGainMean = NaN(numBands,1);
    mapPhaseMean = NaN(numBands,1);
    mapPhaseUnwrappedMean = NaN(numBands,1);
    mapPhaseAnchoredMean = NaN(numBands,1);

    co2GainMean = NaN(numBands,1);
    co2PhaseMean = NaN(numBands,1);
    co2PhaseUnwrappedMean = NaN(numBands,1);
    co2PhaseAnchoredMean = NaN(numBands,1);

    multipleCohMean = NaN(numBands,1);
    partialCohMapMean = NaN(numBands,1);
    partialCohCo2Mean = NaN(numBands,1);

    percentPassedMultipleCoh = NaN(numBands,1);
    percentPassedPartialMapCoh = NaN(numBands,1);
    percentPassedPartialCo2Coh = NaN(numBands,1);
    mapPhaseData = computePhaseRepresentations( ...
        H_mapcbv, f, partialCohMapCbvGivenCo2, coherenceThreshold, ...
        phaseSettings, "map");
    co2PhaseData = computePhaseRepresentations( ...
        H_co2cbv, f, partialCohCo2CbvGivenMap, coherenceThreshold, ...
        phaseSettings, "co2");

    for b = 1:numBands

        mask = bandMasks{b};

        % MAP -> CBV transfer function summaries
        mapGainMean(b) = mean(abs(H_mapcbv(mask)), 'omitnan');
        mapPhaseMean(b) = circularMeanPhase(mapPhaseData.wrapped(mask));
        mapPhaseUnwrappedMean(b) = mean(mapPhaseData.unwrapped(mask), 'omitnan');
        mapPhaseAnchoredMean(b) = mean(mapPhaseData.anchored(mask), 'omitnan');

        % CO2 -> CBV transfer function summaries
        co2GainMean(b) = mean(abs(H_co2cbv(mask)), 'omitnan');
        co2PhaseMean(b) = circularMeanPhase(co2PhaseData.wrapped(mask));
        co2PhaseUnwrappedMean(b) = mean(co2PhaseData.unwrapped(mask), 'omitnan');
        co2PhaseAnchoredMean(b) = mean(co2PhaseData.anchored(mask), 'omitnan');

        % Coherence summaries
        multipleCohMean(b) = mean(multipleCoherence(mask), 'omitnan');
        partialCohMapMean(b) = mean(partialCohMapCbvGivenCo2(mask), 'omitnan');
        partialCohCo2Mean(b) = mean(partialCohCo2CbvGivenMap(mask), 'omitnan');

        % Percent passed coherence threshold
        percentPassedMultipleCoh(b) = ...
            100 * mean(multipleCoherence(mask) >= coherenceThreshold, 'omitnan');

        percentPassedPartialMapCoh(b) = ...
            100 * mean(partialCohMapCbvGivenCo2(mask) >= coherenceThreshold, 'omitnan');

        percentPassedPartialCo2Coh(b) = ...
            100 * mean(partialCohCo2CbvGivenMap(mask) >= coherenceThreshold, 'omitnan');

    end

    bandAverages = table( ...
    bandNames, ...
    mapGainMean, ...
    mapPhaseMean, ...
    co2GainMean, ...
    co2PhaseMean, ...
    mapPhaseUnwrappedMean, ...
    mapPhaseAnchoredMean, ...
    co2PhaseUnwrappedMean, ...
    co2PhaseAnchoredMean, ...
    multipleCohMean, ...
    partialCohMapMean, ...
    partialCohCo2Mean, ...
    percentPassedMultipleCoh, ...
    percentPassedPartialMapCoh, ...
    percentPassedPartialCo2Coh, ...
    'VariableNames', { ...
        'Band', ...
        'MAP_Gain_Mean', ...
        'MAP_Phase_CircularMean_rad', ...
        'CO2_Gain_Mean', ...
        'CO2_Phase_CircularMean_rad', ...
        'MAP_Phase_Unwrapped_Mean_rad', ...
        'MAP_Phase_Anchored_Mean_rad', ...
        'CO2_Phase_Unwrapped_Mean_rad', ...
        'CO2_Phase_Anchored_Mean_rad', ...
        'Multiple_Coh_Mean', ...
        'Partial_Coh_MAP_Mean', ...
        'Partial_Coh_CO2_Mean', ...
        'Percent_Passed_Multiple_Coh', ...
        'Percent_Passed_Partial_MAP_Coh', ...
        'Percent_Passed_Partial_CO2_Coh' ...
    });

end
