function bandAverages = computeSISOBandAverages( ...
    f, ...
    H_mapcbv, ...
    H_co2cbv, ...
    mapCbvCoherence, ...
    co2CbvCoherence, ...
    coherenceThreshold, ...
    frequencyBandEdgesHz, ...
    frequencyBandNames)
% computeSISOBandAverages
%
% Computes unfiltered band averages for SISO TFA results.
%
% Frequency bands are passed in from the analysis settings.
%
% Phase values are averaged using a circular mean.

    f = f(:);

    bands = getFrequencyBands(f, frequencyBandEdgesHz, frequencyBandNames);

    bandNames = frequencyBandNames(:);
    numBands = numel(bandNames);

    bandMasks = cell(numBands,1);
    for b = 1:numBands
        bandName = lower(char(bandNames(b)));
        bandMasks{b} = bands.(bandName).idx;
    end

    % Preallocate
    mapGainMean = NaN(numBands,1);
    mapPhaseMean = NaN(numBands,1);

    co2GainMean = NaN(numBands,1);
    co2PhaseMean = NaN(numBands,1);

    mapCbvCohMean = NaN(numBands,1);
    co2CbvCohMean = NaN(numBands,1);

    percentPassedMapCbvCoh = NaN(numBands,1);
    percentPassedCo2CbvCoh = NaN(numBands,1);

    for b = 1:numBands

        mask = bandMasks{b};

        % MAP -> CBV transfer function summaries
        mapGainMean(b) = mean(abs(H_mapcbv(mask)), 'omitnan');
        mapPhaseMean(b) = circularMeanPhase(angle(H_mapcbv(mask)));

        % CO2 -> CBV transfer function summaries
        co2GainMean(b) = mean(abs(H_co2cbv(mask)), 'omitnan');
        co2PhaseMean(b) = circularMeanPhase(angle(H_co2cbv(mask)));

        % Coherence summaries
        mapCbvCohMean(b) = mean(mapCbvCoherence(mask), 'omitnan');
        co2CbvCohMean(b) = mean(co2CbvCoherence(mask), 'omitnan');

        % Percent passed coherence threshold
        percentPassedMapCbvCoh(b) = ...
            100 * mean(mapCbvCoherence(mask) >= coherenceThreshold, 'omitnan');

        percentPassedCo2CbvCoh(b) = ...
            100 * mean(co2CbvCoherence(mask) >= coherenceThreshold, 'omitnan');

    end

    bandAverages = table( ...
    bandNames, ...
    mapGainMean, ...
    mapPhaseMean, ...
    co2GainMean, ...
    co2PhaseMean, ...
    mapCbvCohMean, ...
    co2CbvCohMean, ...
    percentPassedMapCbvCoh, ...
    percentPassedCo2CbvCoh, ...
    'VariableNames', { ...
        'Band', ...
        'MAP_Gain_Mean', ...
        'MAP_Phase_CircularMean_rad', ...
        'CO2_Gain_Mean', ...
        'CO2_Phase_CircularMean_rad', ...
        'MAP_CBV_Coh_Mean', ...
        'CO2_CBV_Coh_Mean', ...
        'Percent_Passed_MAP_CBV_Coh', ...
        'Percent_Passed_CO2_CBV_Coh' ...
    });

end
