function bandAverages = computeSISOBandAverages( ...
    sisoResults, frequencyBandEdgesHz, frequencyBandNames)
% computeSISOBandAverages Summarize stored SISO results by frequency band.

    f = sisoResults.f(:);
    coherenceThreshold = sisoResults.welchInfo.coherenceThreshold;
    bands = getFrequencyBands(f, frequencyBandEdgesHz, frequencyBandNames);

    bandNames = frequencyBandNames(:);
    numBands = numel(bandNames);
    mapGainMean = NaN(numBands, 1);
    mapPhaseMean = NaN(numBands, 1);
    mapPhaseUnwrappedMean = NaN(numBands, 1);
    co2GainMean = NaN(numBands, 1);
    co2PhaseMean = NaN(numBands, 1);
    co2PhaseUnwrappedMean = NaN(numBands, 1);
    mapCbvCohMean = NaN(numBands, 1);
    co2CbvCohMean = NaN(numBands, 1);
    percentPassedMapCbvCoh = NaN(numBands, 1);
    percentPassedCo2CbvCoh = NaN(numBands, 1);

    for b = 1:numBands
        bandName = lower(char(bandNames(b)));
        mask = bands.(bandName).idx;

        mapGainMean(b) = mean(sisoResults.map.gain(mask), 'omitnan');
        mapPhaseMean(b) = circularMeanPhase( ...
            sisoResults.map.phase.wrapped(mask));
        mapPhaseUnwrappedMean(b) = mean( ...
            sisoResults.map.phase.unwrapped(mask), 'omitnan');

        co2GainMean(b) = mean(sisoResults.co2.gain(mask), 'omitnan');
        co2PhaseMean(b) = circularMeanPhase( ...
            sisoResults.co2.phase.wrapped(mask));
        co2PhaseUnwrappedMean(b) = mean( ...
            sisoResults.co2.phase.unwrapped(mask), 'omitnan');

        mapCbvCohMean(b) = mean( ...
            sisoResults.map.coherence.pairwise(mask), 'omitnan');
        co2CbvCohMean(b) = mean( ...
            sisoResults.co2.coherence.pairwise(mask), 'omitnan');

        percentPassedMapCbvCoh(b) = 100*mean( ...
            sisoResults.map.coherence.pairwise(mask) >= coherenceThreshold, ...
            'omitnan');
        percentPassedCo2CbvCoh(b) = 100*mean( ...
            sisoResults.co2.coherence.pairwise(mask) >= coherenceThreshold, ...
            'omitnan');
    end

    bandAverages = table( ...
        bandNames, ...
        mapGainMean, ...
        mapPhaseMean, ...
        mapPhaseUnwrappedMean, ...
        co2GainMean, ...
        co2PhaseMean, ...
        co2PhaseUnwrappedMean, ...
        mapCbvCohMean, ...
        co2CbvCohMean, ...
        percentPassedMapCbvCoh, ...
        percentPassedCo2CbvCoh, ...
        'VariableNames', { ...
            'Band', ...
            'MAP_Gain_Mean', ...
            'MAP_Phase_CircularMean_rad', ...
            'MAP_Phase_Unwrapped_Mean_rad', ...
            'CO2_Gain_Mean', ...
            'CO2_Phase_CircularMean_rad', ...
            'CO2_Phase_Unwrapped_Mean_rad', ...
            'MAP_CBV_Coh_Mean', ...
            'CO2_CBV_Coh_Mean', ...
            'Percent_Passed_MAP_CBV_Coh', ...
            'Percent_Passed_CO2_CBV_Coh' ...
        });

end
