function bandAverages = computeMISOBandAverages( ...
    misoResults, frequencyBandEdgesHz, frequencyBandNames)
% computeMISOBandAverages Summarize stored MISO results by frequency band.

    f = misoResults.f(:);
    coherenceThreshold = misoResults.welchInfo.coherenceThreshold;
    bands = getFrequencyBands(f, frequencyBandEdgesHz, frequencyBandNames);

    bandNames = frequencyBandNames(:);
    numBands = numel(bandNames);
    mapGainMean = NaN(numBands, 1);
    mapPhaseMean = NaN(numBands, 1);
    mapPhaseUnwrappedMean = NaN(numBands, 1);
    co2GainMean = NaN(numBands, 1);
    co2PhaseMean = NaN(numBands, 1);
    co2PhaseUnwrappedMean = NaN(numBands, 1);
    multipleCohMean = NaN(numBands, 1);
    partialCohMapMean = NaN(numBands, 1);
    partialCohCo2Mean = NaN(numBands, 1);
    percentPassedMultipleCoh = NaN(numBands, 1);
    percentPassedPartialMapCoh = NaN(numBands, 1);
    percentPassedPartialCo2Coh = NaN(numBands, 1);

    for b = 1:numBands
        bandName = lower(char(bandNames(b)));
        mask = bands.(bandName).idx;

        mapGainMean(b) = mean(misoResults.map.gain(mask), 'omitnan');
        mapPhaseMean(b) = circularMeanPhase( ...
            misoResults.map.phase.wrapped(mask));
        mapPhaseUnwrappedMean(b) = mean( ...
            misoResults.map.phase.unwrapped(mask), 'omitnan');

        co2GainMean(b) = mean(misoResults.co2.gain(mask), 'omitnan');
        co2PhaseMean(b) = circularMeanPhase( ...
            misoResults.co2.phase.wrapped(mask));
        co2PhaseUnwrappedMean(b) = mean( ...
            misoResults.co2.phase.unwrapped(mask), 'omitnan');

        multipleCohMean(b) = mean( ...
            misoResults.system.multipleCoherence(mask), 'omitnan');
        partialCohMapMean(b) = mean( ...
            misoResults.map.coherence.partial(mask), 'omitnan');
        partialCohCo2Mean(b) = mean( ...
            misoResults.co2.coherence.partial(mask), 'omitnan');

        percentPassedMultipleCoh(b) = 100*mean( ...
            misoResults.system.multipleCoherence(mask) >= coherenceThreshold, ...
            'omitnan');
        percentPassedPartialMapCoh(b) = 100*mean( ...
            misoResults.map.coherence.partial(mask) >= coherenceThreshold, ...
            'omitnan');
        percentPassedPartialCo2Coh(b) = 100*mean( ...
            misoResults.co2.coherence.partial(mask) >= coherenceThreshold, ...
            'omitnan');
    end

    bandAverages = table( ...
        bandNames, ...
        mapGainMean, ...
        mapPhaseMean, ...
        mapPhaseUnwrappedMean, ...
        co2GainMean, ...
        co2PhaseMean, ...
        co2PhaseUnwrappedMean, ...
        multipleCohMean, ...
        partialCohMapMean, ...
        partialCohCo2Mean, ...
        percentPassedMultipleCoh, ...
        percentPassedPartialMapCoh, ...
        percentPassedPartialCo2Coh, ...
        'VariableNames', { ...
            'Band', ...
            'MAP_Gain_Mean', ...
            'MAP_Phase_CircularMean_rad', ...
            'MAP_Phase_Unwrapped_Mean_rad', ...
            'CO2_Gain_Mean', ...
            'CO2_Phase_CircularMean_rad', ...
            'CO2_Phase_Unwrapped_Mean_rad', ...
            'Multiple_Coh_Mean', ...
            'Partial_Coh_MAP_Mean', ...
            'Partial_Coh_CO2_Mean', ...
            'Percent_Passed_Multiple_Coh', ...
            'Percent_Passed_Partial_MAP_Coh', ...
            'Percent_Passed_Partial_CO2_Coh' ...
        });

end
