function comparison = runModelComparisonForSignals( ...
    map, co2, cbv, samplingFrequencyHz, analysisSettings, solverSettings)
% runModelComparisonForSignals Refit SISO and MISO after a signal change.

    if nargin < 6
        solverSettings = analysisSettings.misoSolver;
    end

    [~, welchInfo] = getWelchWindowSettings( ...
        analysisSettings.pwelch, samplingFrequencyHz, numel(map));
    if ~welchInfo.isReadyForTFA
        error( ...
            "TFA:RobustnessInsufficientWelchWindows", ...
            ['This robustness condition leaves %d Welch windows, but %d ' ...
             'are required.'], ...
            welchInfo.numWindows, welchInfo.minimumWindows);
    end

    spectra = estimateWelchSpectra( ...
        map, co2, cbv, samplingFrequencyHz, ...
        analysisSettings.pwelch);
    miso = runMISOTFA( ...
        spectra, analysisSettings.phase, solverSettings);
    siso = runSISOTFA(spectra, analysisSettings.phase);

    comparison.spectra = spectra;
    comparison.miso = limitResultsToFrequencyRange( ...
        miso, "miso", analysisSettings.frequencyRangeHz);
    comparison.siso = limitResultsToFrequencyRange( ...
        siso, "siso", analysisSettings.frequencyRangeHz);

end
