function runResults = runTFA( ...
    runType, subjectInfo, batchSettings, analysisSettings, outputSettings)
% runTFA Run a single, synthetic, or batch TFA analysis.

    %% Validate the Analysis and Build the Subject List

    runType = lower(string(runType));
    analysisSettings = validateTfaSettings(analysisSettings);
    isBatch = runType == "batch";
    isSynthetic = runType == "synthetic";

    if runType == "single"
        subjectList = table( ...
            string(subjectInfo.subjectID), ...
            string(subjectInfo.group), ...
            string(subjectInfo.sourceFile), ...
            'VariableNames', {'SubjectID', 'Group', 'SourceFile'});
    elseif isSynthetic
        subjectList = table( ...
            "synthetic", "Test", ...
            "Generated by createSyntheticSignal", ...
            'VariableNames', {'SubjectID', 'Group', 'SourceFile'});
    elseif isBatch
        subjectList = findIEEMSubjects( ...
            batchSettings.dataFolder, batchSettings.groupsToRun);
    else
        error('runType must be "single", "batch", or "synthetic".');
    end

    if isBatch && batchSettings.previewOnly
        runResults.runType = runType;
        runResults.subjectList = subjectList;
        runResults.previewTable = ...
            previewBatchReadiness(subjectList, analysisSettings);
        return
    end

    %% Prepare Output and Batch Counters

    if ~exist(outputSettings.baseOutputFolder, "dir")
        mkdir(outputSettings.baseOutputFolder);
    end

    if isBatch
        groupsToRun = upper(string(batchSettings.groupsToRun));
        groupsToRun = unique(groupsToRun(:), "stable");
    else
        groupsToRun = upper(unique(string(subjectList.Group), "stable"));
        groupsToRun = groupsToRun(:);
    end

    successfulSubjectCounts = table( ...
        groupsToRun, zeros(numel(groupsToRun), 1), ...
        'VariableNames', {'Group', 'SuccessfulSubjects'});
    subjectFigureCounts = table( ...
        groupsToRun, zeros(numel(groupsToRun), 1), ...
        'VariableNames', {'Group', 'SavedSubjectFigures'});

    targetSuccessfulSubjectCounts = Inf(numel(groupsToRun), 1);
    if ~isBatch
        targetSuccessfulSubjectCounts(:) = 1;
    else
        targetSuccessfulSubjectCounts(:) = ...
            batchSettings.targetSuccessfulSubjectsPerGroup;

        if ~isnumeric(targetSuccessfulSubjectCounts) || ...
                any(isnan(targetSuccessfulSubjectCounts)) || ...
                any(targetSuccessfulSubjectCounts < 0) || ...
                any(mod(targetSuccessfulSubjectCounts, 1) ~= 0 & ...
                    ~isinf(targetSuccessfulSubjectCounts))
            error( ...
                'TFA:InvalidSuccessfulSubjectTarget', ...
                ['targetSuccessfulSubjectsPerGroup must be a ' ...
                 'nonnegative integer or Inf.']);
        end
    end

    requestedPlotCount = Inf;
    if isBatch
        requestedPlotCount = batchSettings.numSubjectFiguresPerGroup;

        if ~isnumeric(requestedPlotCount)
            requestedPlotCount = lower(string(requestedPlotCount));

            if requestedPlotCount == "all"
                requestedPlotCount = Inf;
            elseif requestedPlotCount == "none"
                requestedPlotCount = 0;
            else
                requestedPlotCount = str2double(requestedPlotCount);
            end
        end

        if ~isscalar(requestedPlotCount) || ...
                isnan(requestedPlotCount) || requestedPlotCount < 0
            error( ...
                'TFA:InvalidSubjectFigureCount', ...
                ['numSubjectFiguresPerGroup must be a nonnegative ' ...
                 'number, "none", or "all".']);
        end
    end

    subjectResults = cell(height(subjectList), 1);
    statusRows = cell(height(subjectList), 1);
    numStatusRows = 0;

    %% Run the Same Subject Analysis Once for Each Selected Subject

    for subjectIndex = 1:height(subjectList)
        currentSubject.subjectID = string( ...
            subjectList.SubjectID(subjectIndex));
        currentSubject.group = string(subjectList.Group(subjectIndex));
        currentSubject.sourceFile = string( ...
            subjectList.SourceFile(subjectIndex));

        groupIndex = find( ...
            successfulSubjectCounts.Group == upper(currentSubject.group), 1);

        if successfulSubjectCounts.SuccessfulSubjects(groupIndex) >= ...
                targetSuccessfulSubjectCounts(groupIndex)
            continue
        end

        subjectOutputSettings = outputSettings;
        if isBatch
            subjectOutputSettings.saveSubjectFigures = ...
                outputSettings.saveSubjectFigures && ...
                subjectFigureCounts.SavedSubjectFigures(groupIndex) < ...
                requestedPlotCount;
        end

        runStatus = initializeSubjectRunStatus(analysisSettings);

        try
            if isSynthetic
                signalData = createSyntheticSignal(analysisSettings.fsTarget);
            else
                try
                    signalData = loadSubjectData(currentSubject.sourceFile);
                catch errorInfo
                    error('TFA:LoadDataFailed', ...
                        'LoadDataFailed: %s', errorInfo.message);
                end
            end

            subjectResults{subjectIndex} = analyzeSubjectTFA( ...
                signalData, currentSubject, ...
                analysisSettings, subjectOutputSettings);
            runStatus = subjectResults{subjectIndex}.runStatus;

            if runStatus.analysisSucceeded
                successfulSubjectCounts.SuccessfulSubjects(groupIndex) = ...
                    successfulSubjectCounts.SuccessfulSubjects(groupIndex) + 1;

                if runStatus.subjectFiguresSaved
                    subjectFigureCounts.SavedSubjectFigures(groupIndex) = ...
                        subjectFigureCounts.SavedSubjectFigures(groupIndex) + 1;
                end
            end

        catch errorInfo
            if ~isBatch
                rethrow(errorInfo)
            end

            runStatus.analysisSucceeded = false;
            runStatus.runStage = "UnknownFailed";

            errorIdentifier = string(errorInfo.identifier);

            if errorIdentifier == "TFA:LoadDataFailed"
                runStatus.runStage = "LoadDataFailed";
            elseif errorIdentifier == "TFA:PreprocessingFailed"
                runStatus.runStage = "PreprocessingFailed";
            elseif errorIdentifier == "TFA:WelchFailed"
                runStatus.runStage = "WelchFailed";
            elseif errorIdentifier == "TFA:MISOFailed"
                runStatus.runStage = "MISOFailed";
            elseif errorIdentifier == "TFA:SISOFailed"
                runStatus.runStage = "SISOFailed";
            end

            runStatus.statusMessage = "Failed: " + string(errorInfo.message);

            fprintf("Subject %s failed: %s\n", ...
                currentSubject.subjectID, string(errorInfo.message));

            failedSubjectResult.subjectInfo = currentSubject;
            failedSubjectResult.runStatus = runStatus;
            failedSubjectResult.misoResults = [];
            failedSubjectResult.sisoResults = [];
            subjectFolderName = upper(string(currentSubject.group)) + ...
                "_" + string(currentSubject.subjectID);
            failedSubjectResult.outputFolder = fullfile( ...
                outputSettings.baseOutputFolder, ...
                subjectFolderName);
            failedSubjectResult.subjectFigureNames = strings(0, 1);
            failedSubjectResult.subjectFigureFiles = strings(0, 1);
            subjectResults{subjectIndex} = failedSubjectResult;
        end

        numStatusRows = numStatusRows + 1;
        statusRows{numStatusRows} = ...
            createSubjectRunStatusRow(currentSubject, runStatus);

        if isBatch
            close all

            if all(successfulSubjectCounts.SuccessfulSubjects >= ...
                    targetSuccessfulSubjectCounts)
                break
            end
        end
    end

    if numStatusRows == 0
        statusTable = table();
    else
        statusTable = vertcat(statusRows{1:numStatusRows});
    end

    %% Calculate and Save Batch Group Figures

    groupResults = struct();
    batchFigureFiles = strings(0, 1);
    excelFile = "";
    batchFigureErrorMessage = "";
    excelErrorMessage = "";

    if isBatch
        groupResults = createGroupResults( ...
            subjectResults, batchSettings.groupsToRun, ...
            analysisSettings.runMISO, analysisSettings.runSISO, ...
            analysisSettings.phase);

        if outputSettings.saveBatchFigures
            try
                batchFigureFiles = saveGroupFigures( ...
                    groupResults, groupsToRun, ...
                    outputSettings.baseOutputFolder, analysisSettings);
            catch errorInfo
                batchFigureErrorMessage = string(errorInfo.message);
                warning( ...
                    'TFA:GroupFigureOutputFailed', ...
                    'Group figures were not saved: %s', errorInfo.message);
            end
        end

    end

    %% Save the Unified Excel Workbook

    if outputSettings.saveExcel
        if isBatch
            excelFolder = outputSettings.baseOutputFolder;
        else
            excelFolder = subjectResults{1}.outputFolder;
        end

        if ~exist(excelFolder, "dir")
            mkdir(excelFolder);
        end

        excelFile = fullfile( ...
            excelFolder, outputSettings.excelFileName);

        try
            saveResultsToExcel( ...
                excelFile, subjectResults, groupsToRun, ...
                analysisSettings, outputSettings);
        catch errorInfo
            excelErrorMessage = string(errorInfo.message);
            excelFile = "";
            warning( ...
                'TFA:ExcelSaveFailed', ...
                'Excel results were not saved: %s', errorInfo.message);
        end
    end

    %% Return the Complete Run Results

    runResults.runType = runType;
    runResults.subjectList = subjectList;
    runResults.subjectResults = subjectResults;
    runResults.statusTable = statusTable;
    runResults.groupResults = groupResults;
    runResults.batchFigureFiles = batchFigureFiles;
    runResults.batchFigureErrorMessage = batchFigureErrorMessage;
    runResults.excelFile = excelFile;
    runResults.excelErrorMessage = excelErrorMessage;
    runResults.successfulSubjectCounts = successfulSubjectCounts;
    runResults.subjectFigureCounts = subjectFigureCounts;

end
