function analysisSettings = validateTfaSettings(analysisSettings)
% validateTfaSettings Validate the user-facing TFA analysis settings.

    %% Model Selection

    if ~isfield(analysisSettings, "runMISO") || ...
            ~isfield(analysisSettings, "runSISO")
        error( ...
            "TFA:MissingModelSelection", ...
            "analysisSettings.runMISO and runSISO must be provided.");
    end

    if ~analysisSettings.runMISO && ~analysisSettings.runSISO
        error( ...
            "TFA:NoModelSelected", ...
            "Enable at least one model using runMISO or runSISO.");
    end

    %% Sampling and Frequency Settings

    validateattributes( ...
        analysisSettings.fsTarget, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'positive'}, ...
        mfilename, 'analysisSettings.fsTarget');

    if ~isfield(analysisSettings, "frequencyRangeHz")
        error( ...
            "TFA:MissingFrequencyRange", ...
            "analysisSettings.frequencyRangeHz must be provided.");
    end

    frequencyRangeHz = analysisSettings.frequencyRangeHz;
    validateattributes( ...
        frequencyRangeHz, {'numeric'}, ...
        {'real', 'finite', 'vector', 'numel', 2, 'nonnegative'}, ...
        mfilename, 'analysisSettings.frequencyRangeHz');

    frequencyRangeHz = double(reshape(frequencyRangeHz, 1, []));

    if frequencyRangeHz(1) >= frequencyRangeHz(2)
        error( ...
            "TFA:InvalidFrequencyRange", ...
            ['analysisSettings.frequencyRangeHz must be [lower upper] ' ...
             'with lower < upper.']);
    end

    nyquistFrequencyHz = analysisSettings.fsTarget / 2;
    if frequencyRangeHz(2) > nyquistFrequencyHz
        error( ...
            "TFA:FrequencyRangeAboveNyquist", ...
            ['The upper analysis frequency cannot exceed the Nyquist ' ...
             'frequency of %.6g Hz.'], nyquistFrequencyHz);
    end

    frequencyBandEdgesHz = analysisSettings.frequencyBandEdgesHz(:);
    frequencyBandNames = string(analysisSettings.frequencyBandNames(:));

    validateattributes( ...
        frequencyBandEdgesHz, {'numeric'}, ...
        {'real', 'finite', 'vector', 'increasing'}, ...
        mfilename, 'analysisSettings.frequencyBandEdgesHz');

    if numel(frequencyBandNames) ~= numel(frequencyBandEdgesHz) - 1
        error( ...
            "TFA:FrequencyBandCountMismatch", ...
            ['frequencyBandNames must contain exactly one name for each ' ...
             'interval between frequencyBandEdgesHz values.']);
    end

    tolerance = 10 * eps(max([1, abs(frequencyRangeHz)]));
    bandsStartBelowRange = ...
        frequencyBandEdgesHz(1) < frequencyRangeHz(1) - tolerance;
    bandsEndAboveRange = ...
        frequencyBandEdgesHz(end) > frequencyRangeHz(2) + tolerance;

    if bandsStartBelowRange || bandsEndAboveRange
        error( ...
            "TFA:FrequencyBandsOutsideAnalysisRange", ...
            ['All frequencyBandEdgesHz must lie inside ' ...
             'frequencyRangeHz. Current range is [%.6g %.6g] Hz.'], ...
            frequencyRangeHz(1), frequencyRangeHz(2));
    end

    analysisSettings.frequencyRangeHz = frequencyRangeHz;
    analysisSettings.frequencyBandEdgesHz = frequencyBandEdgesHz;
    analysisSettings.frequencyBandNames = frequencyBandNames;

    %% Welch Settings

    welchSettings = analysisSettings.pwelch;

    validateattributes( ...
        welchSettings.windowLengthSeconds, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'positive'}, ...
        mfilename, 'analysisSettings.pwelch.windowLengthSeconds');
    validateattributes( ...
        welchSettings.windowOverlap, {'numeric'}, ...
        {'real', 'finite', 'scalar', '>=', 0, '<', 1}, ...
        mfilename, 'analysisSettings.pwelch.windowOverlap');
    validateattributes( ...
        welchSettings.minimumWindows, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'positive'}, ...
        mfilename, 'analysisSettings.pwelch.minimumWindows');

    if ~islogical(welchSettings.smoothingEnabled) || ...
            ~isscalar(welchSettings.smoothingEnabled)
        error( ...
            "TFA:InvalidSmoothingToggle", ...
            "pwelch.smoothingEnabled must be true or false.");
    end

    smoothingKernel = welchSettings.smoothingKernel;
    validateattributes( ...
        smoothingKernel, {'numeric'}, ...
        {'real', 'finite', 'vector', 'nonempty', 'nonnegative'}, ...
        mfilename, 'analysisSettings.pwelch.smoothingKernel');

    if mod(numel(smoothingKernel), 2) == 0
        error( ...
            "TFA:EvenSmoothingKernel", ...
            "pwelch.smoothingKernel must contain an odd number of weights.");
    end

    if abs(sum(smoothingKernel) - 1) > 1e-12
        error( ...
            "TFA:SmoothingKernelDoesNotSumToOne", ...
            "The pwelch.smoothingKernel weights must sum to one.");
    end

    analysisSettings.pwelch.smoothingKernel = ...
        double(reshape(smoothingKernel, 1, []));

    %% Phase and Plot Settings

    unwrapMethod = string(analysisSettings.phase.unwrapMethod);
    if ~any(unwrapMethod == ["standard", "custom"])
        error( ...
            "TFA:UnknownPhaseUnwrapMethod", ...
            "phase.unwrapMethod must be ""standard"" or ""custom"".");
    end
    analysisSettings.phase.unwrapMethod = unwrapMethod;

    if ~isfield(analysisSettings, "plot") || isempty(analysisSettings.plot)
        analysisSettings.plot = defaultPlotSettings();
    end

    transferFunctionStyle = ...
        string(analysisSettings.plot.transferFunctionStyle);
    if ~any(transferFunctionStyle == ["stem", "line"])
        error( ...
            "TFA:UnknownTransferFunctionStyle", ...
            "plot.transferFunctionStyle must be ""stem"" or ""line"".");
    end

    analysisSettings.plot.transferFunctionStyle = transferFunctionStyle;
    analysisSettings.plot.frequencyLimitsHz = frequencyRangeHz;

end
