function diagnostics = createNcDiagnosticTable( ...
    empiricalResults, frequencyRangeHz)
% createNcDiagnosticTable Collect observable NC recording diagnostics.

    subjectResults = empiricalResults.subjectResults;
    rows = cell(0, 1);

    for subjectIndex = 1:numel(subjectResults)
        subject = subjectResults{subjectIndex};
        if isempty(subject) || ...
                ~subject.runStatus.analysisSucceeded || ...
                upper(string(subject.subjectInfo.group)) ~= "NC"
            continue
        end
        if isempty(fieldnames(subject.analysisInput))
            continue
        end

        spectra = subject.analysisInput.spectra;
        frequencyMask = ...
            spectra.f >= frequencyRangeHz(1) & ...
            spectra.f <= frequencyRangeHz(2);
        mapPower = real(spectra.map.power(frequencyMask));
        co2Power = real(spectra.co2.power(frequencyMask));

        row = table( ...
            string(subject.subjectInfo.subjectID), ...
            subject.runStatus.signalDurationSeconds, ...
            subject.runStatus.numWelchWindows, ...
            mean(subject.misoResults.inputRelationship. ...
                coherence, "omitnan"), ...
            calculatePSDShapeOverlap(mapPower, co2Power), ...
            std(subject.analysisInput.co2, "omitnan") / ...
                std(subject.analysisInput.map, "omitnan"), ...
            median(subject.misoResults.diagnostics. ...
                normalizedConditionNumber, "omitnan"), ...
            'VariableNames', { ...
                'SubjectID', 'DurationSeconds', 'NumWelchWindows', ...
                'RealizedInputCoherence', ...
                'RealizedPSDShapeOverlap', ...
                'RealizedPETCO2ToMAPFluctuationSDRatio', ...
                'MedianNormalizedConditionNumber'});
        rows{end + 1,1} = row; %#ok<AGROW>
    end

    if isempty(rows)
        diagnostics = table();
    else
        diagnostics = vertcat(rows{:});
    end

end
