function [figureHandle, sourceData] = ...
    plotSimulationConditioning(data, titleContext)
% plotSimulationConditioning Connect diagnostics to MISO performance.

    if nargin < 2
        titleContext = "";
    end
    sourceData = data(:, { ...
        'FamilyID', 'FamilyInputCoherence', ...
        'FamilyPSDShapeOverlap', ...
        'FamilyPETCO2ToMAPFluctuationSDRatio', ...
        'MedianNormalizedConditionNumber', ...
        'MedianNormalizedDeterminant', ...
        'MAPMISOComplexError', 'CO2MISOComplexError', ...
        'MAPComplexAdvantage', 'CO2ComplexAdvantage'});

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 2, 2, ...
        "TileSpacing", "compact", "Padding", "compact");
    figureTitle = "MISO conditioning and known-truth accuracy";
    if strlength(titleContext) > 0
        figureTitle = figureTitle + newline + titleContext;
    end
    title(layout, figureTitle);

    axesHandle = nexttile(layout);
    scatter(axesHandle, data.MedianNormalizedConditionNumber, ...
        data.MAPMISOComplexError, 20, ...
        data.FamilyInputCoherence, "filled", ...
        "MarkerFaceAlpha", 0.50);
    set(axesHandle, "XScale", "log", "YScale", "log");
    xlabel(axesHandle, "Normalized condition number");
    ylabel(axesHandle, "MISO MAP complex error");
    title(axesHandle, "A  Absolute MAP error");
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Label.String = ...
        "Family mean MAP-PETCO2 coherence";
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    scatter(axesHandle, data.MedianNormalizedConditionNumber, ...
        data.CO2MISOComplexError, 20, ...
        data.FamilyInputCoherence, "filled", ...
        "MarkerFaceAlpha", 0.50);
    set(axesHandle, "XScale", "log", "YScale", "log");
    xlabel(axesHandle, "Normalized condition number");
    ylabel(axesHandle, "MISO CO2 complex error");
    title(axesHandle, "B  Absolute CO2 error");
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Label.String = ...
        "Family mean MAP-PETCO2 coherence";
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    scatter(axesHandle, data.MedianNormalizedConditionNumber, ...
        data.MAPComplexAdvantage, 20, ...
        data.FamilyPSDShapeOverlap, "filled", ...
        "MarkerFaceAlpha", 0.50);
    set(axesHandle, "XScale", "log");
    yline(axesHandle, 0, "k:");
    xlabel(axesHandle, "Normalized condition number");
    ylabel(axesHandle, ...
        "MAP model advantage: log10(SISO/MISO error)");
    title(axesHandle, "C  Comparative MAP accuracy");
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Label.String = ...
        "PSD-shape overlap (Bhattacharyya coefficient)";
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    scatter(axesHandle, data.FamilyInputCoherence, ...
        data.MedianNormalizedConditionNumber, 20, ...
        data.FamilyPSDShapeOverlap, "filled", ...
        "MarkerFaceAlpha", 0.50);
    set(axesHandle, "YScale", "log");
    xlabel(axesHandle, "Family mean MAP-PETCO2 coherence");
    ylabel(axesHandle, "Median normalized condition number");
    title(axesHandle, "D  Input relationship and conditioning");
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Label.String = ...
        "PSD-shape overlap (Bhattacharyya coefficient)";
    grid(axesHandle, "on");

end
