function [figureHandle, sourceData] = plotSimulationFactorErrors( ...
    data, factorName, factorLabel, groupingMode, ...
    groupingSettings, titleContext, statisticsSettings)
% plotSimulationFactorErrors Show overall complex error and comparison.

    if nargin < 5
        groupingSettings = struct();
    end
    if nargin < 6
        titleContext = "";
    end
    if nargin < 7 || isempty(statisticsSettings)
        statisticsSettings.alpha = 0.05;
        statisticsSettings.minimumValidN = 3;
    end
    factorName = string(factorName);
    metrics = [ ...
        "MAPSISOComplexError"
        "MAPMISOComplexError"
        "MAPComplexAdvantage"
        "CO2SISOComplexError"
        "CO2MISOComplexError"
        "CO2ComplexAdvantage"];
    sourceData = summarizeSimulationCurve( ...
        data, factorName, metrics, groupingMode, groupingSettings, ...
        statisticsSettings);

    [x, tickValues, tickLabels] = ...
        prepareSimulationGroupAxis( ...
            sourceData.FactorValue, sourceData.FactorGroup, ...
            groupingMode);
    colors.miso = [0 0.4470 0.7410];
    colors.siso = [0.8500 0.3250 0.0980];
    colors.modelAdvantage = [0.12 0.22 0.36];

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 2, 2, ...
        "TileSpacing", "compact", "Padding", "compact");
    factorTitle = getSimulationFactorTitle( ...
        factorName, factorLabel);
    figureTitle = "Overall complex error and model advantage by " + ...
        factorTitle;
    figureSubtitle = ...
        "Mean and SD | Black ring: BH-adjusted P < " + ...
        string(statisticsSettings.alpha);
    if strlength(titleContext) > 0
        figureSubtitle = figureSubtitle + " | " + titleContext;
    end
    title(layout, figureTitle + newline + figureSubtitle);

    axesHandle = nexttile(layout);
    plotErrorPair( ...
        axesHandle, x, sourceData, "MAP", colors);
    title(axesHandle, ...
        "A  MAP normalized squared complex error");
    ylabel(axesHandle, "Normalized squared complex error");

    axesHandle = nexttile(layout);
    plotModelAdvantage( ...
        axesHandle, x, sourceData, ...
        "MAPComplexAdvantage", colors.modelAdvantage, ...
        statisticsSettings.alpha);
    title(axesHandle, ...
        "B  MAP complex-error model advantage");

    axesHandle = nexttile(layout);
    plotErrorPair( ...
        axesHandle, x, sourceData, "CO2", colors);
    title(axesHandle, ...
        "C  PETCO2 normalized squared complex error");
    ylabel(axesHandle, "Normalized squared complex error");

    axesHandle = nexttile(layout);
    plotModelAdvantage( ...
        axesHandle, x, sourceData, ...
        "CO2ComplexAdvantage", colors.modelAdvantage, ...
        statisticsSettings.alpha);
    title(axesHandle, ...
        "D  PETCO2 complex-error model advantage");

    allAxes = findall(figureHandle, "Type", "axes");
    for axesIndex = 1:numel(allAxes)
        xlabel(allAxes(axesIndex), factorLabel);
        allAxes(axesIndex).XTick = tickValues;
        allAxes(axesIndex).XTickLabel = tickLabels;
        grid(allAxes(axesIndex), "on");
    end

end

function plotErrorPair(axesHandle, x, summary, pathway, colors)
% plotErrorPair Plot SISO and MISO errors on one axis.

    sisoName = pathway + "SISOComplexError";
    misoName = pathway + "MISOComplexError";
    plotMeanSdCurve( ...
        axesHandle, x, summary.(sisoName + "Mean"), ...
        summary.(sisoName + "SD"), ...
        colors.siso, "SISO mean", true);
    plotMeanSdCurve( ...
        axesHandle, x, summary.(misoName + "Mean"), ...
        summary.(misoName + "SD"), ...
        colors.miso, "MISO mean", true);
    set(axesHandle, "YScale", "log");
    legend(axesHandle, "Location", "best");

end

function plotModelAdvantage( ...
    axesHandle, x, summary, metricName, color, alpha)
% plotModelAdvantage Plot the SISO-to-MISO log error ratio.

    plotMeanSdCurve( ...
        axesHandle, x, summary.(metricName + "Mean"), ...
        summary.(metricName + "SD"), ...
        color, "Mean model advantage");
    yline(axesHandle, 0, "k:", ...
        "DisplayName", "Equal error");
    markSignificantCurvePoints( ...
        axesHandle, x, summary.(metricName + "Mean"), ...
        summary.(metricName + "BHAdjustedP"), alpha);
    ylabel(axesHandle, ...
        "Model advantage: log10(SISO/MISO error)");

end
