function [figureHandle, sourceData] = ...
    plotSimulationFamilyCoherenceSpectra(simulationResults)
% plotSimulationFamilyCoherenceSpectra Show coherence within each group.

    observations = simulationResults.observations;
    rows = observations.IsFamilyCharacterizationObservation;
    characterization = observations(rows, :);
    observationIds = characterization.ObservationID;
    frequencyValues = ...
        simulationResults.frequency.inputCoherence(:,observationIds);
    summary = summarizeSimulationFrequencyMap( ...
        characterization.FamilyInputCoherence, frequencyValues, ...
        "FamilyInputCoherence", "binned", ...
        simulationResults.settings.grouping);

    [plotGroups, tickValues, tickLabels] = ...
        prepareSimulationGroupAxis( ...
            summary.factorCenters, summary.factorLabels, "binned");
    displayMask = isfinite(summary.mean) & ...
        summary.validN >= ...
            simulationResults.settings.grouping.minimumValidN;

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    axesHandle = axes(figureHandle);
    imageHandle = imagesc( ...
        axesHandle, simulationResults.frequency.frequencyHz, ...
        plotGroups, summary.mean);
    imageHandle.AlphaData = displayMask;
    axesHandle.Color = [0.92 0.92 0.92];
    set(axesHandle, "YDir", "normal");
    xlim(axesHandle, ...
        simulationResults.settings.frequencyRangeHz);
    clim(axesHandle, [0 1]);
    colormap(axesHandle, parula(256));
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Label.String = ...
        "Mean MAP-PETCO2 coherence";
    xlabel(axesHandle, "Frequency (Hz)");
    ylabel(axesHandle, "Whole-range family coherence group");
    axesHandle.YTick = tickValues;
    axesHandle.YTickLabel = tickLabels;
    grid(axesHandle, "on");

    characterizationDuration = unique( ...
        characterization.DurationSeconds);
    title(axesHandle, ...
        "Frequency-resolved coherence within family groups" + ...
        newline + compose( ...
            "Groups use the %.3g s clean characterization record", ...
            characterizationDuration(1)));

    sourceData = createLongSourceTable( ...
        simulationResults.frequency.frequencyHz, summary);

end

function sourceTable = createLongSourceTable(frequencyHz, summary)
% createLongSourceTable Store the coherence heatmap statistics.

    numFactors = numel(summary.factorCenters);
    numFrequencies = numel(frequencyHz);
    sourceTable = table( ...
        reshape(repelem( ...
            summary.factorCenters(:), numFrequencies), [], 1), ...
        reshape(repelem( ...
            summary.factorLabels(:), numFrequencies), [], 1), ...
        reshape(repelem( ...
            summary.factorLower(:), numFrequencies), [], 1), ...
        reshape(repelem( ...
            summary.factorUpper(:), numFrequencies), [], 1), ...
        repmat(frequencyHz(:), numFactors, 1), ...
        reshape(summary.mean.', [], 1), ...
        reshape(summary.sd.', [], 1), ...
        reshape(summary.validN.', [], 1), ...
        reshape(repelem( ...
            summary.groupN(:), numFrequencies), [], 1), ...
        'VariableNames', { ...
            'FactorValue', 'FactorGroup', ...
            'FactorLower', 'FactorUpper', 'FrequencyHz', ...
            'Mean', 'SD', 'ValidN', 'GroupN'});

end
