function [figureHandle, sourceData] = ...
    plotSimulationFactorFrequencyMaps( ...
        simulationResults, dataRows, factorName, factorLabel, ...
        groupingMode, colorLimit, titleContext)
% plotSimulationFactorFrequencyMaps Show frequency-specific model advantage.

    if nargin < 7
        titleContext = "";
    end
    observations = simulationResults.observations(dataRows, :);
    observationColumns = observations.ObservationID;
    frequency = simulationResults.frequency;
    factorValues = observations.(factorName);
    groupingSettings = simulationResults.settings.grouping;
    statisticsSettings = simulationResults.settings.statistics;
    minimumValidN = groupingSettings.minimumValidN;

    metricNames = [ ...
        "map.complexAdvantage"
        "map.gainAdvantage"
        "map.phaseAdvantage"
        "co2.complexAdvantage"
        "co2.gainAdvantage"
        "co2.phaseAdvantage"];
    panelTitles = [ ...
        "A  MAP complex" + newline + "model advantage"
        "B  MAP gain" + newline + "model advantage"
        "C  MAP phase" + newline + "model advantage"
        "D  PETCO2 complex" + newline + "model advantage"
        "E  PETCO2 gain" + newline + "model advantage"
        "F  PETCO2 phase" + newline + "model advantage"];

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 2, 3, ...
        "TileSpacing", "compact", "Padding", "compact");
    factorTitle = getSimulationFactorTitle( ...
        factorName, factorLabel);
    figureTitle = "Mean frequency-resolved model advantage by " + ...
        factorTitle;
    figureSubtitle = ...
        "Blue: lower MISO error | Orange: lower SISO error | " + ...
        "Black dot: BH-adjusted P < " + ...
        string(statisticsSettings.alpha);
    if strlength(titleContext) > 0
        figureSubtitle = figureSubtitle + " | " + titleContext;
    end
    title(layout, figureTitle + newline + figureSubtitle);
    sourceData = struct();

    for metricIndex = 1:numel(metricNames)
        metricValues = getNestedMetric( ...
            frequency, metricNames(metricIndex));
        metricValues = metricValues(:,observationColumns);
        summary = summarizeSimulationFrequencyMap( ...
            factorValues, metricValues, factorName, ...
            groupingMode, groupingSettings, statisticsSettings);
        [plotCenters, tickValues, tickLabels] = ...
            prepareSimulationHeatmapAxis(summary.factorLabels);

        axesHandle = nexttile(layout);
        imageHandle = imagesc(axesHandle, frequency.frequencyHz, ...
            plotCenters, summary.mean);
        imageHandle.AlphaData = isfinite(summary.mean) & ...
            summary.validN >= minimumValidN;
        axesHandle.Color = [0.92 0.92 0.92];
        set(axesHandle, "YDir", "normal");
        xlim(axesHandle, simulationResults.settings.frequencyRangeHz);
        colormap(axesHandle, misoAdvantageColormap());
        clim(axesHandle, [-colorLimit colorLimit]);
        xlabel(axesHandle, "Frequency (Hz)");
        ylabel(axesHandle, factorLabel);
        axesHandle.YTick = tickValues;
        axesHandle.YTickLabel = tickLabels;
        title( ...
            axesHandle, panelTitles(metricIndex), ...
            "FontSize", 9);
        markSignificantHeatmapCells( ...
            axesHandle, frequency.frequencyHz, plotCenters, ...
            summary.bhAdjustedP, statisticsSettings.alpha);

        fieldName = replace(metricNames(metricIndex), ".", "_");
        sourceData.(fieldName) = createLongSourceTable( ...
            frequency.frequencyHz, summary);
    end
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Layout.Tile = "east";
    colorbarHandle.Label.String = "Mean model advantage";
    labelModelAdvantageColorbar(colorbarHandle, colorLimit);

end

function labelModelAdvantageColorbar(colorbarHandle, colorLimit)
% labelModelAdvantageColorbar Mark equal error and clipped endpoints.

    ticks = linspace(-colorLimit, colorLimit, 5);
    labels = string(compose("%.2g", ticks));
    labels(1) = "<=" + labels(1);
    labels(end) = ">=" + labels(end);
    colorbarHandle.Ticks = ticks;
    colorbarHandle.TickLabels = labels;

end

function values = getNestedMetric(frequency, metricName)
% getNestedMetric Retrieve a two-level frequency result field.

    parts = split(metricName, ".");
    values = frequency.(parts(1)).(parts(2));

end

function sourceTable = createLongSourceTable( ...
    frequencyHz, summary)
% createLongSourceTable Store a heatmap in tidy source-data form.

    factorValues = summary.factorCenters;
    numFactors = numel(factorValues);
    numFrequencies = numel(frequencyHz);
    factorColumn = repelem(factorValues(:), numFrequencies);
    factorColumn = factorColumn(:);
    sourceTable = table( ...
        factorColumn, ...
        reshape(repelem( ...
            summary.factorLabels(:), numFrequencies), [], 1), ...
        reshape(repelem( ...
            summary.factorLower(:), numFrequencies), [], 1), ...
        reshape(repelem( ...
            summary.factorUpper(:), numFrequencies), [], 1), ...
        repmat(frequencyHz(:), numFactors, 1), ...
        reshape(summary.mean.', [], 1), ...
        reshape(summary.sd.', [], 1), ...
        reshape(summary.validN.', [], 1), ...
        reshape(repelem( ...
            summary.groupN(:), numFrequencies), [], 1), ...
        'VariableNames', { ...
            'FactorValue', 'FactorGroup', ...
            'FactorLower', 'FactorUpper', 'FrequencyHz', ...
            'Mean', 'SD', 'ValidN', 'GroupN'});
    if isfield(summary, "rawP")
        sourceTable.StandardError = ...
            reshape(summary.standardError.', [], 1);
        sourceTable.CILower = ...
            reshape(summary.ciLower.', [], 1);
        sourceTable.CIUpper = ...
            reshape(summary.ciUpper.', [], 1);
        sourceTable.RawP = reshape(summary.rawP.', [], 1);
        sourceTable.BHAdjustedP = ...
            reshape(summary.bhAdjustedP.', [], 1);
        sourceTable.IsSignificant = ...
            reshape(summary.isSignificant.', [], 1);
        sourceTable.GeometricSISOToMISOErrorRatio = ...
            reshape( ...
                summary.geometricSisoToMisoErrorRatio.', [], 1);
    end

end
