function [figureHandle, sourceData] = ...
    plotSimulationRidgeResults( ...
        ridgeTable, titleContext, statisticsSettings)
% plotSimulationRidgeResults Summarize the paired regularization path.

    if nargin < 2
        titleContext = "";
    end
    if nargin < 3 || isempty(statisticsSettings)
        statisticsSettings.alpha = 0.05;
        statisticsSettings.minimumValidN = 3;
    end
    metrics = [ ...
        "MAPComplexError"
        "MAPComplexAdvantage"
        "MAPMISOHasLowerComplexError"
        "CO2ComplexError"
        "CO2ComplexAdvantage"
        "CO2MISOHasLowerComplexError"];
    sourceData = summarizeSimulationCurve( ...
        ridgeTable, "Lambda", metrics, "exact", struct(), ...
        statisticsSettings);
    x = sourceData.FactorValue;

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 2, 3, ...
        "TileSpacing", "compact", "Padding", "compact");
    figureTitle = "Ridge sensitivity of pathway error and model comparison";
    if strlength(titleContext) > 0
        figureTitle = figureTitle + newline + titleContext;
    end
    title(layout, figureTitle + newline + ...
        "Black ring: BH-adjusted P < " + ...
        string(statisticsSettings.alpha));
    color = [0 0.4470 0.7410];

    plotMetric(nexttile(layout), x, sourceData, ...
        "MAPComplexError", color, true, ...
        "A  MAP ridge-MISO complex error", ...
        "Normalized squared complex error");
    plotMetric(nexttile(layout), x, sourceData, ...
        "MAPComplexAdvantage", color, false, ...
        "B  MAP complex model advantage", ...
        "log10(SISO error / ridge-MISO error)", ...
        statisticsSettings.alpha);
    plotLowerErrorFraction(nexttile(layout), x, sourceData, ...
        "MAPMISOHasLowerComplexError", ...
        "C  MAP lower-error fraction");
    plotMetric(nexttile(layout), x, sourceData, ...
        "CO2ComplexError", color, true, ...
        "D  PETCO2 ridge-MISO complex error", ...
        "Normalized squared complex error");
    plotMetric(nexttile(layout), x, sourceData, ...
        "CO2ComplexAdvantage", color, false, ...
        "E  PETCO2 complex model advantage", ...
        "log10(SISO error / ridge-MISO error)", ...
        statisticsSettings.alpha);
    plotLowerErrorFraction(nexttile(layout), x, sourceData, ...
        "CO2MISOHasLowerComplexError", ...
        "F  PETCO2 lower-error fraction");

    allAxes = findall(figureHandle, "Type", "axes");
    for axesIndex = 1:numel(allAxes)
        set(allAxes(axesIndex), "XScale", "log");
        xlabel(allAxes(axesIndex), "Standardized ridge lambda");
        grid(allAxes(axesIndex), "on");
    end

end

function plotMetric( ...
    axesHandle, x, summary, metricName, color, logScale, ...
    panelTitle, yLabel, alpha)
% plotMetric Draw one ridge metric.

    if nargin < 9
        alpha = NaN;
    end

    plotMeanSdCurve( ...
        axesHandle, x, summary.(metricName + "Mean"), ...
        summary.(metricName + "SD"), ...
        color, "Mean", logScale);
    if contains(metricName, "Advantage")
        yline(axesHandle, 0, "k:");
        markSignificantCurvePoints( ...
            axesHandle, x, summary.(metricName + "Mean"), ...
            summary.(metricName + "BHAdjustedP"), alpha);
    end
    if logScale
        set(axesHandle, "YScale", "log");
    end
    ylabel(axesHandle, yLabel);
    title(axesHandle, panelTitle);

end

function plotLowerErrorFraction( ...
    axesHandle, x, summary, metricName, panelTitle)
% plotLowerErrorFraction Show the fraction of families favoring ridge MISO.

    fraction = summary.(metricName + "Mean");
    plot(axesHandle, x, fraction, "o-", ...
        "Color", [0.12 0.22 0.36], "LineWidth", 2, ...
        "MarkerFaceColor", [0.12 0.22 0.36]);
    yline(axesHandle, 0.5, "k:");
    ylim(axesHandle, [0 1]);
    ylabel(axesHandle, ...
        "Fraction with ridge-MISO error below SISO error");
    title(axesHandle, panelTitle);

end
