function [figureHandle, sourceData] = ...
    plotSimulationFactorComponents( ...
        data, factorName, factorLabel, groupingMode, ...
        groupingSettings, titleContext, statisticsSettings)
% plotSimulationFactorComponents Show component advantage and consistency.

    if nargin < 5
        groupingSettings = struct();
    end
    if nargin < 6
        titleContext = "";
    end
    if nargin < 7 || isempty(statisticsSettings)
        statisticsSettings.alpha = 0.05;
        statisticsSettings.minimumValidN = 3;
    end
    factorName = string(factorName);
    metrics = [ ...
        "MAPGainAdvantage"
        "MAPPhaseAdvantage"
        "CO2GainAdvantage"
        "CO2PhaseAdvantage"
        "MAPComplexAdvantage"
        "CO2ComplexAdvantage"];
    sourceData = summarizeSimulationCurve( ...
        data, factorName, metrics, groupingMode, groupingSettings, ...
        statisticsSettings);
    [x, tickValues, tickLabels] = ...
        prepareSimulationGroupAxis( ...
            sourceData.FactorValue, sourceData.FactorGroup, ...
            groupingMode);
    advantageColor = [0.12 0.22 0.36];
    fractionColor = [0 0.4470 0.7410];

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 2, 3, ...
        "TileSpacing", "compact", "Padding", "compact");
    factorTitle = getSimulationFactorTitle( ...
        factorName, factorLabel);
    figureTitle = ...
        "Whole-range gain and phase model advantage by " + ...
        factorTitle;
    figureSubtitle = ...
        "Mean and SD | Black ring: BH-adjusted P < " + ...
        string(statisticsSettings.alpha) + ...
        " | Consistency: family fraction";
    if strlength(titleContext) > 0
        figureSubtitle = figureSubtitle + " | " + titleContext;
    end
    title(layout, figureTitle + newline + figureSubtitle);

    plotModelAdvantagePanel( ...
        nexttile(layout), x, sourceData, ...
        "MAPGainAdvantage", advantageColor, ...
        "A  MAP gain" + newline + "model advantage", ...
        statisticsSettings.alpha);
    plotModelAdvantagePanel( ...
        nexttile(layout), x, sourceData, ...
        "MAPPhaseAdvantage", advantageColor, ...
        "B  MAP phase" + newline + "model advantage", ...
        statisticsSettings.alpha);
    plotLowerMisoFraction( ...
        nexttile(layout), x, sourceData, ...
        "MAPComplexAdvantage", fractionColor, ...
        "C  MAP lower-MISO" + newline + ...
            "complex-error fraction");

    plotModelAdvantagePanel( ...
        nexttile(layout), x, sourceData, ...
        "CO2GainAdvantage", advantageColor, ...
        "D  PETCO2 gain" + newline + "model advantage", ...
        statisticsSettings.alpha);
    plotModelAdvantagePanel( ...
        nexttile(layout), x, sourceData, ...
        "CO2PhaseAdvantage", advantageColor, ...
        "E  PETCO2 phase" + newline + "model advantage", ...
        statisticsSettings.alpha);
    plotLowerMisoFraction( ...
        nexttile(layout), x, sourceData, ...
        "CO2ComplexAdvantage", fractionColor, ...
        "F  PETCO2 lower-MISO" + newline + ...
            "complex-error fraction");

    allAxes = findall(figureHandle, "Type", "axes");
    for axesIndex = 1:numel(allAxes)
        xlabel(allAxes(axesIndex), factorLabel);
        allAxes(axesIndex).XTick = tickValues;
        allAxes(axesIndex).XTickLabel = tickLabels;
        grid(allAxes(axesIndex), "on");
    end

end

function plotModelAdvantagePanel( ...
    axesHandle, x, summary, metricName, color, panelTitle, alpha)
% plotModelAdvantagePanel Draw a mean model-advantage curve.

    plotMeanSdCurve( ...
        axesHandle, x, summary.(metricName + "Mean"), ...
        summary.(metricName + "SD"), ...
        color, "Mean model advantage");
    yline(axesHandle, 0, "k:");
    markSignificantCurvePoints( ...
        axesHandle, x, summary.(metricName + "Mean"), ...
        summary.(metricName + "BHAdjustedP"), alpha);
    ylabel(axesHandle, ...
        "Model advantage: log10(SISO/MISO error)");
    title(axesHandle, panelTitle, "FontSize", 9);

end

function plotLowerMisoFraction( ...
    axesHandle, x, summary, metricName, color, panelTitle)
% plotLowerMisoFraction Plot how consistently MISO has lower error.

    fractionName = metricName + "FractionPositive";
    plot(axesHandle, x, summary.(fractionName), "o-", ...
        "Color", color, "LineWidth", 2, ...
        "MarkerFaceColor", color);
    yline(axesHandle, 0.5, "k:");
    ylim(axesHandle, [0 1]);
    ylabel(axesHandle, ...
        "Fraction with lower MISO complex error");
    title(axesHandle, panelTitle, "FontSize", 9);

end
