function [figureHandle, sourceData] = ...
    plotSimulationTransferFunctionExamples(simulationResults)
% plotSimulationTransferFunctionExamples Show two conditioning endpoints.

    observations = simulationResults.observations;
    reference = observations(observations.IsReferenceObservation, :);
    eligible = reference.AssignedPETCO2ToMAPBandGainRatio > 0 & ...
        isfinite(reference.MedianNormalizedConditionNumber);
    if ~any(eligible)
        eligible = isfinite( ...
            reference.MedianNormalizedConditionNumber);
    end

    eligibleRows = find(eligible);
    conditionNumber = ...
        reference.MedianNormalizedConditionNumber(eligible);
    [~, lowConditionIndex] = min(conditionNumber);
    [~, highConditionIndex] = max(conditionNumber);
    selectedIndices = eligibleRows( ...
        [lowConditionIndex highConditionIndex]);
    selected = reference(selectedIndices, :);

    caseNames = [ ...
        "Lower-conditioning example"
        "Higher-conditioning example"];
    selectionRules = [ ...
        "Lowest median normalized condition number"
        "Highest median normalized condition number"];
    frequency = simulationResults.frequency;
    frequencyRangeHz = ...
        simulationResults.settings.frequencyRangeHz;

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 4, 2, ...
        "TileSpacing", "compact", "Padding", "compact");
    headerFormat = ...
        "Illustrative training-reference observations | " + ...
        "same selection metric at opposite ends | " + ...
        "%.0f s, CBFV SNR = %g dB";
    title(layout, sprintf(headerFormat, ...
        selected.DurationSeconds(1), selected.OutputSNRdB(1)));

    sourceRows = cell(2, 1);
    for caseIndex = 1:2
        observationId = selected.ObservationID(caseIndex);
        familyId = selected.FamilyID(caseIndex);
        currentCondition = ...
            selected.MedianNormalizedConditionNumber(caseIndex);
        exampleLabel = "Family " + familyId + " | " + ...
            caseNames(caseIndex);

        plotPathwayPanels( ...
            layout, frequency, observationId, caseIndex, ...
            "map", exampleLabel, currentCondition, ...
            frequencyRangeHz);
        plotPathwayPanels( ...
            layout, frequency, observationId, caseIndex + 4, ...
            "co2", exampleLabel, currentCondition, ...
            frequencyRangeHz);
        sourceRows{caseIndex} = createSourceRows( ...
            frequency, selected(caseIndex, :), ...
            caseNames(caseIndex));
    end

    metadata = selected(:, { ...
        'ObservationID', 'FamilyID', 'DurationSeconds', ...
        'OutputSNRdB', 'MAPInputSNRdB', 'CO2InputSNRdB', ...
        'AlignmentErrorSeconds', 'TargetInputCoherence', ...
        'RealizedInputCoherence', 'SpectralSimilarityControl', ...
        'DesignedPSDShapeOverlap', 'RealizedPSDShapeOverlap', ...
        'AssignedPETCO2ToMAPFluctuationSDRatio', ...
        'RealizedPETCO2ToMAPFluctuationSDRatio', ...
        'AssignedPETCO2ToMAPBandGainRatio', ...
        'AchievedPETCO2ToMAPBandGainRatio', ...
        'CO2DelaySeconds', ...
        'MedianNormalizedConditionNumber'});
    metadata = addvars( ...
        metadata, caseNames, selectionRules, ...
        'Before', 'ObservationID', ...
        'NewVariableNames', {'Case', 'SelectionRule'});

    sourceData.frequencyCurves = vertcat(sourceRows{:});
    sourceData.metadata = metadata;

end

function plotPathwayPanels( ...
    layout, frequency, observationId, tileColumn, pathway, ...
    exampleLabel, conditionNumber, frequencyRangeHz)
% plotPathwayPanels Draw gain and phase for one pathway and example.

    gainTile = tileColumn;
    phaseTile = tileColumn + 2;

    truth = frequency.(pathway).truth(:,observationId);
    miso = frequency.(pathway).misoEstimate(:,observationId);
    siso = frequency.(pathway).sisoEstimate(:,observationId);
    if pathway == "map"
        pathwayLabel = "MAP";
    else
        pathwayLabel = "PETCO2";
    end

    axesHandle = nexttile(layout, gainTile);
    plotOverlay(axesHandle, frequency.frequencyHz, ...
        abs(truth), abs(miso), abs(siso), gainTile == 1, ...
        frequencyRangeHz);
    ylabel(axesHandle, pathwayLabel + " gain");
    title(axesHandle, sprintf( ...
        "%s | %s gain | condition = %.2f", ...
        exampleLabel, pathwayLabel, conditionNumber));

    axesHandle = nexttile(layout, phaseTile);
    plotOverlay(axesHandle, frequency.frequencyHz, ...
        rad2deg(angle(truth)), rad2deg(angle(miso)), ...
        rad2deg(angle(siso)), false, frequencyRangeHz);
    ylabel(axesHandle, pathwayLabel + ...
        " wrapped phase (degrees)");
    title(axesHandle, exampleLabel + " | " + ...
        pathwayLabel + " wrapped phase");

end

function plotOverlay( ...
    axesHandle, frequencyHz, truth, miso, siso, showLegend, ...
    frequencyRangeHz)
% plotOverlay Draw the three transfer-function curves consistently.

    plot(axesHandle, frequencyHz, truth, ...
        "k", "LineWidth", 1.8, "DisplayName", "Truth");
    hold(axesHandle, "on");
    plot(axesHandle, frequencyHz, miso, ...
        "Color", [0 0.4470 0.7410], "LineWidth", 1.2, ...
        "DisplayName", "MISO");
    plot(axesHandle, frequencyHz, siso, ...
        "Color", [0.8500 0.3250 0.0980], "LineWidth", 1.2, ...
        "DisplayName", "SISO");
    xlim(axesHandle, frequencyRangeHz);
    xlabel(axesHandle, "Frequency (Hz)");
    grid(axesHandle, "on");
    if showLegend
        legend(axesHandle, "Location", "best");
    end

end

function sourceTable = createSourceRows( ...
    frequency, selectedRow, caseName)
% createSourceRows Save example complex coefficients and labels.

    observationId = selectedRow.ObservationID;
    numFrequencies = numel(frequency.frequencyHz);
    sourceTable = table( ...
        repmat(string(caseName), numFrequencies, 1), ...
        repmat(observationId, numFrequencies, 1), ...
        repmat(selectedRow.FamilyID, numFrequencies, 1), ...
        repmat(selectedRow.MedianNormalizedConditionNumber, ...
            numFrequencies, 1), ...
        frequency.frequencyHz, ...
        frequency.map.truth(:,observationId), ...
        frequency.map.misoEstimate(:,observationId), ...
        frequency.map.sisoEstimate(:,observationId), ...
        frequency.co2.truth(:,observationId), ...
        frequency.co2.misoEstimate(:,observationId), ...
        frequency.co2.sisoEstimate(:,observationId), ...
        'VariableNames', { ...
            'Case', 'ObservationID', 'FamilyID', ...
            'MedianNormalizedConditionNumber', 'FrequencyHz', ...
            'MAPTruth', 'MAPMISO', 'MAPSISO', ...
            'CO2Truth', 'CO2MISO', 'CO2SISO'});

end
