function [figureHandle, sourceData] = ...
    plotSimulationGeneratorValidation(simulationResults)
% plotSimulationGeneratorValidation Verify requested and realized inputs.

    design = simulationResults.familyDesign;
    observations = simulationResults.observations;
    reference = observations( ...
        observations.IsFamilyCharacterizationObservation, :);
    reference = sortrows(reference, "FamilyID");
    design = sortrows(design, "FamilyID");

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 3, 2, ...
        "TileSpacing", "compact", "Padding", "compact");
    title(layout, ...
        "Validation of requested and realized family properties" + ...
        newline + "One long, noise-free characterization record per family");

    axesHandle = nexttile(layout);
    drawIdentityScatter( ...
        axesHandle, design.TargetInputCoherence, ...
        reference.RealizedInputCoherence, ...
        "Target coherence", "Realized coherence");
    title(axesHandle, "A  Coherence control");

    axesHandle = nexttile(layout);
    drawIdentityScatter( ...
        axesHandle, design.DesignedPSDShapeOverlap, ...
        reference.RealizedPSDShapeOverlap, ...
        "Designed PSD-shape overlap", ...
        "Realized PSD-shape overlap");
    title(axesHandle, "B  PSD-shape-overlap control");

    axesHandle = nexttile(layout);
    drawIdentityScatter( ...
        axesHandle, design.PETCO2ToMAPFluctuationSDRatio, ...
        reference.RealizedPETCO2ToMAPFluctuationSDRatio, ...
        "Assigned PETCO2-to-MAP fluctuation SD ratio", ...
        "Realized PETCO2-to-MAP fluctuation SD ratio");
    set(axesHandle, "XScale", "log", "YScale", "log");
    title(axesHandle, "C  Input fluctuation ratio");

    axesHandle = nexttile(layout);
    drawIdentityScatter( ...
        axesHandle, design.PETCO2ToMAPBandGainRatio, ...
        reference.AchievedPETCO2ToMAPBandGainRatio, ...
        "Assigned PETCO2-to-MAP band-gain ratio", ...
        "Achieved PETCO2-to-MAP band-gain ratio");
    set(axesHandle, "XScale", "log", "YScale", "log");
    title(axesHandle, "D  Pathway band-gain ratio");

    axesHandle = nexttile(layout);
    delayValues = unique(design.CO2DelaySeconds, "sorted");
    delayCounts = arrayfun( ...
        @(value) nnz(design.CO2DelaySeconds == value), delayValues);
    bar(axesHandle, delayValues, delayCounts, ...
        "FaceColor", [0.20 0.60 0.50]);
    xlabel(axesHandle, "Assigned true PETCO2 response delay (s)");
    ylabel(axesHandle, "Number of families");
    title(axesHandle, "E  Balanced delay levels");
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    scatter(axesHandle, ...
        reference.AchievedPETCO2ToMAPBandGainRatio, ...
        reference.RealizedPETCO2ContributionPowerShare, ...
        26, reference.RealizedPETCO2ToMAPFluctuationSDRatio, ...
        "filled", "MarkerFaceAlpha", 0.60);
    set(axesHandle, "XScale", "log");
    xlabel(axesHandle, "Achieved PETCO2-to-MAP band-gain ratio");
    ylabel(axesHandle, "Realized PETCO2 contribution-power share");
    title(axesHandle, "F  Transfer gain and realized output contribution");
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Label.String = ...
        "Realized PETCO2-to-MAP fluctuation SD ratio";
    grid(axesHandle, "on");

    sourceData.targetAndRealized = table( ...
        design.FamilyID, design.TargetInputCoherence, ...
        reference.RealizedInputCoherence, ...
        design.DesignedPSDShapeOverlap, ...
        reference.RealizedPSDShapeOverlap, ...
        design.PETCO2ToMAPFluctuationSDRatio, ...
        reference.RealizedPETCO2ToMAPFluctuationSDRatio, ...
        design.PETCO2ToMAPBandGainRatio, ...
        reference.AchievedPETCO2ToMAPBandGainRatio, ...
        design.CO2DelaySeconds, ...
        reference.RealizedPETCO2ContributionPowerShare, ...
        'VariableNames', { ...
            'FamilyID', 'TargetCoherence', 'RealizedCoherence', ...
            'DesignedPSDShapeOverlap', ...
            'RealizedPSDShapeOverlap', ...
            'AssignedPETCO2ToMAPFluctuationSDRatio', ...
            'RealizedPETCO2ToMAPFluctuationSDRatio', ...
            'AssignedPETCO2ToMAPBandGainRatio', ...
            'AchievedPETCO2ToMAPBandGainRatio', ...
            'AssignedPETCO2DelaySeconds', ...
            'RealizedPETCO2ContributionPowerShare'});
    sourceData.assignedLevelCounts = createLevelCountTable(design);
    sourceData.assignedFactorCorrelations = ...
        createAssignedFactorCorrelationTable(design);

end

function correlationTable = createAssignedFactorCorrelationTable(design)
% createAssignedFactorCorrelationTable Check incidental design correlations.

    variableNames = [ ...
        "TargetInputCoherence"
        "SpectralSimilarityControl"
        "PETCO2ToMAPFluctuationSDRatio"
        "PETCO2ToMAPBandGainRatio"
        "CO2DelaySeconds"];
    correlationMatrix = corrcoef( ...
        design{:,variableNames}, "Rows", "pairwise");
    [rowIndex, columnIndex] = ndgrid( ...
        1:numel(variableNames), 1:numel(variableNames));
    correlationTable = table( ...
        variableNames(rowIndex(:)), ...
        variableNames(columnIndex(:)), ...
        correlationMatrix(:), ...
        'VariableNames', { ...
            'Factor1', 'Factor2', 'Correlation'});

end

function countTable = createLevelCountTable(design)
% createLevelCountTable Export counts for every assigned family factor.

    factorNames = [ ...
        "TargetInputCoherence"
        "SpectralSimilarityControl"
        "PETCO2ToMAPFluctuationSDRatio"
        "PETCO2ToMAPBandGainRatio"
        "CO2DelaySeconds"];
    parts = cell(numel(factorNames), 1);
    for factorIndex = 1:numel(factorNames)
        factorName = factorNames(factorIndex);
        values = unique(design.(factorName), "sorted");
        counts = arrayfun( ...
            @(value) nnz(design.(factorName) == value), values);
        parts{factorIndex} = table( ...
            repmat(factorName, numel(values), 1), ...
            values, counts, ...
            'VariableNames', {'Factor', 'AssignedValue', 'FamilyN'});
    end
    countTable = vertcat(parts{:});

end

function drawIdentityScatter(axesHandle, x, y, xLabel, yLabel)
% drawIdentityScatter Draw data and the ideal x-equals-y reference.

    scatter(axesHandle, x, y, 24, "filled", ...
        "MarkerFaceAlpha", 0.55);
    hold(axesHandle, "on");
    limits = [min([x; y], [], "omitnan"), ...
        max([x; y], [], "omitnan")];
    plot(axesHandle, limits, limits, "k--", "LineWidth", 1.2);
    xlabel(axesHandle, xLabel);
    ylabel(axesHandle, yLabel);
    grid(axesHandle, "on");

end
