function [figureHandle, sourceData] = ...
    plotSimulationSystemExample(simulationResults)
% plotSimulationSystemExample Explain one generated reference observation.

    family = simulationResults.exampleFamily;
    settings = simulationResults.settings;
    realization = family.training;
    referencePlan = simulationResults.observationPlan( ...
        simulationResults.observationPlan.RunRidge, :);
    observation = createKnownTruthObservation( ...
        realization, referencePlan);

    fs = observation.fs;
    displaySeconds = settings.welch.windowLengthSeconds;
    numDisplaySamples = min( ...
        numel(observation.map), round(displaySeconds*fs));
    indices = 1:numDisplaySamples;
    timeSeconds = (indices - 1)'/fs;

    cleanSpectra = estimateWelchSpectra( ...
        observation.map, observation.co2, ...
        observation.cleanCbv, fs, settings.welch);
    observedSpectra = estimateWelchSpectra( ...
        observation.map, observation.co2, ...
        observation.cbv, fs, settings.welch);

    frequencyMask = ...
        observedSpectra.f >= settings.frequencyRangeHz(1) & ...
        observedSpectra.f <= settings.frequencyRangeHz(2);
    frequencyHz = observedSpectra.f(frequencyMask);
    mapPower = real(observedSpectra.map.power(frequencyMask));
    co2Power = real(observedSpectra.co2.power(frequencyMask));
    cleanCbvPower = real(cleanSpectra.cbv.power(frequencyMask));
    observedCbvPower = real( ...
        observedSpectra.cbv.power(frequencyMask));
    realizedCoherence = abs( ...
        observedSpectra.cross.mapCo2(frequencyMask)).^2 ./ ...
        max(mapPower.*co2Power, settings.metrics.errorFloor);
    target = createKnownTruthInputSpectra( ...
        frequencyHz, family.scenario, settings);

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 3, 2, ...
        "TileSpacing", "compact", "Padding", "compact");
    titleText = sprintf( ...
        "Illustrative Family %d training reference | %.0f s, CBFV SNR = %g dB", ...
        family.familyId, referencePlan.DurationSeconds, ...
        referencePlan.OutputSNRdB);
    title(layout, titleText);

    axesHandle = nexttile(layout);
    plot(axesHandle, timeSeconds, ...
        standardizeForPlot(observation.map(indices)), ...
        "LineWidth", 1.0, "DisplayName", "MAP");
    hold(axesHandle, "on");
    plot(axesHandle, timeSeconds, ...
        standardizeForPlot(observation.co2(indices)), ...
        "LineWidth", 1.0, "DisplayName", "PETCO2");
    xlabel(axesHandle, "Time (s)");
    ylabel(axesHandle, "Standardized input");
    xlim(axesHandle, [0 displaySeconds]);
    title(axesHandle, sprintf( ...
        "A  Input time signals, first %.0f s", displaySeconds));
    legend(axesHandle, "Location", "best");
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    plot(axesHandle, timeSeconds, ...
        observation.cleanCbv(indices), ...
        "k", "LineWidth", 1.3, ...
        "DisplayName", "Clean CBFV");
    hold(axesHandle, "on");
    plot(axesHandle, timeSeconds, observation.cbv(indices), ...
        "Color", [0.45 0.45 0.45], "LineWidth", 0.9, ...
        "DisplayName", "Observed CBFV");
    xlabel(axesHandle, "Time (s)");
    ylabel(axesHandle, "CBFV (simulation units)");
    xlim(axesHandle, [0 displaySeconds]);
    title(axesHandle, sprintf( ...
        "B  CBFV time signals, first %.0f s", displaySeconds));
    legend(axesHandle, "Location", "best");
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    semilogy(axesHandle, frequencyHz, mapPower, ...
        "LineWidth", 1.4, "DisplayName", "MAP");
    hold(axesHandle, "on");
    semilogy(axesHandle, frequencyHz, co2Power, ...
        "LineWidth", 1.4, "DisplayName", "PETCO2");
    xlabel(axesHandle, "Frequency (Hz)");
    ylabel(axesHandle, "Power spectral density");
    title(axesHandle, "C  Full-record input PSDs");
    legend(axesHandle, "Location", "best");
    grid(axesHandle, "on");
    xlim(axesHandle, settings.frequencyRangeHz);

    axesHandle = nexttile(layout);
    semilogy(axesHandle, frequencyHz, cleanCbvPower, ...
        "k", "LineWidth", 1.4, ...
        "DisplayName", "Clean CBFV");
    hold(axesHandle, "on");
    semilogy(axesHandle, frequencyHz, observedCbvPower, ...
        "Color", [0.45 0.45 0.45], "LineWidth", 1.2, ...
        "DisplayName", "Observed CBFV");
    xlabel(axesHandle, "Frequency (Hz)");
    ylabel(axesHandle, "Power spectral density");
    title(axesHandle, "D  Full-record CBFV PSDs");
    legend(axesHandle, "Location", "best");
    grid(axesHandle, "on");
    xlim(axesHandle, settings.frequencyRangeHz);

    axesHandle = nexttile(layout);
    plot(axesHandle, timeSeconds, ...
        realization.mapContribution(indices), ...
        "LineWidth", 1.0, ...
        "DisplayName", "MAP contribution");
    hold(axesHandle, "on");
    plot(axesHandle, timeSeconds, ...
        realization.co2Contribution(indices), ...
        "LineWidth", 1.0, ...
        "DisplayName", "CO2 contribution");
    xlabel(axesHandle, "Time (s)");
    ylabel(axesHandle, "CBFV contribution");
    xlim(axesHandle, [0 displaySeconds]);
    title(axesHandle, "E  Known pathway contributions");
    legend(axesHandle, "Location", "best");
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    plot(axesHandle, frequencyHz, target.targetCoherence, ...
        "k--", "LineWidth", 1.4, ...
        "DisplayName", "Target");
    hold(axesHandle, "on");
    plot(axesHandle, frequencyHz, realizedCoherence, ...
        "Color", [0.20 0.60 0.50], "LineWidth", 1.4, ...
        "DisplayName", "Realized");
    ylim(axesHandle, [0 1]);
    xlim(axesHandle, settings.frequencyRangeHz);
    xlabel(axesHandle, "Frequency (Hz)");
    ylabel(axesHandle, "MAP-PETCO2 coherence");
    title(axesHandle, "F  Target and realized input coherence");
    legend(axesHandle, "Location", "best");
    grid(axesHandle, "on");

    sourceData.timeSignals = createTimeSourceData( ...
        family, referencePlan, timeSeconds, indices, ...
        realization, observation);
    sourceData.frequencySignals = createFrequencySourceData( ...
        family, referencePlan, frequencyHz, ...
        mapPower, co2Power, cleanCbvPower, observedCbvPower, ...
        target.targetCoherence, realizedCoherence);
    sourceData.metadata = createMetadataTable( ...
        simulationResults, family, referencePlan, ...
        realizedCoherence);

end

function sourceTable = createTimeSourceData( ...
    family, referencePlan, timeSeconds, indices, ...
    realization, observation)
% createTimeSourceData Store the values shown in the time panels.

    numRows = numel(timeSeconds);
    sourceTable = table( ...
        repmat(family.familyId, numRows, 1), ...
        repmat("Training", numRows, 1), ...
        repmat(referencePlan.DurationSeconds, numRows, 1), ...
        repmat(referencePlan.OutputSNRdB, numRows, 1), ...
        timeSeconds, observation.map(indices), ...
        observation.co2(indices), ...
        realization.mapContribution(indices), ...
        realization.co2Contribution(indices), ...
        observation.cleanCbv(indices), observation.cbv(indices), ...
        'VariableNames', { ...
            'FamilyID', 'Realization', 'DurationSeconds', ...
            'OutputSNRdB', 'TimeSeconds', 'MAP', 'PETCO2', ...
            'MAPContribution', 'CO2Contribution', ...
            'CleanCBFV', 'ObservedCBFV'});

end

function sourceTable = createFrequencySourceData( ...
    family, referencePlan, frequencyHz, mapPower, co2Power, ...
    cleanCbvPower, observedCbvPower, ...
    targetCoherence, realizedCoherence)
% createFrequencySourceData Store the values shown in frequency panels.

    numRows = numel(frequencyHz);
    sourceTable = table( ...
        repmat(family.familyId, numRows, 1), ...
        repmat("Training", numRows, 1), ...
        repmat(referencePlan.DurationSeconds, numRows, 1), ...
        repmat(referencePlan.OutputSNRdB, numRows, 1), ...
        frequencyHz, mapPower, co2Power, ...
        cleanCbvPower, observedCbvPower, ...
        targetCoherence, realizedCoherence, ...
        'VariableNames', { ...
            'FamilyID', 'Realization', 'DurationSeconds', ...
            'OutputSNRdB', 'FrequencyHz', 'MAPPower', ...
            'PETCO2Power', 'CleanCBFVPower', ...
            'ObservedCBFVPower', 'TargetCoherence', ...
            'RealizedCoherence'});

end

function metadata = createMetadataTable( ...
    simulationResults, family, referencePlan, realizedCoherence)
% createMetadataTable Describe the illustrative family and observation.

    design = simulationResults.familyDesign;
    design = design(design.FamilyID == family.familyId, :);
    metadata = design;
    metadata.Realization = "Training";
    metadata.DurationSeconds = referencePlan.DurationSeconds;
    metadata.OutputSNRdB = referencePlan.OutputSNRdB;
    metadata.MAPInputSNRdB = referencePlan.MAPInputSNRdB;
    metadata.CO2InputSNRdB = referencePlan.CO2InputSNRdB;
    metadata.AlignmentErrorSeconds = ...
        referencePlan.AlignmentErrorSeconds;
    metadata.MeanRealizedInputCoherence = ...
        mean(realizedCoherence, "omitnan");

end

function standardized = standardizeForPlot(values)
% standardizeForPlot Put two differently scaled inputs on one axis.

    values = values(:);
    standardized = ...
        (values - mean(values, "omitnan"))/std(values, "omitnan");

end
