function [figureHandle, sourceData] = plotSimulationOperatingMap( ...
    data, xName, xLabel, xMode, yName, yLabel, yMode, colorLimit, ...
    groupingSettings, statisticsSettings, titleContext)
% plotSimulationOperatingMap Show two-factor MISO operating regions.

    if nargin < 9
        groupingSettings = struct();
    end
    if nargin < 10 || isempty(statisticsSettings)
        statisticsSettings.alpha = 0.05;
        statisticsSettings.minimumValidN = 3;
    end
    if nargin < 11
        titleContext = "";
    end
    if isfield(groupingSettings, "minimumValidN")
        minimumValidN = groupingSettings.minimumValidN;
    else
        minimumValidN = 1;
    end

    outcomes = ["MAPComplexAdvantage"; "CO2ComplexAdvantage"];
    pathwayLabels = ["MAP"; "PETCO2"];

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 2, 2, ...
        "TileSpacing", "compact", "Padding", "compact");
    figureTitle = "Joint effects of " + lower(string(xLabel)) + ...
        " and " + lower(string(yLabel));
    figureSubtitle = ...
        "Mean across families | Black dot: BH-adjusted P < " + ...
        string(statisticsSettings.alpha) + ...
        " | Gray: insufficient N";
    if strlength(titleContext) > 0
        figureSubtitle = figureSubtitle + " | " + titleContext;
    end
    title(layout, figureTitle + newline + figureSubtitle);

    sourceData = struct();
    for outcomeIndex = 1:numel(outcomes)
        summary = summarizeSimulationSurface( ...
            data.(xName), data.(yName), ...
            data.(outcomes(outcomeIndex)), ...
            xName, xMode, yName, yMode, groupingSettings, ...
            statisticsSettings);

        axesHandle = nexttile(layout, outcomeIndex);
        drawAdvantageSurface( ...
            axesHandle, summary, xLabel, yLabel, ...
            colorLimit, minimumValidN, ...
            statisticsSettings.alpha);
        title(axesHandle, compose( ...
            "%s  %s complex-error model advantage", ...
            char('A' + outcomeIndex - 1), ...
            pathwayLabels(outcomeIndex)));
        sourceData.(outcomes(outcomeIndex)) = ...
            createSurfaceSourceTable(summary, "advantage");

        axesHandle = nexttile(layout, outcomeIndex + 2);
        drawProbabilitySurface( ...
            axesHandle, summary, xLabel, yLabel, ...
            minimumValidN);
        title(axesHandle, compose( ...
            "%s  %s fraction with lower MISO error", ...
            char('C' + outcomeIndex - 1), ...
            pathwayLabels(outcomeIndex)));
        fieldName = pathwayLabels(outcomeIndex) + ...
            "FractionMisoLowerError";
        sourceData.(fieldName) = ...
            createSurfaceSourceTable(summary, "fraction");
    end

end

function drawAdvantageSurface( ...
    axesHandle, summary, xLabel, yLabel, colorLimit, minimumValidN, ...
    alpha)
% drawAdvantageSurface Draw one blue-white-orange operating map.

    [plotX, xTicks, xTickLabels] = ...
        prepareSimulationHeatmapAxis(summary.x.labels);
    [plotY, yTicks, yTickLabels] = ...
        prepareSimulationHeatmapAxis(summary.y.labels);
    imageHandle = imagesc( ...
        axesHandle, plotX, plotY, summary.mean);
    imageHandle.AlphaData = isfinite(summary.mean) & ...
        summary.validN >= minimumValidN;
    axesHandle.Color = [0.92 0.92 0.92];
    set(axesHandle, "YDir", "normal");
    colormap(axesHandle, misoAdvantageColormap());
    clim(axesHandle, [-colorLimit colorLimit]);
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Label.String = ...
        "Mean log10(SISO error / MISO error)";
    xlabel(axesHandle, xLabel);
    ylabel(axesHandle, yLabel);
    axesHandle.XTick = xTicks;
    axesHandle.XTickLabel = xTickLabels;
    axesHandle.YTick = yTicks;
    axesHandle.YTickLabel = yTickLabels;
    markSignificantHeatmapCells( ...
        axesHandle, plotX, plotY, summary.bhAdjustedP, alpha);

end

function drawProbabilitySurface( ...
    axesHandle, summary, xLabel, yLabel, minimumValidN)
% drawProbabilitySurface Draw the fraction of families favoring MISO.

    [plotX, xTicks, xTickLabels] = ...
        prepareSimulationHeatmapAxis(summary.x.labels);
    [plotY, yTicks, yTickLabels] = ...
        prepareSimulationHeatmapAxis(summary.y.labels);
    imageHandle = imagesc( ...
        axesHandle, plotX, plotY, summary.fractionPositive);
    imageHandle.AlphaData = ...
        isfinite(summary.fractionPositive) & ...
        summary.validN >= minimumValidN;
    axesHandle.Color = [0.92 0.92 0.92];
    set(axesHandle, "YDir", "normal");
    colormap(axesHandle, parula(256));
    clim(axesHandle, [0 1]);
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Label.String = ...
        "Fraction with lower MISO error";
    xlabel(axesHandle, xLabel);
    ylabel(axesHandle, yLabel);
    axesHandle.XTick = xTicks;
    axesHandle.XTickLabel = xTickLabels;
    axesHandle.YTick = yTicks;
    axesHandle.YTickLabel = yTickLabels;

end

function sourceTable = createSurfaceSourceTable(summary, valueType)
% createSurfaceSourceTable Convert one surface to tidy source data.

    [xGrid, yGrid] = meshgrid( ...
        summary.x.centers, summary.y.centers);
    [xLabelGrid, yLabelGrid] = meshgrid( ...
        summary.x.labels, summary.y.labels);
    if valueType == "advantage"
        values = summary.mean;
        sd = summary.sd;
    else
        values = summary.fractionPositive;
        sd = NaN(size(values));
    end

    sourceTable = table( ...
        xGrid(:), xLabelGrid(:), ...
        yGrid(:), yLabelGrid(:), ...
        values(:), sd(:), ...
        summary.validN(:), summary.groupN(:), ...
        summary.positiveN(:), ...
        'VariableNames', { ...
            'XValue', 'XGroup', 'YValue', 'YGroup', ...
            'Mean', 'SD', 'ValidN', 'GroupN', 'PositiveN'});
    if isfield(summary, "rawP") && valueType == "advantage"
        sourceTable.StandardError = summary.standardError(:);
        sourceTable.CILower = summary.ciLower(:);
        sourceTable.CIUpper = summary.ciUpper(:);
        sourceTable.RawP = summary.rawP(:);
        sourceTable.BHAdjustedP = summary.bhAdjustedP(:);
        sourceTable.IsSignificant = summary.isSignificant(:);
        sourceTable.GeometricSISOToMISOErrorRatio = ...
            summary.geometricSisoToMisoErrorRatio(:);
    end

end
