function [figureHandle, sourceData] = plotNcSimulationCoverage( ...
    simulationResults, ncDiagnostics)
% plotNcSimulationCoverage Show whether NC recordings lie in simulation.

    reference = simulationResults.observations( ...
        simulationResults.observations. ...
        IsFamilyCharacterizationObservation, :);
    main = simulationResults.observations( ...
        simulationResults.observations.IsMainExperiment, :);

    specifications = { ...
        main.DurationSeconds, ncDiagnostics.DurationSeconds, ...
            "Duration (s)", false
        reference.RealizedInputCoherence, ...
            ncDiagnostics.RealizedInputCoherence, ...
            "Input coherence", false
        reference.RealizedPSDShapeOverlap, ...
            ncDiagnostics.RealizedPSDShapeOverlap, ...
            "PSD-shape overlap", false
        reference.RealizedPETCO2ToMAPFluctuationSDRatio, ...
            ncDiagnostics.RealizedPETCO2ToMAPFluctuationSDRatio, ...
            "PETCO2-to-MAP fluctuation SD ratio", true
        reference.MedianNormalizedConditionNumber, ...
            ncDiagnostics.MedianNormalizedConditionNumber, ...
            "Normalized condition number", true
        main.NumWelchWindows, ncDiagnostics.NumWelchWindows, ...
            "Welch windows", false};

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 2, 3, ...
        "TileSpacing", "compact", "Padding", "compact");
    title(layout, ...
        "Coverage of observable NC recording properties by simulation");

    for panelIndex = 1:size(specifications, 1)
        axesHandle = nexttile(layout);
        simulationValues = specifications{panelIndex, 1};
        ncValues = specifications{panelIndex, 2};
        histogram(axesHandle, simulationValues, ...
            "Normalization", "probability", ...
            "FaceColor", [0.75 0.82 0.90], ...
            "EdgeColor", "none");
        hold(axesHandle, "on");
        for ncIndex = 1:numel(ncValues)
            xline(axesHandle, ncValues(ncIndex), ...
                "Color", [0.95 0.72 0.58], ...
                "LineWidth", 0.6, "HandleVisibility", "off");
        end
        xline(axesHandle, median(ncValues, "omitnan"), ...
            "Color", [0.85 0.33 0.10], ...
            "LineWidth", 2, "Label", "NC median");
        if specifications{panelIndex, 4}
            set(axesHandle, "XScale", "log");
        end
        xlabel(axesHandle, specifications{panelIndex, 3});
        ylabel(axesHandle, "Simulation proportion");
        title(axesHandle, string(char('A' + panelIndex - 1)));
        grid(axesHandle, "on");
    end

    sourceData.simulationReference = reference;
    sourceData.simulationMain = main;
    sourceData.nc = ncDiagnostics;

end
