function [figureHandle, sourceData] = ...
    plotNcOperatingMapPlacement( ...
        simulationResults, ncDiagnostics, colorLimit)
% plotNcOperatingMapPlacement Overlay NC recordings on simulation maps.

    observations = simulationResults.observations;
    settings = simulationResults.settings;
    reference = observations( ...
        observations.IsReferenceObservation, :);
    resolvedReferenceSnr = unique(reference.OutputSNRdB);
    mainReferenceSnr = observations( ...
        observations.IsMainExperiment & ...
        observations.OutputSNRdB == resolvedReferenceSnr(1), :);

    figureHandle = figure( ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 1, 2, ...
        "TileSpacing", "compact", "Padding", "compact");
    title(layout, ...
        "NC recordings placed within the simulated operating space");

    axesHandle = nexttile(layout);
    summary1 = drawPlacementSurface( ...
        axesHandle, mainReferenceSnr, ...
        "DurationSeconds", "exact", ...
        "FamilyInputCoherence", "binned", ...
        colorLimit, settings.grouping);
    hold(axesHandle, "on");
    scatter(axesHandle, mapExactValuesToGroupAxis( ...
            ncDiagnostics.DurationSeconds, summary1.x), ...
        mapValuesToGroupAxis( ...
            ncDiagnostics.RealizedInputCoherence, summary1.y), ...
        30, [0.10 0.10 0.10], "filled", ...
        "MarkerEdgeColor", "white");
    xlabel(axesHandle, "Duration (s)");
    ylabel(axesHandle, "Family mean MAP-PETCO2 coherence");
    title(axesHandle, "A  NC on duration-coherence map");

    axesHandle = nexttile(layout);
    summary2 = drawPlacementSurface( ...
        axesHandle, reference, ...
        "FamilyInputCoherence", "binned", ...
        "FamilyPSDShapeOverlap", "binned", ...
        colorLimit, settings.grouping);
    hold(axesHandle, "on");
    scatter(axesHandle, ...
        mapValuesToGroupAxis( ...
            ncDiagnostics.RealizedInputCoherence, summary2.x), ...
        mapValuesToGroupAxis( ...
            ncDiagnostics.RealizedPSDShapeOverlap, summary2.y), ...
        30, [0.10 0.10 0.10], "filled", ...
        "MarkerEdgeColor", "white");
    xlabel(axesHandle, "Family mean MAP-PETCO2 coherence");
    ylabel(axesHandle, ...
        "PSD-shape overlap (Bhattacharyya coefficient)");
    title(axesHandle, "B  NC on input-identifiability map");

    sourceData.durationCoherence = surfaceSource(summary1);
    sourceData.coherenceOverlap = surfaceSource(summary2);
    sourceData.nc = ncDiagnostics;

end

function summary = drawPlacementSurface( ...
    axesHandle, data, xName, xMode, yName, yMode, ...
    colorLimit, groupingSettings)
% drawPlacementSurface Draw one MAP complex-advantage background.

    summary = summarizeSimulationSurface( ...
        data.(xName), data.(yName), ...
        data.MAPComplexAdvantage, ...
        xName, xMode, yName, yMode, groupingSettings);
    [plotX, xTicks, xLabels] = ...
        prepareSimulationHeatmapAxis(summary.x.labels);
    [plotY, yTicks, yLabels] = ...
        prepareSimulationHeatmapAxis(summary.y.labels);
    imageHandle = imagesc( ...
        axesHandle, plotX, plotY, summary.mean);
    imageHandle.AlphaData = isfinite(summary.mean) & ...
        summary.validN >= groupingSettings.minimumValidN;
    axesHandle.Color = [0.92 0.92 0.92];
    set(axesHandle, "YDir", "normal");
    axesHandle.XTick = xTicks;
    axesHandle.XTickLabel = xLabels;
    axesHandle.YTick = yTicks;
    axesHandle.YTickLabel = yLabels;
    colormap(axesHandle, misoAdvantageColormap());
    clim(axesHandle, [-colorLimit colorLimit]);
    colorbarHandle = colorbar(axesHandle);
    colorbarHandle.Label.String = ...
        "Mean MAP model advantage";

end

function plotValues = mapExactValuesToGroupAxis(values, groups)
% mapExactValuesToGroupAxis Place numeric values between exact cell centers.

    plotValues = interp1( ...
        groups.centers, (1:numel(groups.centers))', values, ...
        "linear", "extrap");

end

function plotValues = mapValuesToGroupAxis(values, groups)
% mapValuesToGroupAxis Place continuous NC values in interval rows.

    edges = [groups.lowerEdges(:); groups.upperEdges(end)];
    plotValues = discretize(values, edges);

end

function output = surfaceSource(summary)
% surfaceSource Convert one map into a tidy source table.

    [xGrid, yGrid] = meshgrid( ...
        summary.x.centers, summary.y.centers);
    output = table( ...
        xGrid(:), yGrid(:), summary.mean(:), ...
        summary.sd(:), summary.validN(:), summary.groupN(:), ...
        'VariableNames', { ...
            'XValue', 'YValue', 'Mean', 'SD', ...
            'ValidN', 'GroupN'});

end
