function subjectResults = runSelectedWorkflow( ...
    outputFolder, runMISO, runSISO)
% runSelectedWorkflow Run the subject workflow with selected test models.

    [analysisSettings, outputSettings] = createWorkflowTestSettings( ...
        outputFolder, runMISO, runSISO);
    runResults = runTFA( ...
        "synthetic", struct(), struct(), ...
        analysisSettings, outputSettings);
    subjectResults = runResults.subjectResults{1};

end
