function [manifestRows, savedFiles] = ...
    exportSimulationFactorPlotSet( ...
        simulationResults, dataRows, factorName, factorLabel, ...
        groupingMode, groupFolder, groupNumber, ...
        plotPrefix, exportSettings, titleContext)
% exportSimulationFactorPlotSet Export the standard five-figure set.

    if nargin < 10
        titleContext = "";
    end
    data = simulationResults.observations(dataRows, :);
    groupingSettings = simulationResults.settings.grouping;
    factorTitle = getSimulationFactorTitle( ...
        factorName, factorLabel);
    manifestCells = cell(5, 1);
    savedFileCells = cell(5, 1);

    [figureHandle, sourceData] = plotSimulationFactorErrors( ...
        data, factorName, factorLabel, ...
        groupingMode, ...
        groupingSettings, titleContext, ...
        simulationResults.settings.statistics);
    [manifestCells{1}, savedFileCells{1}] = ...
        exportApproachPaperPlot( ...
            figureHandle, sourceData, groupFolder, groupNumber, ...
            plotPrefix + "_overall_complex_error", ...
            "Overall complex error and model advantage by " + ...
                factorTitle, ...
            exportSettings);
    closeApproachFigure(figureHandle);

    [figureHandle, sourceData] = ...
        plotSimulationFactorAbsoluteFrequencyMaps( ...
            simulationResults, dataRows, factorName, factorLabel, ...
            groupingMode, "miso", titleContext);
    [manifestCells{2}, savedFileCells{2}] = ...
        exportApproachPaperPlot( ...
            figureHandle, sourceData, groupFolder, groupNumber, ...
            plotPrefix + "_miso_frequency_error", ...
            "Mean frequency-resolved MISO error by " + ...
                factorTitle, ...
            exportSettings);
    closeApproachFigure(figureHandle);

    [figureHandle, sourceData] = ...
        plotSimulationFactorAbsoluteFrequencyMaps( ...
            simulationResults, dataRows, factorName, factorLabel, ...
            groupingMode, "siso", titleContext);
    [manifestCells{3}, savedFileCells{3}] = ...
        exportApproachPaperPlot( ...
            figureHandle, sourceData, groupFolder, groupNumber, ...
            plotPrefix + "_siso_frequency_error", ...
            "Mean frequency-resolved SISO error by " + ...
                factorTitle, ...
            exportSettings);
    closeApproachFigure(figureHandle);

    [figureHandle, sourceData] = ...
        plotSimulationFactorFrequencyMaps( ...
            simulationResults, dataRows, factorName, ...
            factorLabel, groupingMode, ...
            exportSettings.advantageColorLimit, titleContext);
    [manifestCells{4}, savedFileCells{4}] = ...
        exportApproachPaperPlot( ...
            figureHandle, sourceData, groupFolder, groupNumber, ...
            plotPrefix + "_frequency_model_advantage", ...
            "Mean frequency-resolved model advantage by " + ...
                factorTitle, ...
            exportSettings);
    closeApproachFigure(figureHandle);

    [figureHandle, sourceData] = ...
        plotSimulationFactorComponents( ...
            data, factorName, factorLabel, groupingMode, ...
            groupingSettings, titleContext, ...
            simulationResults.settings.statistics);
    [manifestCells{5}, savedFileCells{5}] = ...
        exportApproachPaperPlot( ...
            figureHandle, sourceData, groupFolder, groupNumber, ...
            plotPrefix + "_gain_phase_consistency", ...
            "Whole-range gain and phase model advantage by " + ...
                factorTitle, ...
            exportSettings);
    closeApproachFigure(figureHandle);

    manifestRows = vertcat(manifestCells{:});
    savedFiles = vertcat(savedFileCells{:});

end
