function [manifestRows, savedFiles] = ...
    exportEstimatorSettingPlotSet( ...
        summaryData, frequencyData, factorName, factorLabel, ...
        groupFolder, groupNumber, plotPrefix, ...
        simulationSettings, exportSettings, titleContext)
% exportEstimatorSettingPlotSet Export the standard Welch sensitivity set.

    manifestParts = cell(5, 1);
    savedParts = cell(5, 1);

    [figureHandle, sourceData] = plotSimulationFactorErrors( ...
        summaryData, factorName, factorLabel, "exact", ...
        simulationSettings.grouping, titleContext, ...
        simulationSettings.statistics);
    [manifestParts{1}, savedParts{1}] = exportApproachPaperPlot( ...
        figureHandle, sourceData, groupFolder, groupNumber, ...
        plotPrefix + "_overall_complex_error", ...
        "Whole-range complex error and model advantage by " + ...
            lower(factorLabel), exportSettings);
    closeApproachFigure(figureHandle);

    displayModes = ["miso" "siso" "advantage"];
    suffixes = [ ...
        "miso_frequency_error"
        "siso_frequency_error"
        "frequency_model_advantage"];
    descriptions = [ ...
        "Frequency-resolved MISO error by "
        "Frequency-resolved SISO error by "
        "Frequency-resolved model advantage by "];
    for modeIndex = 1:numel(displayModes)
        [figureHandle, sourceData] = plotEstimatorFrequencyMaps( ...
            frequencyData, factorName, factorLabel, ...
            displayModes(modeIndex), ...
            simulationSettings.grouping.minimumValidN, ...
            exportSettings.advantageColorLimit, titleContext, ...
            simulationSettings.frequencyRangeHz, ...
            simulationSettings.statistics);
        [manifestParts{modeIndex + 1}, savedParts{modeIndex + 1}] = ...
            exportApproachPaperPlot( ...
                figureHandle, sourceData, groupFolder, groupNumber, ...
                plotPrefix + "_" + suffixes(modeIndex), ...
                descriptions(modeIndex) + lower(factorLabel), ...
                exportSettings);
        closeApproachFigure(figureHandle);
    end

    [figureHandle, sourceData] = plotSimulationFactorComponents( ...
        summaryData, factorName, factorLabel, "exact", ...
        simulationSettings.grouping, titleContext, ...
        simulationSettings.statistics);
    [manifestParts{5}, savedParts{5}] = exportApproachPaperPlot( ...
        figureHandle, sourceData, groupFolder, groupNumber, ...
        plotPrefix + "_gain_phase_fraction", ...
        "Whole-range gain, phase, and lower-error fraction by " + ...
            lower(factorLabel), exportSettings);
    closeApproachFigure(figureHandle);

    manifestRows = vertcat(manifestParts{:});
    savedFiles = vertcat(savedParts{:});

end
