function plotResults = exportApproachPaperPlotGroups( ...
    paperResults, analysisSettings, settings)
% exportApproachPaperPlotGroups Build the organized Paper 1 plot library.

    groupDefinitions = approachPlotGroupDefinitions();
    figuresRoot = fullfile(settings.outputFolder, "Figures");
    if ~exist(figuresRoot, "dir")
        mkdir(figuresRoot);
    end
    for groupIndex = 1:height(groupDefinitions)
        ensureGroupFolders(fullfile( ...
            figuresRoot, groupDefinitions.FolderName(groupIndex)));
    end

    manifestParts = cell(0, 1);
    savedFileParts = cell(0, 1);

    %% Group 1: Simulated System

    fprintf("Creating plot group 01: Simulated System.\n");
    groupFolder = getGroupFolder(figuresRoot, groupDefinitions, 1);
    figureHandle = plotApproachFigure1Concept();
    [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
        exportApproachPaperPlot( ...
            figureHandle, table(), groupFolder, 1, ...
            "G01_P01_siso_miso_concept", ...
            "SISO and MISO conceptual comparison", settings.export);
    closeApproachFigure(figureHandle);

    hasSimulation = isfield(paperResults, "simulation") && ...
        ~isempty(fieldnames(paperResults.simulation));
    if hasSimulation
        simulation = paperResults.simulation;
        [figureHandle, sourceData] = ...
            plotSimulationSystemExample(simulation);
        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportApproachPaperPlot( ...
                figureHandle, sourceData, groupFolder, 1, ...
                "G01_P02_example_family", ...
                "Anatomy of one illustrative simulated family", ...
                settings.export);
        closeApproachFigure(figureHandle);

        [figureHandle, sourceData] = ...
            plotSimulationTransferFunctionExamples(simulation);
        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportApproachPaperPlot( ...
                figureHandle, sourceData, groupFolder, 1, ...
                "G01_P03_truth_miso_siso_transfer_functions", ...
                "True, MISO, and SISO transfer-function examples", ...
                settings.export);
        closeApproachFigure(figureHandle);

        %% Shared Simulation Selections

        observations = simulation.observations;
        simulationSettings = simulation.settings;
        referenceDuration = ...
            simulationSettings.observations.referenceDurationSeconds;
        mainRows = observations.IsMainExperiment;
        referenceRows = observations.IsReferenceObservation;
        referenceSnr = unique( ...
            observations.OutputSNRdB(referenceRows));
        referenceSnr = referenceSnr(1);
        standardContext = compose( ...
            "Recording duration: %.3g s | Welch: %.3g s, %.0f%% overlap", ...
            referenceDuration, ...
            simulationSettings.welch.windowLengthSeconds, ...
            100*simulationSettings.welch.windowOverlap);
        durationContext = compose( ...
            "CBFV output SNR: %.3g dB | Welch: %.3g s, %.0f%% overlap", ...
            referenceSnr, simulationSettings.welch.windowLengthSeconds, ...
            100*simulationSettings.welch.windowOverlap);

        %% Group 2: Generator Validation

        fprintf("Creating plot group 02: Generator Validation.\n");
        groupFolder = getGroupFolder( ...
            figuresRoot, groupDefinitions, 2);
        [figureHandle, sourceData] = ...
            plotSimulationGeneratorValidation(simulation);
        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportApproachPaperPlot( ...
                figureHandle, sourceData, groupFolder, 2, ...
                "G02_P01_target_realized_validation", ...
                "Assigned and realized simulation properties", ...
                settings.export);
        closeApproachFigure(figureHandle);

        [figureHandle, sourceData] = ...
            plotSimulationFamilyCoherenceSpectra(simulation);
        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportApproachPaperPlot( ...
                figureHandle, sourceData, groupFolder, 2, ...
                "G02_P02_family_coherence_spectra", ...
                "Frequency-resolved family input coherence", ...
                settings.export);
        closeApproachFigure(figureHandle);

        [figureHandle, sourceData] = ...
            plotSimulationReferenceStatistics(simulation);
        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportApproachPaperPlot( ...
                figureHandle, sourceData, groupFolder, 2, ...
                "G02_P03_reference_model_statistics", ...
                "Reference-condition MISO versus SISO statistics", ...
                settings.export);
        closeApproachFigure(figureHandle);

        %% Groups 3 through 13: One-Factor Simulation Results

        durationRows = mainRows & ...
            observations.OutputSNRdB == referenceSnr;
        [currentManifest, currentFiles] = exportFactorGroup( ...
            simulation, durationRows, "DurationSeconds", ...
            "Recording duration (s)", "exact", 3, "G03_duration", ...
            durationContext, figuresRoot, groupDefinitions, settings.export);
        manifestParts{end + 1,1} = currentManifest;
        savedFileParts{end + 1,1} = currentFiles;

        outputNoiseRows = mainRows & ...
            observations.DurationSeconds == referenceDuration;
        [currentManifest, currentFiles] = exportFactorGroup( ...
            simulation, outputNoiseRows, "OutputSNRdB", ...
            "CBFV measurement SNR (dB)", "exact", 4, ...
            "G04_cbfv_output_noise", standardContext, ...
            figuresRoot, groupDefinitions, settings.export);
        manifestParts{end + 1,1} = currentManifest;
        savedFileParts{end + 1,1} = currentFiles;

        mapNoiseRows = observations.Experiment == "MAP input noise";
        if any(mapNoiseRows)
            [currentManifest, currentFiles] = exportFactorGroup( ...
                simulation, mapNoiseRows, "MAPInputSNRdB", ...
                "MAP measurement SNR (dB)", "exact", 5, ...
                "G05_map_measurement_noise", standardContext, ...
                figuresRoot, groupDefinitions, settings.export);
            manifestParts{end + 1,1} = currentManifest;
            savedFileParts{end + 1,1} = currentFiles;
        end

        co2NoiseRows = observations.Experiment == "CO2 input noise";
        if any(co2NoiseRows)
            [currentManifest, currentFiles] = exportFactorGroup( ...
                simulation, co2NoiseRows, "CO2InputSNRdB", ...
                "PETCO2 measurement SNR (dB)", "exact", 6, ...
                "G06_petco2_measurement_noise", standardContext, ...
                figuresRoot, groupDefinitions, settings.export);
            manifestParts{end + 1,1} = currentManifest;
            savedFileParts{end + 1,1} = currentFiles;
        end

        [currentManifest, currentFiles] = exportFactorGroup( ...
            simulation, referenceRows, "FamilyInputCoherence", ...
            "Family mean MAP-PETCO2 coherence", "binned", 7, ...
            "G07_input_coherence", standardContext, ...
            figuresRoot, groupDefinitions, settings.export);
        manifestParts{end + 1,1} = currentManifest;
        savedFileParts{end + 1,1} = currentFiles;

        groupFolder = getGroupFolder( ...
            figuresRoot, groupDefinitions, 7);
        [figureHandle, sourceData] = plotSimulationConditioning( ...
            observations(referenceRows,:), standardContext);
        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportApproachPaperPlot( ...
                figureHandle, sourceData, groupFolder, 7, ...
                "G07_conditioning_diagnostics", ...
                "Input coherence, conditioning, and MISO error", ...
                settings.export);
        closeApproachFigure(figureHandle);

        [currentManifest, currentFiles] = exportFactorGroup( ...
            simulation, referenceRows, "FamilyPSDShapeOverlap", ...
            "PSD-shape overlap (Bhattacharyya coefficient)", ...
            "binned", 8, "G08_psd_shape_overlap", standardContext, ...
            figuresRoot, groupDefinitions, settings.export);
        manifestParts{end + 1,1} = currentManifest;
        savedFileParts{end + 1,1} = currentFiles;

        [currentManifest, currentFiles] = exportFactorGroup( ...
            simulation, referenceRows, ...
            "AssignedPETCO2ToMAPFluctuationSDRatio", ...
            "Assigned PETCO2-to-MAP fluctuation SD ratio", ...
            "exact", 9, "G09_fluctuation_sd_ratio", standardContext, ...
            figuresRoot, groupDefinitions, settings.export);
        manifestParts{end + 1,1} = currentManifest;
        savedFileParts{end + 1,1} = currentFiles;

        [currentManifest, currentFiles] = exportFactorGroup( ...
            simulation, referenceRows, ...
            "AssignedPETCO2ToMAPBandGainRatio", ...
            "Assigned PETCO2-to-MAP pathway band-gain ratio", ...
            "exact", 10, "G10_pathway_band_gain_ratio", ...
            standardContext, figuresRoot, groupDefinitions, ...
            settings.export);
        manifestParts{end + 1,1} = currentManifest;
        savedFileParts{end + 1,1} = currentFiles;

        [currentManifest, currentFiles] = exportFactorGroup( ...
            simulation, referenceRows, ...
            "FamilyPETCO2ContributionPowerShare", ...
            "Realized PETCO2 contribution-power share", ...
            "binned", 11, "G11_contribution_power_share", ...
            standardContext, figuresRoot, groupDefinitions, ...
            settings.export);
        manifestParts{end + 1,1} = currentManifest;
        savedFileParts{end + 1,1} = currentFiles;

        [currentManifest, currentFiles] = exportFactorGroup( ...
            simulation, referenceRows, "CO2DelaySeconds", ...
            "True PETCO2 response delay (s)", "exact", 12, ...
            "G12_true_petco2_delay", standardContext, ...
            figuresRoot, groupDefinitions, settings.export);
        manifestParts{end + 1,1} = currentManifest;
        savedFileParts{end + 1,1} = currentFiles;

        alignmentRows = observations.Experiment == "Alignment";
        if any(alignmentRows)
            [currentManifest, currentFiles] = exportFactorGroup( ...
                simulation, alignmentRows, "AlignmentErrorSeconds", ...
                "Applied PETCO2 timing misalignment (s)", "exact", 13, ...
                "G13_petco2_timing_misalignment", standardContext, ...
                figuresRoot, groupDefinitions, settings.export);
            manifestParts{end + 1,1} = currentManifest;
            savedFileParts{end + 1,1} = currentFiles;
        end

        %% Group 14: Ridge Regularization

        if ~isempty(simulation.ridge)
            fprintf("Creating plot group 14: Ridge Regularization.\n");
            groupFolder = getGroupFolder( ...
                figuresRoot, groupDefinitions, 14);
            [figureHandle, sourceData] = ...
                plotSimulationRidgeResults( ...
                    simulation.ridge, standardContext, ...
                    simulationSettings.statistics);
            [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
                exportApproachPaperPlot( ...
                    figureHandle, sourceData, groupFolder, 14, ...
                    "G14_ridge_overall", ...
                    "Ridge error and lower-error fraction", ...
                    settings.export);
            closeApproachFigure(figureHandle);

            ridgeContext = standardContext + ...
                " | MISO is the standardized ridge estimate";
            [figureHandle, sourceData] = plotEstimatorFrequencyMaps( ...
                simulation.ridgeFrequency, "Lambda", "Ridge lambda", ...
                "miso", simulationSettings.grouping.minimumValidN, ...
                settings.export.advantageColorLimit, ridgeContext, ...
                simulationSettings.frequencyRangeHz, ...
                simulationSettings.statistics);
            [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
                exportApproachPaperPlot( ...
                    figureHandle, sourceData, groupFolder, 14, ...
                    "G14_ridge_frequency_error", ...
                    "Frequency-resolved ridge-MISO error", ...
                    settings.export);
            closeApproachFigure(figureHandle);

            [figureHandle, sourceData] = plotEstimatorFrequencyMaps( ...
                simulation.ridgeFrequency, "Lambda", "Ridge lambda", ...
                "advantage", simulationSettings.grouping.minimumValidN, ...
                settings.export.advantageColorLimit, ridgeContext, ...
                simulationSettings.frequencyRangeHz, ...
                simulationSettings.statistics);
            [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
                exportApproachPaperPlot( ...
                    figureHandle, sourceData, groupFolder, 14, ...
                    "G14_ridge_frequency_model_advantage", ...
                    "Frequency-resolved ridge model advantage", ...
                    settings.export);
            closeApproachFigure(figureHandle);

            [figureHandle, sourceData] = ...
                plotSimulationRidgeConditioning( ...
                    simulation.ridge, standardContext);
            [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
                exportApproachPaperPlot( ...
                    figureHandle, sourceData, groupFolder, 14, ...
                    "G14_ridge_effective_conditioning", ...
                    "Effective conditioning after ridge regularization", ...
                    settings.export);
            closeApproachFigure(figureHandle);
        end

        %% Groups 15 and 16: Welch Settings

        estimatorSummary = simulation.estimatorSettings;
        estimatorFrequency = simulation.estimatorFrequency;
        if ~isempty(estimatorSummary)
            fprintf("Creating plot group 15: Welch Window Length.\n");
            windowRows = estimatorSummary.Sweep == "Window length";
            windowFrequencyRows = ...
                estimatorFrequency.Sweep == "Window length";
            groupFolder = getGroupFolder( ...
                figuresRoot, groupDefinitions, 15);
            windowContext = compose( ...
                "Recording duration: %.3g s | Overlap fixed at %.0f%% | * below %d-window primary criterion", ...
                referenceDuration, ...
                100*simulationSettings.welch.windowOverlap, ...
                simulationSettings.welch.minimumWindows);
            [currentManifest, currentFiles] = ...
                exportEstimatorSettingPlotSet( ...
                    estimatorSummary(windowRows,:), ...
                    estimatorFrequency(windowFrequencyRows,:), ...
                    "WelchWindowLengthSeconds", ...
                    "Welch window length (s)", groupFolder, 15, ...
                    "G15_welch_window_length", simulationSettings, ...
                    settings.export, windowContext);
            manifestParts{end + 1,1} = currentManifest;
            savedFileParts{end + 1,1} = currentFiles;

            overlapRows = estimatorSummary.Sweep == "Window overlap";
            overlapFrequencyRows = ...
                estimatorFrequency.Sweep == "Window overlap";
            groupFolder = getGroupFolder( ...
                figuresRoot, groupDefinitions, 16);
            fprintf("Creating plot group 16: Welch Window Overlap.\n");
            overlapContext = compose( ...
                "Recording duration: %.3g s | Window fixed at %.3g s | * below %d-window primary criterion", ...
                referenceDuration, ...
                simulationSettings.welch.windowLengthSeconds, ...
                simulationSettings.welch.minimumWindows);
            [currentManifest, currentFiles] = ...
                exportEstimatorSettingPlotSet( ...
                    estimatorSummary(overlapRows,:), ...
                    estimatorFrequency(overlapFrequencyRows,:), ...
                    "WelchWindowOverlap", "Welch window overlap", ...
                    groupFolder, 16, "G16_welch_window_overlap", ...
                    simulationSettings, settings.export, overlapContext);
            manifestParts{end + 1,1} = currentManifest;
            savedFileParts{end + 1,1} = currentFiles;
        end

        %% Groups 17 through 20: Focused Interactions

        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportOperatingMap( ...
                observations(referenceRows,:), ...
                "FamilyInputCoherence", ...
                "Family mean MAP-PETCO2 coherence", "binned", ...
                "FamilyPSDShapeOverlap", ...
                "PSD-shape overlap", "binned", ...
                17, "G17_coherence_by_psd_overlap", ...
                "Input coherence by PSD-shape overlap", ...
                standardContext, figuresRoot, groupDefinitions, ...
                simulationSettings, settings.export);

        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportOperatingMap( ...
                observations(referenceRows,:), ...
                "AssignedPETCO2ToMAPFluctuationSDRatio", ...
                "PETCO2-to-MAP fluctuation SD ratio", "exact", ...
                "AssignedPETCO2ToMAPBandGainRatio", ...
                "PETCO2-to-MAP pathway band-gain ratio", "exact", ...
                18, "G18_fluctuation_by_pathway_gain", ...
                "Input fluctuation ratio by pathway band-gain ratio", ...
                standardContext, figuresRoot, groupDefinitions, ...
                simulationSettings, settings.export);

        interactionRows = ...
            estimatorSummary.Sweep == "Duration by window";
        if any(interactionRows)
            [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
                exportOperatingMap( ...
                    estimatorSummary(interactionRows,:), ...
                    "DurationSeconds", "Recording duration (s)", "exact", ...
                    "WelchWindowLengthSeconds", ...
                    "Welch window length (s)", "exact", ...
                    19, "G19_duration_by_welch_window", ...
                    "Recording duration by Welch window length", ...
                    "Overlap fixed at " + ...
                        string(100*simulationSettings.welch.windowOverlap) + ...
                        "%", ...
                    figuresRoot, groupDefinitions, ...
                    simulationSettings, settings.export);
        end

        if any(alignmentRows)
            [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
                exportOperatingMap( ...
                    observations(alignmentRows,:), ...
                    "CO2DelaySeconds", ...
                    "True PETCO2 response delay (s)", "exact", ...
                    "AlignmentErrorSeconds", ...
                    "Applied PETCO2 timing misalignment (s)", "exact", ...
                    20, "G20_delay_by_misalignment", ...
                    "True PETCO2 delay by applied timing misalignment", ...
                    standardContext, figuresRoot, groupDefinitions, ...
                    simulationSettings, settings.export);
        end
    end

    %% Groups 21 through 24: NC Results

    hasEmpirical = isfield(paperResults, "empirical") && ...
        ~isempty(fieldnames(paperResults.empirical));
    if hasEmpirical
        if hasSimulation
            ncDiagnostics = createNcDiagnosticTable( ...
                paperResults.empirical, ...
                analysisSettings.frequencyRangeHz);
            if ~isempty(ncDiagnostics)
                groupFolder = getGroupFolder( ...
                    figuresRoot, groupDefinitions, 21);
                [figureHandle, sourceData] = ...
                    plotNcSimulationCoverage( ...
                        paperResults.simulation, ncDiagnostics);
                [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
                    exportApproachPaperPlot( ...
                        figureHandle, sourceData, groupFolder, 21, ...
                        "G21_nc_simulation_coverage", ...
                        "Simulation coverage of NC recordings", ...
                        settings.export);
                closeApproachFigure(figureHandle);

                groupFolder = getGroupFolder( ...
                    figuresRoot, groupDefinitions, 22);
                [figureHandle, sourceData] = ...
                    plotNcOperatingMapPlacement( ...
                        paperResults.simulation, ncDiagnostics, ...
                        settings.export.advantageColorLimit);
                [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
                    exportApproachPaperPlot( ...
                        figureHandle, sourceData, groupFolder, 22, ...
                        "G22_nc_operating_map_placement", ...
                        "NC recordings on simulation operating maps", ...
                        settings.export);
                closeApproachFigure(figureHandle);
            end
        end

        groupFolder = getGroupFolder( ...
            figuresRoot, groupDefinitions, 23);
        [figureHandle, sourceData] = plotApproachFigure5NcComparison( ...
            paperResults.empirical, analysisSettings);
        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportApproachPaperPlot( ...
                figureHandle, sourceData, groupFolder, 23, ...
                "G23_nc_map_gain", ...
                "NC MAP gain comparison", settings.export);
        closeApproachFigure(figureHandle);

        frequencyResults = paperResults.empirical. ...
            statisticalResults.frequencyModelComparisons;
        if ~isempty(frequencyResults) && ...
                any(frequencyResults.Metric == "Phase")
            [figureHandle, sourceData] = ...
                plotApproachFrequencyPhaseComparison(frequencyResults);
            [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
                exportApproachPaperPlot( ...
                    figureHandle, sourceData, groupFolder, 23, ...
                    "G23_nc_frequency_phase", ...
                    "NC frequency-wise phase comparison", ...
                    settings.export);
            closeApproachFigure(figureHandle);
        end
    end

    hasRobustness = isfield(paperResults, "robustness") && ...
        ~isempty(fieldnames(paperResults.robustness));
    if hasRobustness
        groupFolder = getGroupFolder( ...
            figuresRoot, groupDefinitions, 24);
        [figureHandle, sourceData] = ...
            plotApproachFigure6Robustness(paperResults.robustness);
        [manifestParts{end + 1,1}, savedFileParts{end + 1,1}] = ...
            exportApproachPaperPlot( ...
                figureHandle, sourceData, groupFolder, 24, ...
                "G24_nc_robustness", ...
                "NC robustness and falsification checks", ...
                settings.export);
        closeApproachFigure(figureHandle);
    end

    manifest = vertcat(manifestParts{:});
    manifest.GroupFolder = strings(height(manifest), 1);
    for rowIndex = 1:height(manifest)
        manifest.GroupFolder(rowIndex) = getGroupFolder( ...
            figuresRoot, groupDefinitions, ...
            manifest.GroupNumber(rowIndex));
    end
    manifest = movevars( ...
        manifest, "GroupFolder", "After", "GroupNumber");
    manifestFile = fullfile(figuresRoot, "figure_manifest.csv");
    writetable(manifest, manifestFile);

    plotResults.manifest = manifest;
    plotResults.manifestFile = string(manifestFile);
    plotResults.savedFiles = vertcat(savedFileParts{:});
    plotResults.groupDefinitions = groupDefinitions;

end

function [manifestRows, savedFiles] = exportFactorGroup( ...
    simulation, rows, factorName, factorLabel, groupingMode, ...
    groupNumber, plotPrefix, titleContext, figuresRoot, ...
    groupDefinitions, exportSettings)
% exportFactorGroup Export one standard five-figure factor set.

    fprintf("Creating plot group %02d: %s.\n", ...
        groupNumber, getSimulationFactorTitle(factorName, factorLabel));
    groupFolder = getGroupFolder( ...
        figuresRoot, groupDefinitions, groupNumber);
    [manifestRows, savedFiles] = exportSimulationFactorPlotSet( ...
        simulation, rows, factorName, factorLabel, groupingMode, ...
        groupFolder, groupNumber, plotPrefix, ...
        exportSettings, titleContext);

end

function [manifestRow, savedFiles] = exportOperatingMap( ...
    data, xName, xLabel, xMode, yName, yLabel, yMode, ...
    groupNumber, plotName, description, titleContext, ...
    figuresRoot, groupDefinitions, simulationSettings, exportSettings)
% exportOperatingMap Export one named two-factor interaction.

    fprintf("Creating plot group %02d: %s.\n", ...
        groupNumber, description);
    [figureHandle, sourceData] = plotSimulationOperatingMap( ...
        data, xName, xLabel, xMode, yName, yLabel, yMode, ...
        exportSettings.advantageColorLimit, ...
        simulationSettings.grouping, ...
        simulationSettings.statistics, titleContext);
    groupFolder = getGroupFolder( ...
        figuresRoot, groupDefinitions, groupNumber);
    [manifestRow, savedFiles] = exportApproachPaperPlot( ...
        figureHandle, sourceData, groupFolder, groupNumber, ...
        plotName, description, exportSettings);
    closeApproachFigure(figureHandle);

end

function ensureGroupFolders(groupFolder)
% ensureGroupFolders Create the requested plot and source-data structure.

    plotFolder = fullfile(groupFolder, "Plots");
    sourceFolder = fullfile(groupFolder, "Source_Data");
    if ~exist(plotFolder, "dir")
        mkdir(plotFolder);
    end
    if ~exist(sourceFolder, "dir")
        mkdir(sourceFolder);
    end

end

function groupFolder = getGroupFolder( ...
    figuresRoot, groupDefinitions, groupNumber)
% getGroupFolder Resolve one stable numbered output folder.

    row = groupDefinitions.GroupNumber == groupNumber;
    groupFolder = fullfile( ...
        figuresRoot, groupDefinitions.FolderName(row));

end
