function [figureHandle, sourceData] = plotApproachFigure5NcComparison( ...
    empiricalResults, analysisSettings)
% plotApproachFigure5NcComparison Show the NC SISO and MISO MAP results.

    ncMiso = empiricalResults.groupResults.NC.miso;
    ncSiso = empiricalResults.groupResults.NC.siso;
    [commonSubjectIds, misoIndices, sisoIndices] = intersect( ...
        ncMiso.subjectIds, ncSiso.subjectIds, "stable");
    frequencyHz = ncMiso.f(:);
    misoValues = ncMiso.map.gain.values(:,misoIndices);
    sisoValues = ncSiso.map.gain.values(:,sisoIndices);
    differenceValues = misoValues - sisoValues;

    colors.miso = [0 0.4470 0.7410];
    colors.siso = [0.8500 0.3250 0.0980];
    colors.difference = [0.25 0.25 0.25];

    figureHandle = figure( ...
        "Name", "Approach Paper Figure 5", ...
        "Color", "white", "Visible", "off");
    layout = tiledlayout(figureHandle, 2, 2, ...
        "TileSpacing", "compact", "Padding", "compact");

    axesHandle = nexttile(layout);
    misoSummary = plotMeanAndConfidenceInterval( ...
        axesHandle, frequencyHz, misoValues, colors.miso, "MISO");
    sisoSummary = plotMeanAndConfidenceInterval( ...
        axesHandle, frequencyHz, sisoValues, colors.siso, "SISO");
    xlabel(axesHandle, "Frequency (Hz)");
    ylabel(axesHandle, "MAP gain");
    title(axesHandle, "A  NC MAP gain with 95% confidence intervals");
    legend(axesHandle, "Location", "best");
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    differenceSummary = plotMeanAndConfidenceInterval( ...
        axesHandle, frequencyHz, differenceValues, ...
        colors.difference, "MISO minus SISO");
    yline(axesHandle, 0, "k:");
    xlabel(axesHandle, "Frequency (Hz)");
    ylabel(axesHandle, "MAP gain difference");
    title(axesHandle, "B  Paired model difference");
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    modelValues = empiricalResults.statisticalResults. ...
        modelComparisonValues;
    bandRows = modelValues.Group == "NC" & ...
        modelValues.Pathway == "MAP" & ...
        modelValues.Metric == "Gain";
    bandData = modelValues(bandRows, :);
    modelStatistics = empiricalResults.statisticalResults. ...
        modelComparisons;
    statisticRows = modelStatistics.Group == "NC" & ...
        modelStatistics.Pathway == "MAP" & ...
        modelStatistics.Metric == "Gain";
    bandStatistics = modelStatistics(statisticRows, :);
    bandNames = string(analysisSettings.frequencyBandNames(:));
    hold(axesHandle, "on");

    for bandIndex = 1:numel(bandNames)
        rows = bandData.Band == bandNames(bandIndex);
        selected = bandData(rows, :);
        xMiso = 2*bandIndex - 1;
        xSiso = 2*bandIndex;
        for subjectIndex = 1:height(selected)
            plot(axesHandle, [xMiso xSiso], ...
                [selected.MISOValue(subjectIndex), ...
                 selected.SISOValue(subjectIndex)], ...
                "-", "Color", [0.78 0.78 0.78], ...
                "HandleVisibility", "off");
        end
        scatter(axesHandle, repmat(xMiso, height(selected), 1), ...
            selected.MISOValue, 18, colors.miso, "filled");
        scatter(axesHandle, repmat(xSiso, height(selected), 1), ...
            selected.SISOValue, 18, colors.siso, "filled");

        statisticRow = bandStatistics.Band == bandNames(bandIndex);
        if any(statisticRow)
            adjustedP = bandStatistics.BHAdjustedP( ...
                find(statisticRow, 1));
            allBandValues = [selected.MISOValue; selected.SISOValue];
            labelY = max(allBandValues, [], "omitnan");
            if isfinite(labelY) && isfinite(adjustedP)
                text(axesHandle, mean([xMiso xSiso]), labelY, ...
                    "q=" + compose("%.3g", adjustedP), ...
                    "HorizontalAlignment", "center", ...
                    "VerticalAlignment", "bottom", ...
                    "FontSize", 8);
            end
        end
    end
    tickLabels = strings(2*numel(bandNames), 1);
    for bandIndex = 1:numel(bandNames)
        tickLabels(2*bandIndex - 1) = bandNames(bandIndex) + " M";
        tickLabels(2*bandIndex) = bandNames(bandIndex) + " S";
    end
    axesHandle.XTick = 1:(2*numel(bandNames));
    axesHandle.XTickLabel = tickLabels;
    axesHandle.XTickLabelRotation = 30;
    ylabel(axesHandle, "Participant MAP gain");
    title(axesHandle, "C  Paired participant band values");
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    yyaxis(axesHandle, "left");
    plot(axesHandle, frequencyHz, ...
        ncMiso.inputRelationship.coherence.mean, ...
        "Color", [0.20 0.60 0.50], "LineWidth", 1.4);
    ylabel(axesHandle, "Input coherence");
    ylim(axesHandle, [0 1]);
    yyaxis(axesHandle, "right");
    semilogy(axesHandle, frequencyHz, ...
        ncMiso.diagnostics.normalizedConditionNumber.mean, ...
        "Color", [0.25 0.25 0.25], "LineWidth", 1.4);
    ylabel(axesHandle, "Normalized condition number");
    xlabel(axesHandle, "Frequency (Hz)");
    title(axesHandle, "D  Empirical identifiability diagnostics");
    grid(axesHandle, "on");

    frequencySource = table( ...
        frequencyHz, misoSummary.mean, misoSummary.lower95, ...
        misoSummary.upper95, sisoSummary.mean, ...
        sisoSummary.lower95, sisoSummary.upper95, ...
        differenceSummary.mean, differenceSummary.lower95, ...
        differenceSummary.upper95, ...
        ncMiso.inputRelationship.coherence.mean, ...
        ncMiso.diagnostics.normalizedConditionNumber.mean, ...
        'VariableNames', { ...
            'FrequencyHz', 'MISOMean', 'MISO95Lower', 'MISO95Upper', ...
            'SISOMean', 'SISO95Lower', 'SISO95Upper', ...
            'DifferenceMean', 'Difference95Lower', ...
            'Difference95Upper', 'InputCoherenceMean', ...
            'NormalizedConditionNumberMean'});
    sourceData.frequency = frequencySource;
    sourceData.bandValues = bandData;
    sourceData.bandStatistics = bandStatistics;
    sourceData.commonSubjectIds = commonSubjectIds;

end
