function robustnessResults = runApproachPaperRobustness( ...
    subjectResults, statisticalResults, analysisSettings, ...
    robustnessSettings)
% runApproachPaperRobustness Run all empirical checks for retained NC data.

    surrogateSummary = table();
    surrogateShiftLog = table();
    delaySummary = table();
    sensitivitySummary = table();
    sensitivityRunLog = table();
    lambdaSummary = table();
    subjectRunLog = table();

    for subjectIndex = 1:numel(subjectResults)
        subject = subjectResults{subjectIndex};
        if isempty(subject) || ...
                ~subject.runStatus.analysisSucceeded || ...
                upper(string(subject.subjectInfo.group)) ~= "NC" || ...
                ~isfield(subject, "analysisInput") || ...
                isempty(fieldnames(subject.analysisInput))
            continue
        end

        subjectId = string(subject.subjectInfo.subjectID);
        status = "Completed";
        message = "";

        try
            surrogateSettings.numSurrogates = ...
                robustnessSettings.numSurrogates;
            surrogateSettings.randomSeed = ...
                robustnessSettings.randomSeed + subjectIndex;
            surrogateSettings.minimumShiftSeconds = ...
                robustnessSettings.minimumShiftSeconds;
            surrogate = runCo2CircularShiftSurrogates( ...
                subject.analysisInput, analysisSettings, ...
                surrogateSettings);
            surrogate.summary.SubjectID = repmat( ...
                subjectId, height(surrogate.summary), 1);
            surrogate.shiftLog.SubjectID = repmat( ...
                subjectId, height(surrogate.shiftLog), 1);
            surrogateSummary = [surrogateSummary; surrogate.summary];
            surrogateShiftLog = [ ...
                surrogateShiftLog; surrogate.shiftLog];

            delay = runCo2DelaySensitivity( ...
                subject.analysisInput, analysisSettings, ...
                robustnessSettings.delaysSeconds);
            delay.summary.SubjectID = repmat( ...
                subjectId, height(delay.summary), 1);
            delaySummary = [delaySummary; delay.summary];

            sensitivity = runAnalysisSettingSensitivity( ...
                subject.analysisInput, analysisSettings, ...
                robustnessSettings.sensitivityVariants);
            sensitivity.summary.SubjectID = repmat( ...
                subjectId, height(sensitivity.summary), 1);
            sensitivity.runLog.SubjectID = repmat( ...
                subjectId, height(sensitivity.runLog), 1);
            sensitivitySummary = [ ...
                sensitivitySummary; sensitivity.summary];
            sensitivityRunLog = [ ...
                sensitivityRunLog; sensitivity.runLog];

            lambda = runMisoLambdaPath( ...
                subject.analysisInput, analysisSettings, ...
                robustnessSettings.lambdas);
            lambda.summary.SubjectID = repmat( ...
                subjectId, height(lambda.summary), 1);
            lambdaSummary = [lambdaSummary; lambda.summary];
        catch errorInfo
            status = "Failed";
            message = string(errorInfo.message);
        end

        subjectRunLog = [subjectRunLog; table( ...
            subjectId, status, message, ...
            'VariableNames', {'SubjectID', 'Status', 'Message'})];
    end

    robustnessResults.surrogateSummary = surrogateSummary;
    robustnessResults.surrogateShiftLog = surrogateShiftLog;
    [robustnessResults.surrogateGroupDistribution, ...
        robustnessResults.surrogateTests] = ...
        summarizeSurrogateGroupNull(surrogateSummary);
    robustnessResults.delaySummary = delaySummary;
    robustnessResults.sensitivitySummary = sensitivitySummary;
    robustnessResults.sensitivityRunLog = sensitivityRunLog;
    robustnessResults.lambdaSummary = lambdaSummary;
    robustnessResults.influence = calculateLeaveOneOutInfluence( ...
        statisticalResults.modelComparisonValues);
    robustnessResults.subjectRunLog = subjectRunLog;
    robustnessResults.settings = robustnessSettings;

end

function [distributionTable, testTable] = ...
    summarizeSurrogateGroupNull(surrogateSummary)
% summarizeSurrogateGroupNull Test the group mean against shifted timing.

    distributionTable = table();
    testTable = table();
    if isempty(surrogateSummary)
        return
    end

    pathways = unique(surrogateSummary.Pathway, "stable");
    bands = unique(surrogateSummary.Band, "stable");
    surrogateIndices = unique( ...
        surrogateSummary.SurrogateIndex, "sorted");

    for pathwayIndex = 1:numel(pathways)
        for bandIndex = 1:numel(bands)
            familyMask = surrogateSummary.Pathway == ...
                pathways(pathwayIndex) & ...
                surrogateSummary.Band == bands(bandIndex);
            familyRows = surrogateSummary(familyMask, :);

            groupMeans = NaN(numel(surrogateIndices), 1);
            resultTypes = strings(numel(surrogateIndices), 1);
            for surrogateIndex = 1:numel(surrogateIndices)
                currentIndex = surrogateIndices(surrogateIndex);
                currentRows = familyRows.SurrogateIndex == currentIndex;
                groupMeans(surrogateIndex) = mean( ...
                    familyRows.MISOminusSISO(currentRows), "omitnan");
                if currentIndex == 0
                    resultTypes(surrogateIndex) = "Observed";
                else
                    resultTypes(surrogateIndex) = "Surrogate null";
                end
            end

            currentDistribution = table( ...
                repmat(pathways(pathwayIndex), ...
                    numel(surrogateIndices), 1), ...
                repmat(bands(bandIndex), ...
                    numel(surrogateIndices), 1), ...
                surrogateIndices, resultTypes, groupMeans, ...
                'VariableNames', { ...
                    'Pathway', 'Band', 'SurrogateIndex', ...
                    'ResultType', 'GroupMeanDifference'});
            distributionTable = [ ...
                distributionTable; currentDistribution];

            observedDifference = groupMeans(surrogateIndices == 0);
            nullDifferences = groupMeans(surrogateIndices > 0);
            empiricalP = NaN;
            if ~isempty(observedDifference) && ...
                    any(isfinite(nullDifferences))
                empiricalP = (1 + sum( ...
                    abs(nullDifferences) >= ...
                    abs(observedDifference))) / ...
                    (1 + sum(isfinite(nullDifferences)));
            end

            currentTest = table( ...
                pathways(pathwayIndex), bands(bandIndex), ...
                observedDifference, ...
                mean(nullDifferences, "omitnan"), ...
                prctile(nullDifferences, 2.5), ...
                prctile(nullDifferences, 97.5), ...
                empiricalP, numel(nullDifferences), ...
                'VariableNames', { ...
                    'Pathway', 'Band', 'ObservedGroupMeanDifference', ...
                    'NullMeanDifference', 'Null95Lower', ...
                    'Null95Upper', 'EmpiricalP', 'NumSurrogates'});
            testTable = [testTable; currentTest];
        end
    end

end
